/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSKELETONBLENDEDGEOMETRYEVENTSOURCEFIELDS_H_
#define _OSGSKELETONBLENDEDGEOMETRYEVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxAnimationDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class SkeletonBlendedGeometryEventSource;

OSG_GEN_CONTAINERPTR(SkeletonBlendedGeometryEventSource);
/*! \ingroup GrpContribToolboxAnimationFieldTraits
    \ingroup GrpLibOSGContribToolboxAnimation
 */
template <>
struct FieldTraits<SkeletonBlendedGeometryEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<SkeletonBlendedGeometryEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<SkeletonBlendedGeometryEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXANIMATION_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<SkeletonBlendedGeometryEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSkeletonBlendedGeometryEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<SkeletonBlendedGeometryEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSkeletonBlendedGeometryEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<SkeletonBlendedGeometryEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSkeletonBlendedGeometryEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<SkeletonBlendedGeometryEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSkeletonBlendedGeometryEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<SkeletonBlendedGeometryEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSkeletonBlendedGeometryEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<SkeletonBlendedGeometryEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSkeletonBlendedGeometryEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<SkeletonBlendedGeometryEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSkeletonBlendedGeometryEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<SkeletonBlendedGeometryEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSkeletonBlendedGeometryEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxAnimationFieldSFields */
typedef PointerSField<SkeletonBlendedGeometryEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecSkeletonBlendedGeometryEventSourcePtr;
/*! \ingroup GrpContribToolboxAnimationFieldSFields */
typedef PointerSField<SkeletonBlendedGeometryEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecSkeletonBlendedGeometryEventSourcePtr;
/*! \ingroup GrpContribToolboxAnimationFieldSFields */
typedef PointerSField<SkeletonBlendedGeometryEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakSkeletonBlendedGeometryEventSourcePtr;
/*! \ingroup GrpContribToolboxAnimationFieldSFields */
typedef PointerSField<SkeletonBlendedGeometryEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedSkeletonBlendedGeometryEventSourcePtr;


/*! \ingroup GrpContribToolboxAnimationFieldMFields */
typedef PointerMField<SkeletonBlendedGeometryEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecSkeletonBlendedGeometryEventSourcePtr;
/*! \ingroup GrpContribToolboxAnimationFieldMFields */
typedef PointerMField<SkeletonBlendedGeometryEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecSkeletonBlendedGeometryEventSourcePtr;
/*! \ingroup GrpContribToolboxAnimationFieldMFields */
typedef PointerMField<SkeletonBlendedGeometryEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakSkeletonBlendedGeometryEventSourcePtr;
/*! \ingroup GrpContribToolboxAnimationFieldMFields */
typedef PointerMField<SkeletonBlendedGeometryEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedSkeletonBlendedGeometryEventSourcePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxAnimationFieldSFields \ingroup GrpLibOSGContribToolboxAnimation */
struct SFRecSkeletonBlendedGeometryEventSourcePtr : 
    public PointerSField<SkeletonBlendedGeometryEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxAnimationFieldSFields \ingroup GrpLibOSGContribToolboxAnimation */
struct SFUnrecSkeletonBlendedGeometryEventSourcePtr : 
    public PointerSField<SkeletonBlendedGeometryEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxAnimationFieldSFields \ingroup GrpLibOSGContribToolboxAnimation */
struct SFWeakSkeletonBlendedGeometryEventSourcePtr :
    public PointerSField<SkeletonBlendedGeometryEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxAnimationFieldSFields \ingroup GrpLibOSGContribToolboxAnimation */
struct SFUncountedSkeletonBlendedGeometryEventSourcePtr :
    public PointerSField<SkeletonBlendedGeometryEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxAnimationFieldMFields \ingroup GrpLibOSGContribToolboxAnimation */
struct MFRecSkeletonBlendedGeometryEventSourcePtr :
    public PointerMField<SkeletonBlendedGeometryEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxAnimationFieldMFields \ingroup GrpLibOSGContribToolboxAnimation */
struct MFUnrecSkeletonBlendedGeometryEventSourcePtr :
    public PointerMField<SkeletonBlendedGeometryEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxAnimationFieldMFields \ingroup GrpLibOSGContribToolboxAnimation */
struct MFWeakSkeletonBlendedGeometryEventSourcePtr :
    public PointerMField<SkeletonBlendedGeometryEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxAnimationFieldMFields \ingroup GrpLibOSGContribToolboxAnimation */
struct MFUncountedSkeletonBlendedGeometryEventSourcePtr :
    public PointerMField<SkeletonBlendedGeometryEventSource *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSKELETONBLENDEDGEOMETRYEVENTSOURCEFIELDS_H_ */
