/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *          David Naylor                                                     *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSKELETONBLENDEDGEOMETRYFIELDS_H_
#define _OSGSKELETONBLENDEDGEOMETRYFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxAnimationDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class SkeletonBlendedGeometry;

OSG_GEN_CONTAINERPTR(SkeletonBlendedGeometry);
/*! \ingroup GrpContribToolboxAnimationFieldTraits
    \ingroup GrpLibOSGContribToolboxAnimation
 */
template <>
struct FieldTraits<SkeletonBlendedGeometry *, nsOSG> :
    public FieldTraitsFCPtrBase<SkeletonBlendedGeometry *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<SkeletonBlendedGeometry *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXANIMATION_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<SkeletonBlendedGeometry *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSkeletonBlendedGeometryPtr"; 
}

template<> inline
const Char8 *FieldTraits<SkeletonBlendedGeometry *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSkeletonBlendedGeometryPtr"; 
}

template<> inline
const Char8 *FieldTraits<SkeletonBlendedGeometry *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSkeletonBlendedGeometryPtr"; 
}

template<> inline
const Char8 *FieldTraits<SkeletonBlendedGeometry *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSkeletonBlendedGeometryPtr"; 
}

template<> inline
const Char8 *FieldTraits<SkeletonBlendedGeometry *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSkeletonBlendedGeometryPtr"; 
}

template<> inline
const Char8 *FieldTraits<SkeletonBlendedGeometry *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSkeletonBlendedGeometryPtr"; 
}

template<> inline
const Char8 *FieldTraits<SkeletonBlendedGeometry *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSkeletonBlendedGeometryPtr"; 
}

template<> inline
const Char8 *FieldTraits<SkeletonBlendedGeometry *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSkeletonBlendedGeometryPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxAnimationFieldSFields */
typedef PointerSField<SkeletonBlendedGeometry *,
                      RecordedRefCountPolicy, nsOSG  > SFRecSkeletonBlendedGeometryPtr;
/*! \ingroup GrpContribToolboxAnimationFieldSFields */
typedef PointerSField<SkeletonBlendedGeometry *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecSkeletonBlendedGeometryPtr;
/*! \ingroup GrpContribToolboxAnimationFieldSFields */
typedef PointerSField<SkeletonBlendedGeometry *,
                      WeakRefCountPolicy, nsOSG      > SFWeakSkeletonBlendedGeometryPtr;
/*! \ingroup GrpContribToolboxAnimationFieldSFields */
typedef PointerSField<SkeletonBlendedGeometry *,
                      NoRefCountPolicy, nsOSG        > SFUncountedSkeletonBlendedGeometryPtr;


/*! \ingroup GrpContribToolboxAnimationFieldMFields */
typedef PointerMField<SkeletonBlendedGeometry *,
                      RecordedRefCountPolicy, nsOSG  > MFRecSkeletonBlendedGeometryPtr;
/*! \ingroup GrpContribToolboxAnimationFieldMFields */
typedef PointerMField<SkeletonBlendedGeometry *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecSkeletonBlendedGeometryPtr;
/*! \ingroup GrpContribToolboxAnimationFieldMFields */
typedef PointerMField<SkeletonBlendedGeometry *,
                      WeakRefCountPolicy, nsOSG      > MFWeakSkeletonBlendedGeometryPtr;
/*! \ingroup GrpContribToolboxAnimationFieldMFields */
typedef PointerMField<SkeletonBlendedGeometry *,
                      NoRefCountPolicy, nsOSG        > MFUncountedSkeletonBlendedGeometryPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxAnimationFieldSFields \ingroup GrpLibOSGContribToolboxAnimation */
struct SFRecSkeletonBlendedGeometryPtr : 
    public PointerSField<SkeletonBlendedGeometry *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxAnimationFieldSFields \ingroup GrpLibOSGContribToolboxAnimation */
struct SFUnrecSkeletonBlendedGeometryPtr : 
    public PointerSField<SkeletonBlendedGeometry *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxAnimationFieldSFields \ingroup GrpLibOSGContribToolboxAnimation */
struct SFWeakSkeletonBlendedGeometryPtr :
    public PointerSField<SkeletonBlendedGeometry *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxAnimationFieldSFields \ingroup GrpLibOSGContribToolboxAnimation */
struct SFUncountedSkeletonBlendedGeometryPtr :
    public PointerSField<SkeletonBlendedGeometry *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxAnimationFieldMFields \ingroup GrpLibOSGContribToolboxAnimation */
struct MFRecSkeletonBlendedGeometryPtr :
    public PointerMField<SkeletonBlendedGeometry *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxAnimationFieldMFields \ingroup GrpLibOSGContribToolboxAnimation */
struct MFUnrecSkeletonBlendedGeometryPtr :
    public PointerMField<SkeletonBlendedGeometry *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxAnimationFieldMFields \ingroup GrpLibOSGContribToolboxAnimation */
struct MFWeakSkeletonBlendedGeometryPtr :
    public PointerMField<SkeletonBlendedGeometry *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxAnimationFieldMFields \ingroup GrpLibOSGContribToolboxAnimation */
struct MFUncountedSkeletonBlendedGeometryPtr :
    public PointerMField<SkeletonBlendedGeometry *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSKELETONBLENDEDGEOMETRYFIELDS_H_ */
