/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TextComponentEventSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"




#include "OSGTextComponentEventSourceBase.h"
#include "OSGTextComponentEventSource.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TextComponentEventSource
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<TextComponentEventSource *, nsOSG>::_type(
    "TextComponentEventSourcePtr", 
    "ComponentEventSourcePtr", 
    TextComponentEventSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(TextComponentEventSource *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TextComponentEventSource *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TextComponentEventSource *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TextComponentEventSourceBase::classDescInserter(TypeObject &oType)
{
}


TextComponentEventSourceBase::TypeObject TextComponentEventSourceBase::_type(
    TextComponentEventSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&TextComponentEventSourceBase::createEmptyLocal),
    TextComponentEventSource::initMethod,
    TextComponentEventSource::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TextComponentEventSource::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"TextComponentEventSource\"\n"
    "    parent=\"ComponentEventSource\"\n"
    "    library=\"ContribToolboxUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    ">\n"
    "<!--     parentProducer=\"Component\" -->\n"
    "<!--\n"
    "    <ProducedEvent\n"
    "        name=\"TextValueChanged\"\n"
    "        detailsType=\"TextEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"CaretChanged\"\n"
    "        detailsType=\"CaretEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "-->\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TextComponentEventSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &TextComponentEventSourceBase::getType(void) const
{
    return _type;
}

UInt32 TextComponentEventSourceBase::getContainerSize(void) const
{
    return sizeof(TextComponentEventSource);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

SizeT TextComponentEventSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void TextComponentEventSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void TextComponentEventSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
TextComponentEventSourceTransitPtr TextComponentEventSourceBase::createLocal(BitVector bFlags)
{
    TextComponentEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<TextComponentEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
TextComponentEventSourceTransitPtr TextComponentEventSourceBase::createDependent(BitVector bFlags)
{
    TextComponentEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<TextComponentEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
TextComponentEventSourceTransitPtr TextComponentEventSourceBase::create(void)
{
    TextComponentEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<TextComponentEventSource>(tmpPtr);
    }

    return fc;
}

TextComponentEventSource *TextComponentEventSourceBase::createEmptyLocal(BitVector bFlags)
{
    TextComponentEventSource *returnValue;

    newPtr<TextComponentEventSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
TextComponentEventSource *TextComponentEventSourceBase::createEmpty(void)
{
    TextComponentEventSource *returnValue;

    newPtr<TextComponentEventSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr TextComponentEventSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    TextComponentEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TextComponentEventSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr TextComponentEventSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    TextComponentEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TextComponentEventSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr TextComponentEventSourceBase::shallowCopy(void) const
{
    TextComponentEventSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const TextComponentEventSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

TextComponentEventSourceBase::TextComponentEventSourceBase(void) :
    Inherited()
{
}

TextComponentEventSourceBase::TextComponentEventSourceBase(const TextComponentEventSourceBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

TextComponentEventSourceBase::~TextComponentEventSourceBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void TextComponentEventSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TextComponentEventSource *pThis = static_cast<TextComponentEventSource *>(this);

    pThis->execSync(static_cast<TextComponentEventSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *TextComponentEventSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    TextComponentEventSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const TextComponentEventSource *>(pRefAspect),
                  dynamic_cast<const TextComponentEventSource *>(this));

    return returnValue;
}
#endif

void TextComponentEventSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
