/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTEXTFIELDEVENTSOURCEFIELDS_H_
#define _OSGTEXTFIELDEVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TextFieldEventSource;

OSG_GEN_CONTAINERPTR(TextFieldEventSource);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<TextFieldEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<TextFieldEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TextFieldEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TextFieldEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTextFieldEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TextFieldEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTextFieldEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TextFieldEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTextFieldEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TextFieldEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTextFieldEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TextFieldEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTextFieldEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TextFieldEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTextFieldEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TextFieldEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTextFieldEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TextFieldEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTextFieldEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TextFieldEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTextFieldEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TextFieldEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTextFieldEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TextFieldEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTextFieldEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TextFieldEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTextFieldEventSourcePtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TextFieldEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTextFieldEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TextFieldEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTextFieldEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TextFieldEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTextFieldEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TextFieldEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTextFieldEventSourcePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecTextFieldEventSourcePtr : 
    public PointerSField<TextFieldEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecTextFieldEventSourcePtr : 
    public PointerSField<TextFieldEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakTextFieldEventSourcePtr :
    public PointerSField<TextFieldEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedTextFieldEventSourcePtr :
    public PointerSField<TextFieldEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecTextFieldEventSourcePtr :
    public PointerMField<TextFieldEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecTextFieldEventSourcePtr :
    public PointerMField<TextFieldEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakTextFieldEventSourcePtr :
    public PointerMField<TextFieldEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedTextFieldEventSourcePtr :
    public PointerMField<TextFieldEventSource *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTEXTFIELDEventSourceFIELDS_H_ */
