/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTEXTCOMPONENTFIELDS_H_
#define _OSGTEXTCOMPONENTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TextComponent;

OSG_GEN_CONTAINERPTR(TextComponent);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<TextComponent *, nsOSG> :
    public FieldTraitsFCPtrBase<TextComponent *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TextComponent *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TextComponent *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTextComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextComponent *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTextComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextComponent *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTextComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextComponent *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTextComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextComponent *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTextComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextComponent *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTextComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextComponent *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTextComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextComponent *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTextComponentPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TextComponent *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTextComponentPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TextComponent *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTextComponentPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TextComponent *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTextComponentPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TextComponent *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTextComponentPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TextComponent *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTextComponentPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TextComponent *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTextComponentPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TextComponent *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTextComponentPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TextComponent *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTextComponentPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecTextComponentPtr : 
    public PointerSField<TextComponent *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecTextComponentPtr : 
    public PointerSField<TextComponent *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakTextComponentPtr :
    public PointerSField<TextComponent *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedTextComponentPtr :
    public PointerSField<TextComponent *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecTextComponentPtr :
    public PointerMField<TextComponent *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecTextComponentPtr :
    public PointerMField<TextComponent *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakTextComponentPtr :
    public PointerMField<TextComponent *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedTextComponentPtr :
    public PointerMField<TextComponent *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTEXTCOMPONENTFIELDS_H_ */
