/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTEXTFIELDFIELDS_H_
#define _OSGTEXTFIELDFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TextField;

OSG_GEN_CONTAINERPTR(TextField);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<TextField *, nsOSG> :
    public FieldTraitsFCPtrBase<TextField *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TextField *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TextField *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTextFieldPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextField *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTextFieldPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextField *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTextFieldPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextField *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTextFieldPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextField *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTextFieldPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextField *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTextFieldPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextField *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTextFieldPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextField *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTextFieldPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TextField *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTextFieldPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TextField *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTextFieldPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TextField *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTextFieldPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TextField *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTextFieldPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TextField *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTextFieldPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TextField *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTextFieldPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TextField *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTextFieldPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TextField *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTextFieldPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecTextFieldPtr : 
    public PointerSField<TextField *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecTextFieldPtr : 
    public PointerSField<TextField *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakTextFieldPtr :
    public PointerSField<TextField *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedTextFieldPtr :
    public PointerSField<TextField *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecTextFieldPtr :
    public PointerMField<TextField *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecTextFieldPtr :
    public PointerMField<TextField *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakTextFieldPtr :
    public PointerMField<TextField *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedTextFieldPtr :
    public PointerMField<TextField *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTEXTFIELDFIELDS_H_ */
