/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TextFieldEventSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"


#include "OSGTextFieldEventSourceBase.h"
#include "OSGTextFieldEventSource.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TextFieldEventSource
    A UI Text Field
 */



/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<TextFieldEventSource *, nsOSG>::_type(
    "TextFieldEventSourcePtr",
    "TextComponentEventSourcePtr",
    TextFieldEventSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(TextFieldEventSource *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TextFieldEventSource *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TextFieldEventSource *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TextFieldEventSourceBase::classDescInserter(TypeObject &oType)
{
}


TextFieldEventSourceBase::TypeObject TextFieldEventSourceBase::_type(
    TextFieldEventSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&TextFieldEventSourceBase::createEmptyLocal),
    TextFieldEventSource::initMethod,
    TextFieldEventSource::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TextFieldEventSource::classDescInserter),
    false,
    0,
    "",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TextFieldEventSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &TextFieldEventSourceBase::getType(void) const
{
    return _type;
}

UInt32 TextFieldEventSourceBase::getContainerSize(void) const
{
    return sizeof(TextFieldEventSource);
}



/*------------------------------ access -----------------------------------*/

SizeT TextFieldEventSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    return returnValue;
}

void TextFieldEventSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);
}

void TextFieldEventSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);
}

//! create a new instance of the class
TextFieldEventSourceTransitPtr TextFieldEventSourceBase::createLocal(BitVector bFlags)
{
    TextFieldEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<TextFieldEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
TextFieldEventSourceTransitPtr TextFieldEventSourceBase::createDependent(BitVector bFlags)
{
    TextFieldEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<TextFieldEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
TextFieldEventSourceTransitPtr TextFieldEventSourceBase::create(void)
{
    TextFieldEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<TextFieldEventSource>(tmpPtr);
    }

    return fc;
}

TextFieldEventSource *TextFieldEventSourceBase::createEmptyLocal(BitVector bFlags)
{
    TextFieldEventSource *returnValue;

    newPtr<TextFieldEventSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
TextFieldEventSource *TextFieldEventSourceBase::createEmpty(void)
{
    TextFieldEventSource *returnValue;

    newPtr<TextFieldEventSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr TextFieldEventSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    TextFieldEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TextFieldEventSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr TextFieldEventSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    TextFieldEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TextFieldEventSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr TextFieldEventSourceBase::shallowCopy(void) const
{
    TextFieldEventSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const TextFieldEventSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

TextFieldEventSourceBase::TextFieldEventSourceBase(void) :
    Inherited()
{
}

TextFieldEventSourceBase::TextFieldEventSourceBase(const TextFieldEventSourceBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

TextFieldEventSourceBase::~TextFieldEventSourceBase(void)
{
}


#ifdef OSG_MT_CPTR_ASPECT
void TextFieldEventSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TextFieldEventSource *pThis = static_cast<TextFieldEventSource *>(this);

    pThis->execSync(static_cast<TextFieldEventSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *TextFieldEventSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    TextFieldEventSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const TextFieldEventSource *>(pRefAspect),
                  dynamic_cast<const TextFieldEventSource *>(this));

    return returnValue;
}
#endif

void TextFieldEventSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();

}

OSG_END_NAMESPACE
