/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *          Mark Stenerson                                                   *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGDIALOGWINDOWEVENTSOURCEFIELDS_H_
#define _OSGDIALOGWINDOWEVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class DialogWindowEventSource;

OSG_GEN_CONTAINERPTR(DialogWindowEventSource);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<DialogWindowEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<DialogWindowEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<DialogWindowEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<DialogWindowEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecDialogWindowEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<DialogWindowEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecDialogWindowEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<DialogWindowEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakDialogWindowEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<DialogWindowEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdDialogWindowEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<DialogWindowEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecDialogWindowEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<DialogWindowEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecDialogWindowEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<DialogWindowEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakDialogWindowEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<DialogWindowEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdDialogWindowEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<DialogWindowEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecDialogWindowEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<DialogWindowEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecDialogWindowEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<DialogWindowEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakDialogWindowEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<DialogWindowEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedDialogWindowEventSourcePtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<DialogWindowEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecDialogWindowEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<DialogWindowEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecDialogWindowEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<DialogWindowEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakDialogWindowEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<DialogWindowEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedDialogWindowEventSourcePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecDialogWindowEventSourcePtr : 
    public PointerSField<DialogWindowEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecDialogWindowEventSourcePtr : 
    public PointerSField<DialogWindowEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakDialogWindowEventSourcePtr :
    public PointerSField<DialogWindowEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedDialogWindowEventSourcePtr :
    public PointerSField<DialogWindowEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecDialogWindowEventSourcePtr :
    public PointerMField<DialogWindowEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecDialogWindowEventSourcePtr :
    public PointerMField<DialogWindowEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakDialogWindowEventSourcePtr :
    public PointerMField<DialogWindowEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedDialogWindowEventSourcePtr :
    public PointerMField<DialogWindowEventSource *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGDIALOGWINDOWEventSourceFIELDS_H_ */
