/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *          Mark Stenerson                                                   *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class DialogWindow!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"



#include "OSGTextureObjChunk.h"         // ErrorIcon Class

#include "OSGDialogWindowBase.h"
#include "OSGDialogWindow.h"
#include "OSGDialogWindowEventSource.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::DialogWindow
    A UI Dialog Window.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var TextureObjChunk * DialogWindowBase::_sfErrorIcon
    
*/

/*! \var TextureObjChunk * DialogWindowBase::_sfQuestionIcon
    
*/

/*! \var TextureObjChunk * DialogWindowBase::_sfDefaultIcon
    
*/

/*! \var bool            DialogWindowBase::_sfShowCancel
    
*/

/*! \var std::string     DialogWindowBase::_sfInputValues
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<DialogWindow *, nsOSG>::_type(
    "DialogWindowPtr", 
    "InternalWindowPtr", 
    DialogWindow::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(DialogWindow *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           DialogWindow *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           DialogWindow *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void DialogWindowBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecTextureObjChunkPtr::Description(
        SFUnrecTextureObjChunkPtr::getClassType(),
        "ErrorIcon",
        "",
        ErrorIconFieldId, ErrorIconFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DialogWindow::editHandleErrorIcon),
        static_cast<FieldGetMethodSig >(&DialogWindow::getHandleErrorIcon));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUnrecTextureObjChunkPtr::Description(
        SFUnrecTextureObjChunkPtr::getClassType(),
        "QuestionIcon",
        "",
        QuestionIconFieldId, QuestionIconFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DialogWindow::editHandleQuestionIcon),
        static_cast<FieldGetMethodSig >(&DialogWindow::getHandleQuestionIcon));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUnrecTextureObjChunkPtr::Description(
        SFUnrecTextureObjChunkPtr::getClassType(),
        "DefaultIcon",
        "",
        DefaultIconFieldId, DefaultIconFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DialogWindow::editHandleDefaultIcon),
        static_cast<FieldGetMethodSig >(&DialogWindow::getHandleDefaultIcon));

    oType.addInitialDesc(pDesc);

    pDesc = new SFBool::Description(
        SFBool::getClassType(),
        "ShowCancel",
        "",
        ShowCancelFieldId, ShowCancelFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DialogWindow::editHandleShowCancel),
        static_cast<FieldGetMethodSig >(&DialogWindow::getHandleShowCancel));

    oType.addInitialDesc(pDesc);

    pDesc = new SFString::Description(
        SFString::getClassType(),
        "InputValues",
        "",
        InputValuesFieldId, InputValuesFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&DialogWindow::editHandleInputValues),
        static_cast<FieldGetMethodSig >(&DialogWindow::getHandleInputValues));

    oType.addInitialDesc(pDesc);
}


DialogWindowBase::TypeObject DialogWindowBase::_type(
    DialogWindowBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&DialogWindowBase::createEmptyLocal),
    DialogWindow::initMethod,
    DialogWindow::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&DialogWindow::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"DialogWindow\"\n"
    "    parent=\"InternalWindow\"\n"
    "    library=\"ContribToolboxUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com), Mark Stenerson             \"\n"
    "    parentProducer=\"AbstractWindow\"\n"
    ">\n"
    "A UI Dialog Window.\n"
    "    <Field\n"
    "        name=\"ErrorIcon\"\n"
    "        type=\"TextureObjChunk\"\n"
    "        category=\"pointer\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        defaultValue=\"NULL\"\n"
    "        access=\"public\"\n"
    "    >\n"
    "    </Field>\n"
    "    <Field\n"
    "        name=\"QuestionIcon\"\n"
    "        type=\"TextureObjChunk\"\n"
    "        category=\"pointer\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        defaultValue=\"NULL\"\n"
    "        access=\"public\"\n"
    "    >\n"
    "    </Field>\n"
    "    <Field\n"
    "        name=\"DefaultIcon\"\n"
    "        type=\"TextureObjChunk\"\n"
    "        category=\"pointer\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        defaultValue=\"NULL\"\n"
    "        access=\"public\"\n"
    "    >\n"
    "    </Field>\n"
    "    <Field\n"
    "        name=\"ShowCancel\"\n"
    "        type=\"bool\"\n"
    "        category=\"data\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        defaultValue=\"true\"\n"
    "        access=\"public\"\n"
    "    >\n"
    "    </Field>\n"
    "    <Field\n"
    "        name=\"InputValues\"\n"
    "        type=\"std::string\"\n"
    "        category=\"data\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "    >\n"
    "    </Field>\n"
    "    <ProducedEvent\n"
    "        name=\"DialogWindowClosing\"\n"
    "        detailsType=\"DialogWindowEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"DialogWindowClosed\"\n"
    "        detailsType=\"DialogWindowEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "</FieldContainer>\n",
    "A UI Dialog Window.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &DialogWindowBase::getType(void)
{
    return _type;
}

const FieldContainerType &DialogWindowBase::getType(void) const
{
    return _type;
}

UInt32 DialogWindowBase::getContainerSize(void) const
{
    return sizeof(DialogWindow);
}

/*------------------------- decorator get ------------------------------*/


//! Get the DialogWindow::_sfErrorIcon field.
const SFUnrecTextureObjChunkPtr *DialogWindowBase::getSFErrorIcon(void) const
{
    return &_sfErrorIcon;
}

SFUnrecTextureObjChunkPtr *DialogWindowBase::editSFErrorIcon      (void)
{
    editSField(ErrorIconFieldMask);

    return &_sfErrorIcon;
}


//! Get the DialogWindow::_sfQuestionIcon field.
const SFUnrecTextureObjChunkPtr *DialogWindowBase::getSFQuestionIcon(void) const
{
    return &_sfQuestionIcon;
}

SFUnrecTextureObjChunkPtr *DialogWindowBase::editSFQuestionIcon   (void)
{
    editSField(QuestionIconFieldMask);

    return &_sfQuestionIcon;
}


//! Get the DialogWindow::_sfDefaultIcon field.
const SFUnrecTextureObjChunkPtr *DialogWindowBase::getSFDefaultIcon(void) const
{
    return &_sfDefaultIcon;
}

SFUnrecTextureObjChunkPtr *DialogWindowBase::editSFDefaultIcon    (void)
{
    editSField(DefaultIconFieldMask);

    return &_sfDefaultIcon;
}


SFBool *DialogWindowBase::editSFShowCancel(void)
{
    editSField(ShowCancelFieldMask);

    return &_sfShowCancel;
}

const SFBool *DialogWindowBase::getSFShowCancel(void) const
{
    return &_sfShowCancel;
}


SFString *DialogWindowBase::editSFInputValues(void)
{
    editSField(InputValuesFieldMask);

    return &_sfInputValues;
}

const SFString *DialogWindowBase::getSFInputValues(void) const
{
    return &_sfInputValues;
}






/*------------------------------ access -----------------------------------*/

SizeT DialogWindowBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (ErrorIconFieldMask & whichField))
    {
        returnValue += _sfErrorIcon.getBinSize();
    }
    if(FieldBits::NoField != (QuestionIconFieldMask & whichField))
    {
        returnValue += _sfQuestionIcon.getBinSize();
    }
    if(FieldBits::NoField != (DefaultIconFieldMask & whichField))
    {
        returnValue += _sfDefaultIcon.getBinSize();
    }
    if(FieldBits::NoField != (ShowCancelFieldMask & whichField))
    {
        returnValue += _sfShowCancel.getBinSize();
    }
    if(FieldBits::NoField != (InputValuesFieldMask & whichField))
    {
        returnValue += _sfInputValues.getBinSize();
    }

    return returnValue;
}

void DialogWindowBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (ErrorIconFieldMask & whichField))
    {
        _sfErrorIcon.copyToBin(pMem);
    }
    if(FieldBits::NoField != (QuestionIconFieldMask & whichField))
    {
        _sfQuestionIcon.copyToBin(pMem);
    }
    if(FieldBits::NoField != (DefaultIconFieldMask & whichField))
    {
        _sfDefaultIcon.copyToBin(pMem);
    }
    if(FieldBits::NoField != (ShowCancelFieldMask & whichField))
    {
        _sfShowCancel.copyToBin(pMem);
    }
    if(FieldBits::NoField != (InputValuesFieldMask & whichField))
    {
        _sfInputValues.copyToBin(pMem);
    }
}

void DialogWindowBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (ErrorIconFieldMask & whichField))
    {
        editSField(ErrorIconFieldMask);
        _sfErrorIcon.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (QuestionIconFieldMask & whichField))
    {
        editSField(QuestionIconFieldMask);
        _sfQuestionIcon.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (DefaultIconFieldMask & whichField))
    {
        editSField(DefaultIconFieldMask);
        _sfDefaultIcon.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (ShowCancelFieldMask & whichField))
    {
        editSField(ShowCancelFieldMask);
        _sfShowCancel.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (InputValuesFieldMask & whichField))
    {
        editSField(InputValuesFieldMask);
        _sfInputValues.copyFromBin(pMem);
    }
}

//! create a new instance of the class
DialogWindowTransitPtr DialogWindowBase::createLocal(BitVector bFlags)
{
    DialogWindowTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<DialogWindow>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
DialogWindowTransitPtr DialogWindowBase::createDependent(BitVector bFlags)
{
    DialogWindowTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<DialogWindow>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
DialogWindowTransitPtr DialogWindowBase::create(void)
{
    DialogWindowTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<DialogWindow>(tmpPtr);
    }

    return fc;
}

DialogWindow *DialogWindowBase::createEmptyLocal(BitVector bFlags)
{
    DialogWindow *returnValue;

    newPtr<DialogWindow>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
DialogWindow *DialogWindowBase::createEmpty(void)
{
    DialogWindow *returnValue;

    newPtr<DialogWindow>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr DialogWindowBase::shallowCopyLocal(
    BitVector bFlags) const
{
    DialogWindow *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const DialogWindow *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr DialogWindowBase::shallowCopyDependent(
    BitVector bFlags) const
{
    DialogWindow *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const DialogWindow *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr DialogWindowBase::shallowCopy(void) const
{
    DialogWindow *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const DialogWindow *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

DialogWindowBase::DialogWindowBase(void) :
    Inherited(),
    _sfErrorIcon              (NULL),
    _sfQuestionIcon           (NULL),
    _sfDefaultIcon            (NULL),
    _sfShowCancel             (bool(true)),
    _sfInputValues            ()
{
}

DialogWindowBase::DialogWindowBase(const DialogWindowBase &source) :
    Inherited(source),
    _sfErrorIcon              (NULL),
    _sfQuestionIcon           (NULL),
    _sfDefaultIcon            (NULL),
    _sfShowCancel             (source._sfShowCancel             ),
    _sfInputValues            (source._sfInputValues            )
{
}


/*-------------------------- destructors ----------------------------------*/

DialogWindowBase::~DialogWindowBase(void)
{
}

void DialogWindowBase::onCreate(const DialogWindow *source)
{
    Inherited::onCreate(source);

    if(source)
    {
        DialogWindow *pThis = static_cast<DialogWindow *>(this);

        pThis->setErrorIcon(source->getErrorIcon());

        pThis->setQuestionIcon(source->getQuestionIcon());

        pThis->setDefaultIcon(source->getDefaultIcon());
    }
    
    {
        DialogWindowEventSourceUnrecPtr evSrc = DialogWindowEventSource::create();
        setEventSource( evSrc );
    }
}

GetFieldHandlePtr DialogWindowBase::getHandleErrorIcon       (void) const
{
    SFUnrecTextureObjChunkPtr::GetHandlePtr returnValue(
        new  SFUnrecTextureObjChunkPtr::GetHandle(
             &_sfErrorIcon,
             this->getType().getFieldDesc(ErrorIconFieldId),
             const_cast<DialogWindowBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DialogWindowBase::editHandleErrorIcon      (void)
{
    SFUnrecTextureObjChunkPtr::EditHandlePtr returnValue(
        new  SFUnrecTextureObjChunkPtr::EditHandle(
             &_sfErrorIcon,
             this->getType().getFieldDesc(ErrorIconFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&DialogWindow::setErrorIcon,
                    static_cast<DialogWindow *>(this), _1));

    editSField(ErrorIconFieldMask);

    return returnValue;
}

GetFieldHandlePtr DialogWindowBase::getHandleQuestionIcon    (void) const
{
    SFUnrecTextureObjChunkPtr::GetHandlePtr returnValue(
        new  SFUnrecTextureObjChunkPtr::GetHandle(
             &_sfQuestionIcon,
             this->getType().getFieldDesc(QuestionIconFieldId),
             const_cast<DialogWindowBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DialogWindowBase::editHandleQuestionIcon   (void)
{
    SFUnrecTextureObjChunkPtr::EditHandlePtr returnValue(
        new  SFUnrecTextureObjChunkPtr::EditHandle(
             &_sfQuestionIcon,
             this->getType().getFieldDesc(QuestionIconFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&DialogWindow::setQuestionIcon,
                    static_cast<DialogWindow *>(this), _1));

    editSField(QuestionIconFieldMask);

    return returnValue;
}

GetFieldHandlePtr DialogWindowBase::getHandleDefaultIcon     (void) const
{
    SFUnrecTextureObjChunkPtr::GetHandlePtr returnValue(
        new  SFUnrecTextureObjChunkPtr::GetHandle(
             &_sfDefaultIcon,
             this->getType().getFieldDesc(DefaultIconFieldId),
             const_cast<DialogWindowBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DialogWindowBase::editHandleDefaultIcon    (void)
{
    SFUnrecTextureObjChunkPtr::EditHandlePtr returnValue(
        new  SFUnrecTextureObjChunkPtr::EditHandle(
             &_sfDefaultIcon,
             this->getType().getFieldDesc(DefaultIconFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&DialogWindow::setDefaultIcon,
                    static_cast<DialogWindow *>(this), _1));

    editSField(DefaultIconFieldMask);

    return returnValue;
}

GetFieldHandlePtr DialogWindowBase::getHandleShowCancel      (void) const
{
    SFBool::GetHandlePtr returnValue(
        new  SFBool::GetHandle(
             &_sfShowCancel,
             this->getType().getFieldDesc(ShowCancelFieldId),
             const_cast<DialogWindowBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DialogWindowBase::editHandleShowCancel     (void)
{
    SFBool::EditHandlePtr returnValue(
        new  SFBool::EditHandle(
             &_sfShowCancel,
             this->getType().getFieldDesc(ShowCancelFieldId),
             this));


    editSField(ShowCancelFieldMask);

    return returnValue;
}

GetFieldHandlePtr DialogWindowBase::getHandleInputValues     (void) const
{
    SFString::GetHandlePtr returnValue(
        new  SFString::GetHandle(
             &_sfInputValues,
             this->getType().getFieldDesc(InputValuesFieldId),
             const_cast<DialogWindowBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr DialogWindowBase::editHandleInputValues    (void)
{
    SFString::EditHandlePtr returnValue(
        new  SFString::EditHandle(
             &_sfInputValues,
             this->getType().getFieldDesc(InputValuesFieldId),
             this));


    editSField(InputValuesFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void DialogWindowBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    DialogWindow *pThis = static_cast<DialogWindow *>(this);

    pThis->execSync(static_cast<DialogWindow *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *DialogWindowBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    DialogWindow *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const DialogWindow *>(pRefAspect),
                  dynamic_cast<const DialogWindow *>(this));

    return returnValue;
}
#endif

void DialogWindowBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<DialogWindow *>(this)->setErrorIcon(NULL);

    static_cast<DialogWindow *>(this)->setQuestionIcon(NULL);

    static_cast<DialogWindow *>(this)->setDefaultIcon(NULL);


}


boost::signals2::connection  DialogWindowBase::connectDialogWindowClosing(
                                                    const DialogWindowEventSource::DialogWindowClosingEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    DialogWindowEventSource* evSrc = dynamic_cast<DialogWindowEventSource*>( getEventSource() );
    if ( evSrc )
    {
        return evSrc->connectDialogWindowClosing( listener, at );
    }
    return boost::signals2::connection();
}

boost::signals2::connection  DialogWindowBase::connectDialogWindowClosing(
                                                    const DialogWindowEventSource::DialogWindowClosingEventType::group_type &group,
                                                    const DialogWindowEventSource::DialogWindowClosingEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    DialogWindowEventSource* evSrc = dynamic_cast<DialogWindowEventSource*>( getEventSource() );
    if ( evSrc )
    {
        return evSrc->connectDialogWindowClosing( group, listener, at );
    }
    return boost::signals2::connection();
}

void  DialogWindowBase::disconnectDialogWindowClosing(
                                                    const DialogWindowEventSource::DialogWindowClosingEventType::group_type &group
)
{
    DialogWindowEventSource* evSrc = dynamic_cast<DialogWindowEventSource*>( getEventSource() );
    if ( evSrc )
    {
        evSrc->disconnectDialogWindowClosing( group );
    }
}

void  DialogWindowBase::disconnectAllSlotsDialogWindowClosing(void)
{
    DialogWindowEventSource* evSrc = dynamic_cast<DialogWindowEventSource*>( getEventSource() );
    if ( evSrc )
    {
        evSrc->disconnectAllSlotsDialogWindowClosing();
    }
}

bool  DialogWindowBase::isEmptyDialogWindowClosing(void) const
{
    DialogWindowEventSource* evSrc = dynamic_cast<DialogWindowEventSource*>( getEventSource() );
    if ( evSrc )
    {
        return evSrc->isEmptyDialogWindowClosing();
    }
    return true;
}

UInt32  DialogWindowBase::numSlotsDialogWindowClosing(void) const
{
    DialogWindowEventSource* evSrc = dynamic_cast<DialogWindowEventSource*>( getEventSource() );
    if ( evSrc )
    {
        return evSrc->numSlotsDialogWindowClosing();
    }
    return 0u;
}

boost::signals2::connection  DialogWindowBase::connectDialogWindowClosed(
                                                    const DialogWindowEventSource::DialogWindowClosedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    DialogWindowEventSource* evSrc = dynamic_cast<DialogWindowEventSource*>( getEventSource() );
    if ( evSrc )
    {
        return evSrc->connectDialogWindowClosed( listener, at );
    }
    return boost::signals2::connection();
}

boost::signals2::connection  DialogWindowBase::connectDialogWindowClosed(
                                                    const DialogWindowEventSource::DialogWindowClosedEventType::group_type &group,
                                                    const DialogWindowEventSource::DialogWindowClosedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    DialogWindowEventSource* evSrc = dynamic_cast<DialogWindowEventSource*>( getEventSource() );
    if ( evSrc )
    {
        return evSrc->connectDialogWindowClosed( group, listener, at );
    }
    return boost::signals2::connection();
}

void  DialogWindowBase::disconnectDialogWindowClosed(
                                                    const DialogWindowEventSource::DialogWindowClosedEventType::group_type &group
)
{
    DialogWindowEventSource* evSrc = dynamic_cast<DialogWindowEventSource*>( getEventSource() );
    if ( evSrc )
    {
        evSrc->disconnectDialogWindowClosed( group );
    }
}

void  DialogWindowBase::disconnectAllSlotsDialogWindowClosed(void)
{
    DialogWindowEventSource* evSrc = dynamic_cast<DialogWindowEventSource*>( getEventSource() );
    if ( evSrc )
    {
        evSrc->disconnectAllSlotsDialogWindowClosed();
    }
}

bool  DialogWindowBase::isEmptyDialogWindowClosed(void) const
{
    DialogWindowEventSource* evSrc = dynamic_cast<DialogWindowEventSource*>( getEventSource() );
    if ( evSrc )
    {
        return evSrc->isEmptyDialogWindowClosed();
    }
    return true;
}

UInt32  DialogWindowBase::numSlotsDialogWindowClosed(void) const
{
    DialogWindowEventSource* evSrc = dynamic_cast<DialogWindowEventSource*>( getEventSource() );
    if ( evSrc )
    {
        return evSrc->numSlotsDialogWindowClosed();
    }
    return 0u;
}

OSG_END_NAMESPACE
