/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGLISTMODELFIELDS_H_
#define _OSGLISTMODELFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class ListModel;

OSG_GEN_CONTAINERPTR(ListModel);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<ListModel *, nsOSG> :
    public FieldTraitsFCPtrBase<ListModel *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<ListModel *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<ListModel *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecListModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListModel *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecListModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListModel *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakListModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListModel *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdListModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListModel *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecListModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListModel *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecListModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListModel *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakListModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListModel *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdListModelPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ListModel *,
                      RecordedRefCountPolicy, nsOSG  > SFRecListModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ListModel *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecListModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ListModel *,
                      WeakRefCountPolicy, nsOSG      > SFWeakListModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ListModel *,
                      NoRefCountPolicy, nsOSG        > SFUncountedListModelPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ListModel *,
                      RecordedRefCountPolicy, nsOSG  > MFRecListModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ListModel *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecListModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ListModel *,
                      WeakRefCountPolicy, nsOSG      > MFWeakListModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ListModel *,
                      NoRefCountPolicy, nsOSG        > MFUncountedListModelPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecListModelPtr : 
    public PointerSField<ListModel *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecListModelPtr : 
    public PointerSField<ListModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakListModelPtr :
    public PointerSField<ListModel *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedListModelPtr :
    public PointerSField<ListModel *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecListModelPtr :
    public PointerMField<ListModel *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecListModelPtr :
    public PointerMField<ListModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakListModelPtr :
    public PointerMField<ListModel *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedListModelPtr :
    public PointerMField<ListModel *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGLISTMODELFIELDS_H_ */
