/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGABSTRACTWINDOWEVENTSOURCEFIELDS_H_
#define _OSGABSTRACTWINDOWEVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class AbstractWindowEventSource;

OSG_GEN_CONTAINERPTR(AbstractWindowEventSource);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<AbstractWindowEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<AbstractWindowEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<AbstractWindowEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<AbstractWindowEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecAbstractWindowEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractWindowEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecAbstractWindowEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractWindowEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakAbstractWindowEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractWindowEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdAbstractWindowEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractWindowEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecAbstractWindowEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractWindowEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecAbstractWindowEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractWindowEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakAbstractWindowEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractWindowEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdAbstractWindowEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<AbstractWindowEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecAbstractWindowEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<AbstractWindowEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecAbstractWindowEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<AbstractWindowEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakAbstractWindowEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<AbstractWindowEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedAbstractWindowEventSourcePtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<AbstractWindowEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecAbstractWindowEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<AbstractWindowEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecAbstractWindowEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<AbstractWindowEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakAbstractWindowEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<AbstractWindowEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedAbstractWindowEventSourcePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecAbstractWindowEventSourcePtr : 
    public PointerSField<AbstractWindowEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecAbstractWindowEventSourcePtr : 
    public PointerSField<AbstractWindowEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakAbstractWindowEventSourcePtr :
    public PointerSField<AbstractWindowEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedAbstractWindowEventSourcePtr :
    public PointerSField<AbstractWindowEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecAbstractWindowEventSourcePtr :
    public PointerMField<AbstractWindowEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecAbstractWindowEventSourcePtr :
    public PointerMField<AbstractWindowEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakAbstractWindowEventSourcePtr :
    public PointerMField<AbstractWindowEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedAbstractWindowEventSourcePtr :
    public PointerMField<AbstractWindowEventSource *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGABSTRACTWINDOWEventSourceFIELDS_H_ */
