/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGABSTRACTWINDOWFIELDS_H_
#define _OSGABSTRACTWINDOWFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class AbstractWindow;

OSG_GEN_CONTAINERPTR(AbstractWindow);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<AbstractWindow *, nsOSG> :
    public FieldTraitsFCPtrBase<AbstractWindow *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<AbstractWindow *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<AbstractWindow *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecAbstractWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractWindow *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecAbstractWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractWindow *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakAbstractWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractWindow *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdAbstractWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractWindow *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecAbstractWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractWindow *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecAbstractWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractWindow *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakAbstractWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractWindow *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdAbstractWindowPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<AbstractWindow *,
                      RecordedRefCountPolicy, nsOSG  > SFRecAbstractWindowPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<AbstractWindow *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecAbstractWindowPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<AbstractWindow *,
                      WeakRefCountPolicy, nsOSG      > SFWeakAbstractWindowPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<AbstractWindow *,
                      NoRefCountPolicy, nsOSG        > SFUncountedAbstractWindowPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<AbstractWindow *,
                      RecordedRefCountPolicy, nsOSG  > MFRecAbstractWindowPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<AbstractWindow *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecAbstractWindowPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<AbstractWindow *,
                      WeakRefCountPolicy, nsOSG      > MFWeakAbstractWindowPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<AbstractWindow *,
                      NoRefCountPolicy, nsOSG        > MFUncountedAbstractWindowPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecAbstractWindowPtr : 
    public PointerSField<AbstractWindow *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecAbstractWindowPtr : 
    public PointerSField<AbstractWindow *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakAbstractWindowPtr :
    public PointerSField<AbstractWindow *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedAbstractWindowPtr :
    public PointerSField<AbstractWindow *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecAbstractWindowPtr :
    public PointerMField<AbstractWindow *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecAbstractWindowPtr :
    public PointerMField<AbstractWindow *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakAbstractWindowPtr :
    public PointerMField<AbstractWindow *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedAbstractWindowPtr :
    public PointerMField<AbstractWindow *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGABSTRACTWINDOWFIELDS_H_ */
