/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBUTTONEVENTSOURCEFIELDS_H_
#define _OSGBUTTONEVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class ButtonEventSource;

OSG_GEN_CONTAINERPTR(ButtonEventSource);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<ButtonEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<ButtonEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<ButtonEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<ButtonEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ButtonEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ButtonEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ButtonEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ButtonEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ButtonEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ButtonEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ButtonEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdButtonEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ButtonEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ButtonEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ButtonEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ButtonEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedButtonEventSourcePtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ButtonEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ButtonEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ButtonEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ButtonEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedButtonEventSourcePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecButtonEventSourcePtr : 
    public PointerSField<ButtonEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecButtonEventSourcePtr : 
    public PointerSField<ButtonEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakButtonEventSourcePtr :
    public PointerSField<ButtonEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedButtonEventSourcePtr :
    public PointerSField<ButtonEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecButtonEventSourcePtr :
    public PointerMField<ButtonEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecButtonEventSourcePtr :
    public PointerMField<ButtonEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakButtonEventSourcePtr :
    public PointerMField<ButtonEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedButtonEventSourcePtr :
    public PointerMField<ButtonEventSource *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBUTTONEventSourceFIELDS_H_ */
