/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ButtonEventSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"




#include "OSGButtonEventSourceBase.h"
#include "OSGButtonEventSource.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::ButtonEventSource
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<ButtonEventSource *, nsOSG>::_type(
    "ButtonEventSourcePtr", 
    "ComponentEventSourcePtr", 
    ButtonEventSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(ButtonEventSource *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           ButtonEventSource *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           ButtonEventSource *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void ButtonEventSourceBase::classDescInserter(TypeObject &oType)
{
}


ButtonEventSourceBase::TypeObject ButtonEventSourceBase::_type(
    ButtonEventSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&ButtonEventSourceBase::createEmptyLocal),
    ButtonEventSource::initMethod,
    ButtonEventSource::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&ButtonEventSource::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"ButtonEventSource\"\n"
    "    parent=\"ComponentEventSource\"\n"
    "    library=\"ContribToolboxUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    ">\n"
    "<!--     parentProducer=\"Component\" -->\n"
    "<!--\n"
    "    <ProducedEvent\n"
    "        name=\"ActionPerformed\"\n"
    "        detailsType=\"ActionEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"MousePressedActionPerformed\"\n"
    "        detailsType=\"ActionEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "-->\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &ButtonEventSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &ButtonEventSourceBase::getType(void) const
{
    return _type;
}

UInt32 ButtonEventSourceBase::getContainerSize(void) const
{
    return sizeof(ButtonEventSource);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

SizeT ButtonEventSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void ButtonEventSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void ButtonEventSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
ButtonEventSourceTransitPtr ButtonEventSourceBase::createLocal(BitVector bFlags)
{
    ButtonEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<ButtonEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
ButtonEventSourceTransitPtr ButtonEventSourceBase::createDependent(BitVector bFlags)
{
    ButtonEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<ButtonEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
ButtonEventSourceTransitPtr ButtonEventSourceBase::create(void)
{
    ButtonEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<ButtonEventSource>(tmpPtr);
    }

    return fc;
}

ButtonEventSource *ButtonEventSourceBase::createEmptyLocal(BitVector bFlags)
{
    ButtonEventSource *returnValue;

    newPtr<ButtonEventSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
ButtonEventSource *ButtonEventSourceBase::createEmpty(void)
{
    ButtonEventSource *returnValue;

    newPtr<ButtonEventSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr ButtonEventSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    ButtonEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ButtonEventSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr ButtonEventSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    ButtonEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ButtonEventSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr ButtonEventSourceBase::shallowCopy(void) const
{
    ButtonEventSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const ButtonEventSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

ButtonEventSourceBase::ButtonEventSourceBase(void) :
    Inherited()
{
}

ButtonEventSourceBase::ButtonEventSourceBase(const ButtonEventSourceBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

ButtonEventSourceBase::~ButtonEventSourceBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void ButtonEventSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    ButtonEventSource *pThis = static_cast<ButtonEventSource *>(this);

    pThis->execSync(static_cast<ButtonEventSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *ButtonEventSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    ButtonEventSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const ButtonEventSource *>(pRefAspect),
                  dynamic_cast<const ButtonEventSource *>(this));

    return returnValue;
}
#endif

void ButtonEventSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
