/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBUTTONFIELDS_H_
#define _OSGBUTTONFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class Button;

OSG_GEN_CONTAINERPTR(Button);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<Button *, nsOSG> :
    public FieldTraitsFCPtrBase<Button *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<Button *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<Button *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecButtonPtr"; 
}

template<> inline
const Char8 *FieldTraits<Button *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecButtonPtr"; 
}

template<> inline
const Char8 *FieldTraits<Button *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakButtonPtr"; 
}

template<> inline
const Char8 *FieldTraits<Button *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdButtonPtr"; 
}

template<> inline
const Char8 *FieldTraits<Button *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecButtonPtr"; 
}

template<> inline
const Char8 *FieldTraits<Button *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecButtonPtr"; 
}

template<> inline
const Char8 *FieldTraits<Button *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakButtonPtr"; 
}

template<> inline
const Char8 *FieldTraits<Button *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdButtonPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<Button *,
                      RecordedRefCountPolicy, nsOSG  > SFRecButtonPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<Button *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecButtonPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<Button *,
                      WeakRefCountPolicy, nsOSG      > SFWeakButtonPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<Button *,
                      NoRefCountPolicy, nsOSG        > SFUncountedButtonPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<Button *,
                      RecordedRefCountPolicy, nsOSG  > MFRecButtonPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<Button *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecButtonPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<Button *,
                      WeakRefCountPolicy, nsOSG      > MFWeakButtonPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<Button *,
                      NoRefCountPolicy, nsOSG        > MFUncountedButtonPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecButtonPtr : 
    public PointerSField<Button *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecButtonPtr : 
    public PointerSField<Button *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakButtonPtr :
    public PointerSField<Button *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedButtonPtr :
    public PointerSField<Button *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecButtonPtr :
    public PointerMField<Button *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecButtonPtr :
    public PointerMField<Button *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakButtonPtr :
    public PointerMField<Button *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedButtonPtr :
    public PointerMField<Button *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBUTTONFIELDS_H_ */
