/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class MenuButtonEventSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"




#include "OSGMenuButtonEventSourceBase.h"
#include "OSGMenuButtonEventSource.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::MenuButtonEventSource
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<MenuButtonEventSource *, nsOSG>::_type(
    "MenuButtonEventSourcePtr", 
    "ToggleButtonEventSourcePtr", 
    MenuButtonEventSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(MenuButtonEventSource *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           MenuButtonEventSource *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           MenuButtonEventSource *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void MenuButtonEventSourceBase::classDescInserter(TypeObject &oType)
{
}


MenuButtonEventSourceBase::TypeObject MenuButtonEventSourceBase::_type(
    MenuButtonEventSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&MenuButtonEventSourceBase::createEmptyLocal),
    MenuButtonEventSource::initMethod,
    MenuButtonEventSource::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&MenuButtonEventSource::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"MenuButtonEventSource\"\n"
    "    parent=\"ToggleButtonEventSource\"\n"
    "    library=\"ContribToolboxUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    ">\n"
    "<!--\n"
    "    <ProducedEvent\n"
    "        name=\"MenuActionPerformed\"\n"
    "        detailsType=\"ActionEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "-->\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &MenuButtonEventSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &MenuButtonEventSourceBase::getType(void) const
{
    return _type;
}

UInt32 MenuButtonEventSourceBase::getContainerSize(void) const
{
    return sizeof(MenuButtonEventSource);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

SizeT MenuButtonEventSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void MenuButtonEventSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void MenuButtonEventSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
MenuButtonEventSourceTransitPtr MenuButtonEventSourceBase::createLocal(BitVector bFlags)
{
    MenuButtonEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<MenuButtonEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
MenuButtonEventSourceTransitPtr MenuButtonEventSourceBase::createDependent(BitVector bFlags)
{
    MenuButtonEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<MenuButtonEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
MenuButtonEventSourceTransitPtr MenuButtonEventSourceBase::create(void)
{
    MenuButtonEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<MenuButtonEventSource>(tmpPtr);
    }

    return fc;
}

MenuButtonEventSource *MenuButtonEventSourceBase::createEmptyLocal(BitVector bFlags)
{
    MenuButtonEventSource *returnValue;

    newPtr<MenuButtonEventSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
MenuButtonEventSource *MenuButtonEventSourceBase::createEmpty(void)
{
    MenuButtonEventSource *returnValue;

    newPtr<MenuButtonEventSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr MenuButtonEventSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    MenuButtonEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const MenuButtonEventSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr MenuButtonEventSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    MenuButtonEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const MenuButtonEventSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr MenuButtonEventSourceBase::shallowCopy(void) const
{
    MenuButtonEventSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const MenuButtonEventSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

MenuButtonEventSourceBase::MenuButtonEventSourceBase(void) :
    Inherited()
{
}

MenuButtonEventSourceBase::MenuButtonEventSourceBase(const MenuButtonEventSourceBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

MenuButtonEventSourceBase::~MenuButtonEventSourceBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void MenuButtonEventSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    MenuButtonEventSource *pThis = static_cast<MenuButtonEventSource *>(this);

    pThis->execSync(static_cast<MenuButtonEventSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *MenuButtonEventSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    MenuButtonEventSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const MenuButtonEventSource *>(pRefAspect),
                  dynamic_cast<const MenuButtonEventSource *>(this));

    return returnValue;
}
#endif

void MenuButtonEventSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
