/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGMENUBUTTONEVENTSOURCEFIELDS_H_
#define _OSGMENUBUTTONEVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class MenuButtonEventSource;

OSG_GEN_CONTAINERPTR(MenuButtonEventSource);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<MenuButtonEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<MenuButtonEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<MenuButtonEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<MenuButtonEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecMenuButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<MenuButtonEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecMenuButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<MenuButtonEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakMenuButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<MenuButtonEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdMenuButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<MenuButtonEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecMenuButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<MenuButtonEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecMenuButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<MenuButtonEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakMenuButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<MenuButtonEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdMenuButtonEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<MenuButtonEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecMenuButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<MenuButtonEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecMenuButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<MenuButtonEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakMenuButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<MenuButtonEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedMenuButtonEventSourcePtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<MenuButtonEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecMenuButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<MenuButtonEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecMenuButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<MenuButtonEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakMenuButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<MenuButtonEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedMenuButtonEventSourcePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecMenuButtonEventSourcePtr : 
    public PointerSField<MenuButtonEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecMenuButtonEventSourcePtr : 
    public PointerSField<MenuButtonEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakMenuButtonEventSourcePtr :
    public PointerSField<MenuButtonEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedMenuButtonEventSourcePtr :
    public PointerSField<MenuButtonEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecMenuButtonEventSourcePtr :
    public PointerMField<MenuButtonEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecMenuButtonEventSourcePtr :
    public PointerMField<MenuButtonEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakMenuButtonEventSourcePtr :
    public PointerMField<MenuButtonEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedMenuButtonEventSourcePtr :
    public PointerMField<MenuButtonEventSource *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGMENUBUTTONEVENTSOURCEFIELDS_H_ */
