/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGMENUBUTTONFIELDS_H_
#define _OSGMENUBUTTONFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class MenuButton;

OSG_GEN_CONTAINERPTR(MenuButton);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<MenuButton *, nsOSG> :
    public FieldTraitsFCPtrBase<MenuButton *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<MenuButton *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<MenuButton *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecMenuButtonPtr"; 
}

template<> inline
const Char8 *FieldTraits<MenuButton *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecMenuButtonPtr"; 
}

template<> inline
const Char8 *FieldTraits<MenuButton *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakMenuButtonPtr"; 
}

template<> inline
const Char8 *FieldTraits<MenuButton *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdMenuButtonPtr"; 
}

template<> inline
const Char8 *FieldTraits<MenuButton *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecMenuButtonPtr"; 
}

template<> inline
const Char8 *FieldTraits<MenuButton *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecMenuButtonPtr"; 
}

template<> inline
const Char8 *FieldTraits<MenuButton *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakMenuButtonPtr"; 
}

template<> inline
const Char8 *FieldTraits<MenuButton *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdMenuButtonPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<MenuButton *,
                      RecordedRefCountPolicy, nsOSG  > SFRecMenuButtonPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<MenuButton *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecMenuButtonPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<MenuButton *,
                      WeakRefCountPolicy, nsOSG      > SFWeakMenuButtonPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<MenuButton *,
                      NoRefCountPolicy, nsOSG        > SFUncountedMenuButtonPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<MenuButton *,
                      RecordedRefCountPolicy, nsOSG  > MFRecMenuButtonPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<MenuButton *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecMenuButtonPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<MenuButton *,
                      WeakRefCountPolicy, nsOSG      > MFWeakMenuButtonPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<MenuButton *,
                      NoRefCountPolicy, nsOSG        > MFUncountedMenuButtonPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecMenuButtonPtr : 
    public PointerSField<MenuButton *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecMenuButtonPtr : 
    public PointerSField<MenuButton *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakMenuButtonPtr :
    public PointerSField<MenuButton *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedMenuButtonPtr :
    public PointerSField<MenuButton *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecMenuButtonPtr :
    public PointerMField<MenuButton *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecMenuButtonPtr :
    public PointerMField<MenuButton *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakMenuButtonPtr :
    public PointerMField<MenuButton *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedMenuButtonPtr :
    public PointerMField<MenuButton *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGMENUBUTTONFIELDS_H_ */
