/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTOGGLEBUTTONEVENTSOURCEFIELDS_H_
#define _OSGTOGGLEBUTTONEVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class ToggleButtonEventSource;

OSG_GEN_CONTAINERPTR(ToggleButtonEventSource);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<ToggleButtonEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<ToggleButtonEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<ToggleButtonEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<ToggleButtonEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecToggleButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ToggleButtonEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecToggleButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ToggleButtonEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakToggleButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ToggleButtonEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdToggleButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ToggleButtonEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecToggleButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ToggleButtonEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecToggleButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ToggleButtonEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakToggleButtonEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ToggleButtonEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdToggleButtonEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ToggleButtonEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecToggleButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ToggleButtonEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecToggleButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ToggleButtonEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakToggleButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ToggleButtonEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedToggleButtonEventSourcePtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ToggleButtonEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecToggleButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ToggleButtonEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecToggleButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ToggleButtonEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakToggleButtonEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ToggleButtonEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedToggleButtonEventSourcePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecToggleButtonEventSourcePtr : 
    public PointerSField<ToggleButtonEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecToggleButtonEventSourcePtr : 
    public PointerSField<ToggleButtonEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakToggleButtonEventSourcePtr :
    public PointerSField<ToggleButtonEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedToggleButtonEventSourcePtr :
    public PointerSField<ToggleButtonEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecToggleButtonEventSourcePtr :
    public PointerMField<ToggleButtonEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecToggleButtonEventSourcePtr :
    public PointerMField<ToggleButtonEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakToggleButtonEventSourcePtr :
    public PointerMField<ToggleButtonEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedToggleButtonEventSourcePtr :
    public PointerMField<ToggleButtonEventSource *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTOGGLEBUTTONEventSourceFIELDS_H_ */
