/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ToggleButton!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"




#include "OSGToggleButtonBase.h"
#include "OSGToggleButton.h"
#include "OSGToggleButtonEventSource.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::ToggleButton
    A UI Toggle Button.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<ToggleButton *, nsOSG>::_type(
    "ToggleButtonPtr", 
    "ButtonPtr", 
    ToggleButton::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(ToggleButton *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           ToggleButton *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           ToggleButton *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void ToggleButtonBase::classDescInserter(TypeObject &oType)
{
}


ToggleButtonBase::TypeObject ToggleButtonBase::_type(
    ToggleButtonBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&ToggleButtonBase::createEmptyLocal),
    ToggleButton::initMethod,
    ToggleButton::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&ToggleButton::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"ToggleButton\"\n"
    "    parent=\"Button\"\n"
    "    library=\"ContribToolboxUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)\"\n"
    "    parentProducer=\"Button\"\n"
    ">\n"
    "A UI Toggle Button.\n"
    "    <ProducedEvent\n"
    "        name=\"ButtonSelected\"\n"
    "        detailsType=\"ButtonSelectedEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"ButtonDeselected\"\n"
    "        detailsType=\"ButtonSelectedEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "</FieldContainer>\n",
    "A UI Toggle Button.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &ToggleButtonBase::getType(void)
{
    return _type;
}

const FieldContainerType &ToggleButtonBase::getType(void) const
{
    return _type;
}

UInt32 ToggleButtonBase::getContainerSize(void) const
{
    return sizeof(ToggleButton);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

SizeT ToggleButtonBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void ToggleButtonBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void ToggleButtonBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
ToggleButtonTransitPtr ToggleButtonBase::createLocal(BitVector bFlags)
{
    ToggleButtonTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<ToggleButton>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
ToggleButtonTransitPtr ToggleButtonBase::createDependent(BitVector bFlags)
{
    ToggleButtonTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<ToggleButton>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
ToggleButtonTransitPtr ToggleButtonBase::create(void)
{
    ToggleButtonTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<ToggleButton>(tmpPtr);
    }

    return fc;
}

ToggleButton *ToggleButtonBase::createEmptyLocal(BitVector bFlags)
{
    ToggleButton *returnValue;

    newPtr<ToggleButton>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
ToggleButton *ToggleButtonBase::createEmpty(void)
{
    ToggleButton *returnValue;

    newPtr<ToggleButton>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr ToggleButtonBase::shallowCopyLocal(
    BitVector bFlags) const
{
    ToggleButton *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ToggleButton *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr ToggleButtonBase::shallowCopyDependent(
    BitVector bFlags) const
{
    ToggleButton *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ToggleButton *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr ToggleButtonBase::shallowCopy(void) const
{
    ToggleButton *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const ToggleButton *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

ToggleButtonBase::ToggleButtonBase(void) :
    Inherited()
{
}

ToggleButtonBase::ToggleButtonBase(const ToggleButtonBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

ToggleButtonBase::~ToggleButtonBase(void)
{
}

void ToggleButtonBase::onCreate(const ToggleButton *source)
{
    Inherited::onCreate(source);

    
    {
        ToggleButtonEventSourceUnrecPtr evSrc = ToggleButtonEventSource::create();
        setEventSource( evSrc );
    }
}


#ifdef OSG_MT_CPTR_ASPECT
void ToggleButtonBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    ToggleButton *pThis = static_cast<ToggleButton *>(this);

    pThis->execSync(static_cast<ToggleButton *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *ToggleButtonBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    ToggleButton *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const ToggleButton *>(pRefAspect),
                  dynamic_cast<const ToggleButton *>(this));

    return returnValue;
}
#endif

void ToggleButtonBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
