/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCOMBOBOXEVENTSOURCEFIELDS_H_
#define _OSGCOMBOBOXEVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class ComboBoxEventSource;

OSG_GEN_CONTAINERPTR(ComboBoxEventSource);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<ComboBoxEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<ComboBoxEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<ComboBoxEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<ComboBoxEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecComboBoxEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ComboBoxEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecComboBoxEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ComboBoxEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakComboBoxEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ComboBoxEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdComboBoxEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ComboBoxEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecComboBoxEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ComboBoxEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecComboBoxEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ComboBoxEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakComboBoxEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ComboBoxEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdComboBoxEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComboBoxEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecComboBoxEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComboBoxEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecComboBoxEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComboBoxEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakComboBoxEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComboBoxEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedComboBoxEventSourcePtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComboBoxEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecComboBoxEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComboBoxEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecComboBoxEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComboBoxEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakComboBoxEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComboBoxEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedComboBoxEventSourcePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecComboBoxEventSourcePtr : 
    public PointerSField<ComboBoxEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecComboBoxEventSourcePtr : 
    public PointerSField<ComboBoxEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakComboBoxEventSourcePtr :
    public PointerSField<ComboBoxEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedComboBoxEventSourcePtr :
    public PointerSField<ComboBoxEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecComboBoxEventSourcePtr :
    public PointerMField<ComboBoxEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecComboBoxEventSourcePtr :
    public PointerMField<ComboBoxEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakComboBoxEventSourcePtr :
    public PointerMField<ComboBoxEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedComboBoxEventSourcePtr :
    public PointerMField<ComboBoxEventSource *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGCOMBOBOXEventSourceFIELDS_H_ */
