/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ComboBoxEventSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"


#include "OSGComboBoxEventSourceBase.h"
#include "OSGComboBoxEventSource.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::ComboBoxEventSource
    A UI ComboBox
 */



/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<ComboBoxEventSource *, nsOSG>::_type(
    "ComboBoxEventSourcePtr",
    "ComponentEventSourcePtr",
    ComboBoxEventSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(ComboBoxEventSource *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           ComboBoxEventSource *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           ComboBoxEventSource *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void ComboBoxEventSourceBase::classDescInserter(TypeObject &oType)
{
}


ComboBoxEventSourceBase::TypeObject ComboBoxEventSourceBase::_type(
    ComboBoxEventSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&ComboBoxEventSourceBase::createEmptyLocal),
    ComboBoxEventSource::initMethod,
    ComboBoxEventSource::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&ComboBoxEventSource::classDescInserter),
    false,
    0,
    "",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &ComboBoxEventSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &ComboBoxEventSourceBase::getType(void) const
{
    return _type;
}

UInt32 ComboBoxEventSourceBase::getContainerSize(void) const
{
    return sizeof(ComboBoxEventSource);
}



/*------------------------------ access -----------------------------------*/

SizeT ComboBoxEventSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    return returnValue;
}

void ComboBoxEventSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);
}

void ComboBoxEventSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);
}

//! create a new instance of the class
ComboBoxEventSourceTransitPtr ComboBoxEventSourceBase::createLocal(BitVector bFlags)
{
    ComboBoxEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<ComboBoxEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
ComboBoxEventSourceTransitPtr ComboBoxEventSourceBase::createDependent(BitVector bFlags)
{
    ComboBoxEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<ComboBoxEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
ComboBoxEventSourceTransitPtr ComboBoxEventSourceBase::create(void)
{
    ComboBoxEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<ComboBoxEventSource>(tmpPtr);
    }

    return fc;
}

ComboBoxEventSource *ComboBoxEventSourceBase::createEmptyLocal(BitVector bFlags)
{
    ComboBoxEventSource *returnValue;

    newPtr<ComboBoxEventSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
ComboBoxEventSource *ComboBoxEventSourceBase::createEmpty(void)
{
    ComboBoxEventSource *returnValue;

    newPtr<ComboBoxEventSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr ComboBoxEventSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    ComboBoxEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ComboBoxEventSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr ComboBoxEventSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    ComboBoxEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ComboBoxEventSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr ComboBoxEventSourceBase::shallowCopy(void) const
{
    ComboBoxEventSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const ComboBoxEventSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

ComboBoxEventSourceBase::ComboBoxEventSourceBase(void) :
    Inherited()
{
}

ComboBoxEventSourceBase::ComboBoxEventSourceBase(const ComboBoxEventSourceBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

ComboBoxEventSourceBase::~ComboBoxEventSourceBase(void)
{
}


#ifdef OSG_MT_CPTR_ASPECT
void ComboBoxEventSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    ComboBoxEventSource *pThis = static_cast<ComboBoxEventSource *>(this);

    pThis->execSync(static_cast<ComboBoxEventSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *ComboBoxEventSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    ComboBoxEventSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const ComboBoxEventSource *>(pRefAspect),
                  dynamic_cast<const ComboBoxEventSource *>(this));

    return returnValue;
}
#endif

void ComboBoxEventSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();

}

OSG_END_NAMESPACE
