/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ComponentEventSourceDecorator!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"




#include "OSGComponentEventSourceDecoratorBase.h"
#include "OSGComponentEventSourceDecorator.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::ComponentEventSourceDecorator
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var ComponentEventSourcePtr ComponentEventSourceDecoratorBase::_sfDecoratee
    The object being decorated
*/

/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<ComponentEventSourceDecorator *, nsOSG>::_type(
    "ComponentEventSourceDecoratorPtr", 
    "ComponentEventSourcePtr", 
    ComponentEventSourceDecorator::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(ComponentEventSourceDecorator *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           ComponentEventSourceDecorator *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           ComponentEventSourceDecorator *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void ComponentEventSourceDecoratorBase::classDescInserter(TypeObject &oType)
{
    pDesc = new SFUnrecComponentEventSourcePtr::Description(
        SFUnrecComponentEventSourcePtr::getClassType(),
        "decoratee",
        "undocumented decoratee",
        DecorateeFieldId, DecorateeFieldMask,
        false,
        Field::SFDefaultFlags,
        static_cast<FieldEditMethodSig>(&ComponentEventSourceDecorator::editHandleDecoratee),
        static_cast<FieldGetMethodSig >(&ComponentEventSourceDecorator::getHandleDecoratee ));

    oType.addInitialDesc(pDesc);
}


ComponentEventSourceDecoratorBase::TypeObject ComponentEventSourceDecoratorBase::_type(
    ComponentEventSourceDecoratorBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&ComponentEventSourceDecoratorBase::createEmptyLocal),
    ComponentEventSourceDecorator::initMethod,
    ComponentEventSourceDecorator::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&ComponentEventSourceDecorator::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"ComponentEventSource\"\n"
    "    parent=\"EventContainer\"\n"
    "    library=\"ContribToolboxUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"true\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    >\n"
    "<!--\n"
    "    <ProducedEvent\n"
    "        name=\"MouseMoved\"\n"
    "        detailsType=\"MouseEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when the mouse is hovering over this Component and moves.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"MouseDragged\"\n"
    "        detailsType=\"MouseEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when the mouse is hovering over this Component and moves \n"
    "        when a mouse button is down.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"MouseClicked\"\n"
    "        detailsType=\"MouseEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when the mouse is hovering over this Component and a \n"
    "        mouse button is clicked.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"MouseEntered\"\n"
    "        detailsType=\"MouseEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when the mouse enters this Component.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"MouseExited\"\n"
    "        detailsType=\"MouseEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when the mouse exits this Component.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"MousePressed\"\n"
    "        detailsType=\"MouseEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when the mouse is hovering over this Component and a \n"
    "        mouse button is pressed.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"MouseReleased\"\n"
    "        detailsType=\"MouseEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when the mouse is hovering over this Component and a \n"
    "        mouse button is released.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"MouseWheelMoved\"\n"
    "        detailsType=\"MouseWheelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when the mouse is hovering over this Component and the\n"
    "        mouse wheel is moved.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"KeyPressed\"\n"
    "        detailsType=\"KeyEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when this Component has focused and a keyboard key is \n"
    "        pressed.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"KeyReleased\"\n"
    "        detailsType=\"KeyEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when this Component has focused and a keyboard key is \n"
    "        released.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"KeyTyped\"\n"
    "        detailsType=\"KeyEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when this Component has focused and a keyboard key is \n"
    "        typed.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"FocusGained\"\n"
    "        detailsType=\"FocusEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when this Component gains focus.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"FocusLost\"\n"
    "        detailsType=\"FocusEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when this Component loses focus.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"ComponentHidden\"\n"
    "        detailsType=\"ComponentEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when this Component's Visible field is set to false.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"ComponentVisible\"\n"
    "        detailsType=\"ComponentEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when this Component's Visible field is set to true.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"ComponentMoved\"\n"
    "        detailsType=\"ComponentEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when this Component's Position field changes.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"ComponentResized\"\n"
    "        detailsType=\"ComponentEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when this Component's Size field changes.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"ComponentEnabled\"\n"
    "        detailsType=\"ComponentEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when this Component's Enabled field is set to true.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"ComponentDisabled\"\n"
    "        detailsType=\"ComponentEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when this Component's Enabled field is set to false.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"ToolTipActivated\"\n"
    "        detailsType=\"ComponentEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when the ToolTip for this Component is activated.\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"ToolTipDeactivated\"\n"
    "        detailsType=\"ComponentEventDetails\"\n"
    "        consumable=\"true\"\n"
    "        >\n"
    "        Event produced when the ToolTip for this Component is deactivated.\n"
    "    </ProducedEvent>\n"
    "-->\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &ComponentEventSourceDecoratorBase::getType(void)
{
    return _type;
}

const FieldContainerType &ComponentEventSourceDecoratorBase::getType(void) const
{
    return _type;
}

UInt32 ComponentEventSourceDecoratorBase::getContainerSize(void) const
{
    return sizeof(ComponentEventSourceDecorator);
}

/*------------------------- decorator get ------------------------------*/

const SFUnrecComponentEventSourcePtr *ComponentEventSourceDecoratorBase::getSFDecoratee(void) const
{
    return &_sfDecoratee;
}






/*------------------------------ access -----------------------------------*/

SizeT ComponentEventSourceDecoratorBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (DecorateeFieldMask & whichField))
    {
        returnValue += _sfDecoratee.getBinSize();
    }

    return returnValue;
}

void ComponentEventSourceDecoratorBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (DecorateeFieldMask & whichField))
    {
        _sfDecoratee.copyToBin(pMem);
    }
}

void ComponentEventSourceDecoratorBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (DecorateeFieldMask & whichField))
    {
        editSField(DecorateeFieldMask);
        _sfDecoratee.copyFromBin(pMem);
    }
}

//! create a new instance of the class
ComponentEventSourceDecoratorTransitPtr ComponentEventSourceDecoratorBase::createLocal(BitVector bFlags)
{
    ComponentEventSourceDecoratorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<ComponentEventSourceDecorator>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
ComponentEventSourceDecoratorTransitPtr ComponentEventSourceDecoratorBase::createDependent(BitVector bFlags)
{
    ComponentEventSourceDecoratorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<ComponentEventSourceDecorator>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
ComponentEventSourceDecoratorTransitPtr ComponentEventSourceDecoratorBase::create(void)
{
    ComponentEventSourceDecoratorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<ComponentEventSourceDecorator>(tmpPtr);
    }

    return fc;
}

ComponentEventSourceDecorator *ComponentEventSourceDecoratorBase::createEmptyLocal(BitVector bFlags)
{
    ComponentEventSourceDecorator *returnValue;

    newPtr<ComponentEventSourceDecorator>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
ComponentEventSourceDecorator *ComponentEventSourceDecoratorBase::createEmpty(void)
{
    ComponentEventSourceDecorator *returnValue;

    newPtr<ComponentEventSourceDecorator>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr ComponentEventSourceDecoratorBase::shallowCopyLocal(
    BitVector bFlags) const
{
    ComponentEventSourceDecorator *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ComponentEventSourceDecorator *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr ComponentEventSourceDecoratorBase::shallowCopyDependent(
    BitVector bFlags) const
{
    ComponentEventSourceDecorator *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ComponentEventSourceDecorator *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr ComponentEventSourceDecoratorBase::shallowCopy(void) const
{
    ComponentEventSourceDecorator *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const ComponentEventSourceDecorator *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

ComponentEventSourceDecoratorBase::ComponentEventSourceDecoratorBase(void) :
    Inherited()
{
}

ComponentEventSourceDecoratorBase::ComponentEventSourceDecoratorBase(const ComponentEventSourceDecoratorBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

ComponentEventSourceDecoratorBase::~ComponentEventSourceDecoratorBase(void)
{
}


GetFieldHandlePtr  ComponentEventSourceDecoratorBase::getHandleDecoratee (void) const
{
    SFUnrecComponentEventSourcePtr::GetHandlePtr returnValue(
        new SFUnrecComponentEventSourcePtr::GetHandle(
            &_sfDecoratee,
            this->getType().getFieldDesc(DecorateeFieldId),
            const_cast<ComponentEventSourceDecoratorBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr ComponentEventSourceDecoratorBase::editHandleDecoratee(void)
{
    SFUnrecComponentEventSourcePtr::EditHandlePtr returnValue(
        new SFUnrecComponentEventSourcePtr::EditHandle(
            &_sfDecoratee,
            this->getType().getFieldDesc(DecorateeFieldId),
            this));

    returnValue->setSetMethod(boost::bind(&ComponentEventSourceDecorator::setDecoratee,
                              static_cast<ComponentEventSourceDecorator *>(this), _1));

    editSField(DecorateeFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void ComponentEventSourceDecoratorBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    ComponentEventSourceDecorator *pThis = static_cast<ComponentEventSourceDecorator *>(this);

    pThis->execSync(static_cast<ComponentEventSourceDecorator *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *ComponentEventSourceDecoratorBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    ComponentEventSourceDecorator *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const ComponentEventSourceDecorator *>(pRefAspect),
                  dynamic_cast<const ComponentEventSourceDecorator *>(this));

    return returnValue;
}
#endif

void ComponentEventSourceDecoratorBase::resolveLinks(void)
{
    static_cast<ComponentEventSourceDecorator *>(this)->setDecoratee(NULL);    

    Inherited::resolveLinks();


}

/*------------------------------ get -----------------------------------*/



OSG_END_NAMESPACE
