/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCOMPONENTEVENTSOURCEFIELDS_H_
#define _OSGCOMPONENTEVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class ComponentEventSource;

OSG_GEN_CONTAINERPTR(ComponentEventSource);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<ComponentEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<ComponentEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<ComponentEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<ComponentEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecComponentEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecComponentEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakComponentEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdComponentEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecComponentEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecComponentEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakComponentEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdComponentEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComponentEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecComponentEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComponentEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecComponentEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComponentEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakComponentEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComponentEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedComponentEventSourcePtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComponentEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecComponentEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComponentEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecComponentEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComponentEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakComponentEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComponentEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedComponentEventSourcePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecComponentEventSourcePtr : 
    public PointerSField<ComponentEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecComponentEventSourcePtr : 
    public PointerSField<ComponentEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakComponentEventSourcePtr :
    public PointerSField<ComponentEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedComponentEventSourcePtr :
    public PointerSField<ComponentEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecComponentEventSourcePtr :
    public PointerMField<ComponentEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecComponentEventSourcePtr :
    public PointerMField<ComponentEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakComponentEventSourcePtr :
    public PointerMField<ComponentEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedComponentEventSourcePtr :
    public PointerMField<ComponentEventSource *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGCOMPONENTEVENTSOURCEFIELDS_H_ */
