/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCOMPONENTEVENTSOURCEDECORATORFIELDS_H_
#define _OSGCOMPONENTEVENTSOURCEDECORATORFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class ComponentEventSourceDecorator;

OSG_GEN_CONTAINERPTR(ComponentEventSourceDecorator);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<ComponentEventSourceDecorator *, nsOSG> :
    public FieldTraitsFCPtrBase<ComponentEventSourceDecorator *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<ComponentEventSourceDecorator *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<ComponentEventSourceDecorator *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecComponentEventSourceDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentEventSourceDecorator *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecComponentEventSourceDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentEventSourceDecorator *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakComponentEventSourceDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentEventSourceDecorator *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdComponentEventSourceDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentEventSourceDecorator *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecComponentEventSourceDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentEventSourceDecorator *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecComponentEventSourceDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentEventSourceDecorator *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakComponentEventSourceDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentEventSourceDecorator *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdComponentEventSourceDecoratorPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComponentEventSourceDecorator *,
                      RecordedRefCountPolicy, nsOSG  > SFRecComponentEventSourceDecoratorPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComponentEventSourceDecorator *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecComponentEventSourceDecoratorPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComponentEventSourceDecorator *,
                      WeakRefCountPolicy, nsOSG      > SFWeakComponentEventSourceDecoratorPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComponentEventSourceDecorator *,
                      NoRefCountPolicy, nsOSG        > SFUncountedComponentEventSourceDecoratorPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComponentEventSourceDecorator *,
                      RecordedRefCountPolicy, nsOSG  > MFRecComponentEventSourceDecoratorPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComponentEventSourceDecorator *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecComponentEventSourceDecoratorPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComponentEventSourceDecorator *,
                      WeakRefCountPolicy, nsOSG      > MFWeakComponentEventSourceDecoratorPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComponentEventSourceDecorator *,
                      NoRefCountPolicy, nsOSG        > MFUncountedComponentEventSourceDecoratorPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecComponentEventSourceDecoratorPtr : 
    public PointerSField<ComponentEventSourceDecorator *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecComponentEventSourceDecoratorPtr : 
    public PointerSField<ComponentEventSourceDecorator *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakComponentEventSourceDecoratorPtr :
    public PointerSField<ComponentEventSourceDecorator *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedComponentEventSourceDecoratorPtr :
    public PointerSField<ComponentEventSourceDecorator *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecComponentEventSourceDecoratorPtr :
    public PointerMField<ComponentEventSourceDecorator *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecComponentEventSourceDecoratorPtr :
    public PointerMField<ComponentEventSourceDecorator *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakComponentEventSourceDecoratorPtr :
    public PointerMField<ComponentEventSourceDecorator *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedComponentEventSourceDecoratorPtr :
    public PointerMField<ComponentEventSourceDecorator *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGCOMPONENTEVENTSOURCEDECORATORFIELDS_H_ */
