/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCOMPONENTFIELDS_H_
#define _OSGCOMPONENTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class Component;

OSG_GEN_CONTAINERPTR(Component);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<Component *, nsOSG> :
    public FieldTraitsFCPtrBase<Component *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<Component *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<Component *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<Component *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<Component *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<Component *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<Component *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<Component *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<Component *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<Component *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdComponentPtr"; 
}


/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
 */
template <>
struct FieldTraits<Component *, nsOSG + 1> :
    public FieldTraitsFCPtrBase<Component *, nsOSG + 1>
{
  private:

  public:
    typedef FieldTraits<Component *, nsOSG + 1>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);
};

template<> inline
const Char8 *FieldTraits<Component *, nsOSG + 1>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecChildComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<Component *, nsOSG + 1>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecChildComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<Component *, nsOSG + 1>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakChildComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<Component *, nsOSG + 1>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdChildComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<Component *, nsOSG + 1>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecChildComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<Component *, nsOSG + 1>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecChildComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<Component *, nsOSG + 1>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakChildComponentPtr"; 
}

template<> inline
const Char8 *FieldTraits<Component *, nsOSG + 1>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdChildComponentPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<Component *,
                      RecordedRefCountPolicy, nsOSG  > SFRecComponentPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<Component *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecComponentPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<Component *,
                      WeakRefCountPolicy, nsOSG      > SFWeakComponentPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<Component *,
                      NoRefCountPolicy, nsOSG        > SFUncountedComponentPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<Component *,
                      RecordedRefCountPolicy, nsOSG  > MFRecComponentPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<Component *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecComponentPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<Component *,
                      WeakRefCountPolicy, nsOSG      > MFWeakComponentPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<Component *,
                      NoRefCountPolicy, nsOSG        > MFUncountedComponentPtr;



/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef ChildPointerMField<
          Component *, 
          UnrecordedRefCountPolicy,
          nsOSG + 1             > MFUnrecChildComponentPtr;



#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecComponentPtr : 
    public PointerSField<Component *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecComponentPtr : 
    public PointerSField<Component *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakComponentPtr :
    public PointerSField<Component *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedComponentPtr :
    public PointerSField<Component *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecComponentPtr :
    public PointerMField<Component *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecComponentPtr :
    public PointerMField<Component *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakComponentPtr :
    public PointerMField<Component *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedComponentPtr :
    public PointerMField<Component *,
                         NoRefCountPolicy        > {};



/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecChildComponentPtr :
    public ChildPointerMField<
        Component *, 
        UnrecordedRefCountPolicy,
        nsOSG + 1             > {};


#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGCOMPONENTFIELDS_H_ */
