/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCOMPONENTDECORATORFIELDS_H_
#define _OSGCOMPONENTDECORATORFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class ComponentDecorator;

OSG_GEN_CONTAINERPTR(ComponentDecorator);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<ComponentDecorator *, nsOSG> :
    public FieldTraitsFCPtrBase<ComponentDecorator *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<ComponentDecorator *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<ComponentDecorator *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecComponentDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentDecorator *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecComponentDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentDecorator *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakComponentDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentDecorator *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdComponentDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentDecorator *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecComponentDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentDecorator *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecComponentDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentDecorator *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakComponentDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentDecorator *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdComponentDecoratorPtr"; 
}


/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
 */
template <>
struct FieldTraits<ComponentDecorator *, nsOSG + 1> :
    public FieldTraitsFCPtrBase<ComponentDecorator *, nsOSG + 1>
{
  private:

  public:
    typedef FieldTraits<ComponentDecorator *, nsOSG + 1>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);
};

template<> inline
const Char8 *FieldTraits<ComponentDecorator *, nsOSG + 1>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecChildComponentDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentDecorator *, nsOSG + 1>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecChildComponentDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentDecorator *, nsOSG + 1>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakChildComponentDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentDecorator *, nsOSG + 1>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdChildComponentDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentDecorator *, nsOSG + 1>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecChildComponentDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentDecorator *, nsOSG + 1>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecChildComponentDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentDecorator *, nsOSG + 1>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakChildComponentDecoratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComponentDecorator *, nsOSG + 1>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdChildComponentDecoratorPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComponentDecorator *,
                      RecordedRefCountPolicy, nsOSG  > SFRecComponentDecoratorPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComponentDecorator *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecComponentDecoratorPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComponentDecorator *,
                      WeakRefCountPolicy, nsOSG      > SFWeakComponentDecoratorPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComponentDecorator *,
                      NoRefCountPolicy, nsOSG        > SFUncountedComponentDecoratorPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComponentDecorator *,
                      RecordedRefCountPolicy, nsOSG  > MFRecComponentDecoratorPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComponentDecorator *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecComponentDecoratorPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComponentDecorator *,
                      WeakRefCountPolicy, nsOSG      > MFWeakComponentDecoratorPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComponentDecorator *,
                      NoRefCountPolicy, nsOSG        > MFUncountedComponentDecoratorPtr;



/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef ChildPointerMField<
          ComponentDecorator *, 
          UnrecordedRefCountPolicy,
          nsOSG + 1             > MFUnrecChildComponentDecoratorPtr;



#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecComponentDecoratorPtr : 
    public PointerSField<ComponentDecorator *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecComponentDecoratorPtr : 
    public PointerSField<ComponentDecorator *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakComponentDecoratorPtr :
    public PointerSField<ComponentDecorator *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedComponentDecoratorPtr :
    public PointerSField<ComponentDecorator *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecComponentDecoratorPtr :
    public PointerMField<ComponentDecorator *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecComponentDecoratorPtr :
    public PointerMField<ComponentDecorator *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakComponentDecoratorPtr :
    public PointerMField<ComponentDecorator *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedComponentDecoratorPtr :
    public PointerMField<ComponentDecorator *,
                         NoRefCountPolicy        > {};



/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecChildComponentDecoratorPtr :
    public ChildPointerMField<
        ComponentDecorator *, 
        UnrecordedRefCountPolicy,
        nsOSG + 1             > {};


#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGCOMPONENTDECORATORFIELDS_H_ */
