/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGUIVIEWPORTEVENTSOURCEFIELDS_H_
#define _OSGUIVIEWPORTEVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class UIViewportEventSource;

OSG_GEN_CONTAINERPTR(UIViewportEventSource);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<UIViewportEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<UIViewportEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<UIViewportEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<UIViewportEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecUIViewportEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<UIViewportEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecUIViewportEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<UIViewportEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakUIViewportEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<UIViewportEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdUIViewportEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<UIViewportEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecUIViewportEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<UIViewportEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecUIViewportEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<UIViewportEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakUIViewportEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<UIViewportEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdUIViewportEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<UIViewportEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecUIViewportEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<UIViewportEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecUIViewportEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<UIViewportEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakUIViewportEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<UIViewportEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedUIViewportEventSourcePtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<UIViewportEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecUIViewportEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<UIViewportEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecUIViewportEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<UIViewportEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakUIViewportEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<UIViewportEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedUIViewportEventSourcePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecUIViewportEventSourcePtr : 
    public PointerSField<UIViewportEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecUIViewportEventSourcePtr : 
    public PointerSField<UIViewportEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakUIViewportEventSourcePtr :
    public PointerSField<UIViewportEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedUIViewportEventSourcePtr :
    public PointerSField<UIViewportEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecUIViewportEventSourcePtr :
    public PointerMField<UIViewportEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecUIViewportEventSourcePtr :
    public PointerMField<UIViewportEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakUIViewportEventSourcePtr :
    public PointerMField<UIViewportEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedUIViewportEventSourcePtr :
    public PointerMField<UIViewportEventSource *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGUIVIEWPORTEVENTSOURCEFIELDS_H_ */
