/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGUIVIEWPORTFIELDS_H_
#define _OSGUIVIEWPORTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class UIViewport;

OSG_GEN_CONTAINERPTR(UIViewport);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<UIViewport *, nsOSG> :
    public FieldTraitsFCPtrBase<UIViewport *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<UIViewport *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<UIViewport *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecUIViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<UIViewport *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecUIViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<UIViewport *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakUIViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<UIViewport *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdUIViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<UIViewport *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecUIViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<UIViewport *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecUIViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<UIViewport *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakUIViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<UIViewport *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdUIViewportPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<UIViewport *,
                      RecordedRefCountPolicy, nsOSG  > SFRecUIViewportPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<UIViewport *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecUIViewportPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<UIViewport *,
                      WeakRefCountPolicy, nsOSG      > SFWeakUIViewportPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<UIViewport *,
                      NoRefCountPolicy, nsOSG        > SFUncountedUIViewportPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<UIViewport *,
                      RecordedRefCountPolicy, nsOSG  > MFRecUIViewportPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<UIViewport *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecUIViewportPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<UIViewport *,
                      WeakRefCountPolicy, nsOSG      > MFWeakUIViewportPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<UIViewport *,
                      NoRefCountPolicy, nsOSG        > MFUncountedUIViewportPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecUIViewportPtr : 
    public PointerSField<UIViewport *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecUIViewportPtr : 
    public PointerSField<UIViewport *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakUIViewportPtr :
    public PointerSField<UIViewport *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedUIViewportPtr :
    public PointerSField<UIViewport *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecUIViewportPtr :
    public PointerMField<UIViewport *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecUIViewportPtr :
    public PointerMField<UIViewport *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakUIViewportPtr :
    public PointerMField<UIViewport *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedUIViewportPtr :
    public PointerMField<UIViewport *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGUIVIEWPORTFIELDS_H_ */
