/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class UIViewportEventSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"


#include "OSGUIViewportEventSourceBase.h"
#include "OSGUIViewportEventSource.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::UIViewportEventSource
    A UI UIViewport
 */



/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<UIViewportEventSource *, nsOSG>::_type(
    "UIViewportEventSourcePtr",
    "ComponentEventSourcePtr",
    UIViewportEventSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(UIViewportEventSource *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           UIViewportEventSource *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           UIViewportEventSource *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void UIViewportEventSourceBase::classDescInserter(TypeObject &oType)
{
}


UIViewportEventSourceBase::TypeObject UIViewportEventSourceBase::_type(
    UIViewportEventSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&UIViewportEventSourceBase::createEmptyLocal),
    UIViewportEventSource::initMethod,
    UIViewportEventSource::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&UIViewportEventSource::classDescInserter),
    false,
    0,
    "",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &UIViewportEventSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &UIViewportEventSourceBase::getType(void) const
{
    return _type;
}

UInt32 UIViewportEventSourceBase::getContainerSize(void) const
{
    return sizeof(UIViewportEventSource);
}



/*------------------------------ access -----------------------------------*/

SizeT UIViewportEventSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    return returnValue;
}

void UIViewportEventSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);
}

void UIViewportEventSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);
}

//! create a new instance of the class
UIViewportEventSourceTransitPtr UIViewportEventSourceBase::createLocal(BitVector bFlags)
{
    UIViewportEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<UIViewportEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
UIViewportEventSourceTransitPtr UIViewportEventSourceBase::createDependent(BitVector bFlags)
{
    UIViewportEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<UIViewportEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
UIViewportEventSourceTransitPtr UIViewportEventSourceBase::create(void)
{
    UIViewportEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<UIViewportEventSource>(tmpPtr);
    }

    return fc;
}

UIViewportEventSource *UIViewportEventSourceBase::createEmptyLocal(BitVector bFlags)
{
    UIViewportEventSource *returnValue;

    newPtr<UIViewportEventSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
UIViewportEventSource *UIViewportEventSourceBase::createEmpty(void)
{
    UIViewportEventSource *returnValue;

    newPtr<UIViewportEventSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr UIViewportEventSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    UIViewportEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const UIViewportEventSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr UIViewportEventSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    UIViewportEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const UIViewportEventSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr UIViewportEventSourceBase::shallowCopy(void) const
{
    UIViewportEventSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const UIViewportEventSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

UIViewportEventSourceBase::UIViewportEventSourceBase(void) :
    Inherited()
{
}

UIViewportEventSourceBase::UIViewportEventSourceBase(const UIViewportEventSourceBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

UIViewportEventSourceBase::~UIViewportEventSourceBase(void)
{
}


#ifdef OSG_MT_CPTR_ASPECT
void UIViewportEventSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    UIViewportEventSource *pThis = static_cast<UIViewportEventSource *>(this);

    pThis->execSync(static_cast<UIViewportEventSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *UIViewportEventSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    UIViewportEventSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const UIViewportEventSource *>(pRefAspect),
                  dynamic_cast<const UIViewportEventSource *>(this));

    return returnValue;
}
#endif

void UIViewportEventSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();

}

OSG_END_NAMESPACE
