/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TreeSelectionModelEventSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"




#include "OSGTreeSelectionModelEventSourceBase.h"
#include "OSGTreeSelectionModelEventSource.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TreeSelectionModelEventSource
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<TreeSelectionModelEventSource *, nsOSG>::_type(
    "TreeSelectionModelEventSourcePtr", 
    "EventContainerPtr", 
    TreeSelectionModelEventSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(TreeSelectionModelEventSource *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TreeSelectionModelEventSource *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TreeSelectionModelEventSource *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TreeSelectionModelEventSourceBase::classDescInserter(TypeObject &oType)
{
}


TreeSelectionModelEventSourceBase::TypeObject TreeSelectionModelEventSourceBase::_type(
    TreeSelectionModelEventSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&TreeSelectionModelEventSourceBase::createEmptyLocal),
    TreeSelectionModelEventSource::initMethod,
    TreeSelectionModelEventSource::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TreeSelectionModelEventSource::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"TreeSelectionModelEventSource\"\n"
    "    parent=\"EventContainer\"\n"
    "    library=\"ContribToolboxUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    ">\n"
    "<!--\n"
    "    <ProducedEvent\n"
    "        name=\"SelectionAdded\"\n"
    "        detailsType=\"TreeSelectionEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"SelectionRemoved\"\n"
    "        detailsType=\"TreeSelectionEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "-->\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TreeSelectionModelEventSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &TreeSelectionModelEventSourceBase::getType(void) const
{
    return _type;
}

UInt32 TreeSelectionModelEventSourceBase::getContainerSize(void) const
{
    return sizeof(TreeSelectionModelEventSource);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

SizeT TreeSelectionModelEventSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void TreeSelectionModelEventSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void TreeSelectionModelEventSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
TreeSelectionModelEventSourceTransitPtr TreeSelectionModelEventSourceBase::createLocal(BitVector bFlags)
{
    TreeSelectionModelEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<TreeSelectionModelEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
TreeSelectionModelEventSourceTransitPtr TreeSelectionModelEventSourceBase::createDependent(BitVector bFlags)
{
    TreeSelectionModelEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<TreeSelectionModelEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
TreeSelectionModelEventSourceTransitPtr TreeSelectionModelEventSourceBase::create(void)
{
    TreeSelectionModelEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<TreeSelectionModelEventSource>(tmpPtr);
    }

    return fc;
}

TreeSelectionModelEventSource *TreeSelectionModelEventSourceBase::createEmptyLocal(BitVector bFlags)
{
    TreeSelectionModelEventSource *returnValue;

    newPtr<TreeSelectionModelEventSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
TreeSelectionModelEventSource *TreeSelectionModelEventSourceBase::createEmpty(void)
{
    TreeSelectionModelEventSource *returnValue;

    newPtr<TreeSelectionModelEventSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr TreeSelectionModelEventSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    TreeSelectionModelEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TreeSelectionModelEventSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr TreeSelectionModelEventSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    TreeSelectionModelEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TreeSelectionModelEventSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr TreeSelectionModelEventSourceBase::shallowCopy(void) const
{
    TreeSelectionModelEventSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const TreeSelectionModelEventSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

TreeSelectionModelEventSourceBase::TreeSelectionModelEventSourceBase(void) :
    Inherited()
{
}

TreeSelectionModelEventSourceBase::TreeSelectionModelEventSourceBase(const TreeSelectionModelEventSourceBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

TreeSelectionModelEventSourceBase::~TreeSelectionModelEventSourceBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void TreeSelectionModelEventSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TreeSelectionModelEventSource *pThis = static_cast<TreeSelectionModelEventSource *>(this);

    pThis->execSync(static_cast<TreeSelectionModelEventSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *TreeSelectionModelEventSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    TreeSelectionModelEventSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const TreeSelectionModelEventSource *>(pRefAspect),
                  dynamic_cast<const TreeSelectionModelEventSource *>(this));

    return returnValue;
}
#endif

void TreeSelectionModelEventSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
