/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TreeSelectionModel!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"



#include "OSGTreeSelectionModelEventSource.h" // EventSource Class

#include "OSGTreeSelectionModelBase.h"
#include "OSGTreeSelectionModel.h"
#include "OSGTreeSelectionModelEventSource.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TreeSelectionModel
    A UI TreeModel.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var TreeSelectionModelEventSource * TreeSelectionModelBase::_sfEventSource
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<TreeSelectionModel *, nsOSG>::_type(
    "TreeSelectionModelPtr", 
    "AttachmentContainerPtr", 
    TreeSelectionModel::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(TreeSelectionModel *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TreeSelectionModel *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TreeSelectionModel *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TreeSelectionModelBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecTreeSelectionModelEventSourcePtr::Description(
        SFUnrecTreeSelectionModelEventSourcePtr::getClassType(),
        "EventSource",
        "",
        EventSourceFieldId, EventSourceFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&TreeSelectionModel::editHandleEventSource),
        static_cast<FieldGetMethodSig >(&TreeSelectionModel::getHandleEventSource));

    oType.addInitialDesc(pDesc);
}


TreeSelectionModelBase::TypeObject TreeSelectionModelBase::_type(
    TreeSelectionModelBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    NULL,
    TreeSelectionModel::initMethod,
    TreeSelectionModel::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TreeSelectionModel::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"TreeSelectionModel\"\n"
    "    parent=\"AttachmentContainer\"\n"
    "    library=\"ContribToolboxUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"abstract\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "A UI TreeModel.\n"
    "    <Field\n"
    "        name=\"EventSource\"\n"
    "        type=\"TreeSelectionModelEventSource\"\n"
    "        category=\"pointer\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        defaultValue=\"NULL\"\n"
    "        access=\"public\"\n"
    "        >\n"
    "    </Field>\n"
    "    <ProducedEvent\n"
    "        name=\"SelectionAdded\"\n"
    "        detailsType=\"TreeSelectionEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"SelectionRemoved\"\n"
    "        detailsType=\"TreeSelectionEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "</FieldContainer>\n",
    "A UI TreeModel.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TreeSelectionModelBase::getType(void)
{
    return _type;
}

const FieldContainerType &TreeSelectionModelBase::getType(void) const
{
    return _type;
}

UInt32 TreeSelectionModelBase::getContainerSize(void) const
{
    return sizeof(TreeSelectionModel);
}

/*------------------------- decorator get ------------------------------*/


//! Get the TreeSelectionModel::_sfEventSource field.
const SFUnrecTreeSelectionModelEventSourcePtr *TreeSelectionModelBase::getSFEventSource(void) const
{
    return &_sfEventSource;
}

SFUnrecTreeSelectionModelEventSourcePtr *TreeSelectionModelBase::editSFEventSource    (void)
{
    editSField(EventSourceFieldMask);

    return &_sfEventSource;
}






/*------------------------------ access -----------------------------------*/

SizeT TreeSelectionModelBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        returnValue += _sfEventSource.getBinSize();
    }

    return returnValue;
}

void TreeSelectionModelBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        _sfEventSource.copyToBin(pMem);
    }
}

void TreeSelectionModelBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        editSField(EventSourceFieldMask);
        _sfEventSource.copyFromBin(pMem);
    }
}




/*------------------------- constructors ----------------------------------*/

TreeSelectionModelBase::TreeSelectionModelBase(void) :
    Inherited(),
    _sfEventSource            (NULL)
{
}

TreeSelectionModelBase::TreeSelectionModelBase(const TreeSelectionModelBase &source) :
    Inherited(source),
    _sfEventSource            (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

TreeSelectionModelBase::~TreeSelectionModelBase(void)
{
}

void TreeSelectionModelBase::onCreate(const TreeSelectionModel *source)
{
    Inherited::onCreate(source);

    if(source)
    {
        TreeSelectionModel *pThis = static_cast<TreeSelectionModel *>(this);

        pThis->setEventSource(source->getEventSource());
    }
    
    {
        TreeSelectionModelEventSourceUnrecPtr evSrc = TreeSelectionModelEventSource::create();
        setEventSource( evSrc );
    }
}

GetFieldHandlePtr TreeSelectionModelBase::getHandleEventSource     (void) const
{
    SFUnrecTreeSelectionModelEventSourcePtr::GetHandlePtr returnValue(
        new  SFUnrecTreeSelectionModelEventSourcePtr::GetHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             const_cast<TreeSelectionModelBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr TreeSelectionModelBase::editHandleEventSource    (void)
{
    SFUnrecTreeSelectionModelEventSourcePtr::EditHandlePtr returnValue(
        new  SFUnrecTreeSelectionModelEventSourcePtr::EditHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&TreeSelectionModel::setEventSource,
                    static_cast<TreeSelectionModel *>(this), _1));

    editSField(EventSourceFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void TreeSelectionModelBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TreeSelectionModel *pThis = static_cast<TreeSelectionModel *>(this);

    pThis->execSync(static_cast<TreeSelectionModel *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif



void TreeSelectionModelBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<TreeSelectionModel *>(this)->setEventSource(NULL);


}


boost::signals2::connection  TreeSelectionModelBase::connectSelectionAdded(
                                                    const TreeSelectionModelEventSource::SelectionAddedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectSelectionAdded( listener, at );
}

boost::signals2::connection  TreeSelectionModelBase::connectSelectionAdded(
                                                    const TreeSelectionModelEventSource::SelectionAddedEventType::group_type &group,
                                                    const TreeSelectionModelEventSource::SelectionAddedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectSelectionAdded( group, listener, at );
}

void  TreeSelectionModelBase::disconnectSelectionAdded(
                                                    const TreeSelectionModelEventSource::SelectionAddedEventType::group_type &group
)
{
    getEventSource()->disconnectSelectionAdded( group );
}

void  TreeSelectionModelBase::disconnectAllSlotsSelectionAdded(void)
{
    getEventSource()->disconnectAllSlotsSelectionAdded();
}

bool  TreeSelectionModelBase::isEmptySelectionAdded(void) const
{
    return getEventSource()->isEmptySelectionAdded();
}

UInt32  TreeSelectionModelBase::numSlotsSelectionAdded(void) const
{
    return getEventSource()->numSlotsSelectionAdded();
}

boost::signals2::connection  TreeSelectionModelBase::connectSelectionRemoved(
                                                    const TreeSelectionModelEventSource::SelectionRemovedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectSelectionRemoved( listener, at );
}

boost::signals2::connection  TreeSelectionModelBase::connectSelectionRemoved(
                                                    const TreeSelectionModelEventSource::SelectionRemovedEventType::group_type &group,
                                                    const TreeSelectionModelEventSource::SelectionRemovedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectSelectionRemoved( group, listener, at );
}

void  TreeSelectionModelBase::disconnectSelectionRemoved(
                                                    const TreeSelectionModelEventSource::SelectionRemovedEventType::group_type &group
)
{
    getEventSource()->disconnectSelectionRemoved( group );
}

void  TreeSelectionModelBase::disconnectAllSlotsSelectionRemoved(void)
{
    getEventSource()->disconnectAllSlotsSelectionRemoved();
}

bool  TreeSelectionModelBase::isEmptySelectionRemoved(void) const
{
    return getEventSource()->isEmptySelectionRemoved();
}

UInt32  TreeSelectionModelBase::numSlotsSelectionRemoved(void) const
{
    return getEventSource()->numSlotsSelectionRemoved();
}

OSG_END_NAMESPACE
