/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TableModelEventSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"


#include "OSGTableModelEventSourceBase.h"
#include "OSGTableModelEventSource.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TableModelEventSource
    A UI TableModel.
 */



/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<TableModelEventSource *, nsOSG>::_type(
    "TableModelEventSourcePtr",
    "EventContainerPtr",
    TableModelEventSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(TableModelEventSource *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TableModelEventSource *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TableModelEventSource *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TableModelEventSourceBase::classDescInserter(TypeObject &oType)
{
}


TableModelEventSourceBase::TypeObject TableModelEventSourceBase::_type(
    TableModelEventSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&TableModelEventSourceBase::createEmptyLocal),
    TableModelEventSource::initMethod,
    TableModelEventSource::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TableModelEventSource::classDescInserter),
    false,
    0,
    "",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TableModelEventSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &TableModelEventSourceBase::getType(void) const
{
    return _type;
}

UInt32 TableModelEventSourceBase::getContainerSize(void) const
{
    return sizeof(TableModelEventSource);
}



/*------------------------------ access -----------------------------------*/

SizeT TableModelEventSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    return returnValue;
}

void TableModelEventSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);
}

void TableModelEventSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);
}

//! create a new instance of the class
TableModelEventSourceTransitPtr TableModelEventSourceBase::createLocal(BitVector bFlags)
{
    TableModelEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<TableModelEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
TableModelEventSourceTransitPtr TableModelEventSourceBase::createDependent(BitVector bFlags)
{
    TableModelEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<TableModelEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
TableModelEventSourceTransitPtr TableModelEventSourceBase::create(void)
{
    TableModelEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<TableModelEventSource>(tmpPtr);
    }

    return fc;
}

TableModelEventSource *TableModelEventSourceBase::createEmptyLocal(BitVector bFlags)
{
    TableModelEventSource *returnValue;

    newPtr<TableModelEventSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
TableModelEventSource *TableModelEventSourceBase::createEmpty(void)
{
    TableModelEventSource *returnValue;

    newPtr<TableModelEventSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr TableModelEventSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    TableModelEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TableModelEventSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr TableModelEventSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    TableModelEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TableModelEventSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr TableModelEventSourceBase::shallowCopy(void) const
{
    TableModelEventSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const TableModelEventSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

TableModelEventSourceBase::TableModelEventSourceBase(void) :
    Inherited()
{
}

TableModelEventSourceBase::TableModelEventSourceBase(const TableModelEventSourceBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

TableModelEventSourceBase::~TableModelEventSourceBase(void)
{
}


#ifdef OSG_MT_CPTR_ASPECT
void TableModelEventSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TableModelEventSource *pThis = static_cast<TableModelEventSource *>(this);

    pThis->execSync(static_cast<TableModelEventSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *TableModelEventSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    TableModelEventSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const TableModelEventSource *>(pRefAspect),
                  dynamic_cast<const TableModelEventSource *>(this));

    return returnValue;
}
#endif

void TableModelEventSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();

}

OSG_END_NAMESPACE
