/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTABLECOLUMNMODELFIELDS_H_
#define _OSGTABLECOLUMNMODELFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TableColumnModel;

OSG_GEN_CONTAINERPTR(TableColumnModel);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<TableColumnModel *, nsOSG> :
    public FieldTraitsFCPtrBase<TableColumnModel *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TableColumnModel *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TableColumnModel *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTableColumnModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumnModel *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTableColumnModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumnModel *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTableColumnModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumnModel *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTableColumnModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumnModel *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTableColumnModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumnModel *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTableColumnModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumnModel *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTableColumnModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumnModel *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTableColumnModelPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TableColumnModel *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTableColumnModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TableColumnModel *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTableColumnModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TableColumnModel *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTableColumnModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TableColumnModel *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTableColumnModelPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TableColumnModel *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTableColumnModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TableColumnModel *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTableColumnModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TableColumnModel *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTableColumnModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TableColumnModel *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTableColumnModelPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecTableColumnModelPtr : 
    public PointerSField<TableColumnModel *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecTableColumnModelPtr : 
    public PointerSField<TableColumnModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakTableColumnModelPtr :
    public PointerSField<TableColumnModel *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedTableColumnModelPtr :
    public PointerSField<TableColumnModel *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecTableColumnModelPtr :
    public PointerMField<TableColumnModel *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecTableColumnModelPtr :
    public PointerMField<TableColumnModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakTableColumnModelPtr :
    public PointerMField<TableColumnModel *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedTableColumnModelPtr :
    public PointerMField<TableColumnModel *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTABLECOLUMNMODELFIELDS_H_ */
