/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTABLEMODELFIELDS_H_
#define _OSGTABLEMODELFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TableModel;

OSG_GEN_CONTAINERPTR(TableModel);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<TableModel *, nsOSG> :
    public FieldTraitsFCPtrBase<TableModel *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TableModel *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TableModel *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTableModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableModel *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTableModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableModel *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTableModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableModel *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTableModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableModel *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTableModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableModel *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTableModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableModel *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTableModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableModel *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTableModelPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TableModel *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTableModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TableModel *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTableModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TableModel *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTableModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TableModel *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTableModelPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TableModel *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTableModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TableModel *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTableModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TableModel *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTableModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TableModel *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTableModelPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecTableModelPtr : 
    public PointerSField<TableModel *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecTableModelPtr : 
    public PointerSField<TableModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakTableModelPtr :
    public PointerSField<TableModel *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedTableModelPtr :
    public PointerSField<TableModel *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecTableModelPtr :
    public PointerMField<TableModel *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecTableModelPtr :
    public PointerMField<TableModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakTableModelPtr :
    public PointerMField<TableModel *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedTableModelPtr :
    public PointerMField<TableModel *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTABLEMODELFIELDS_H_ */
