/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TableModel!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"



#include "OSGTableModelEventSource.h"   // EventSource Class

#include "OSGTableModelBase.h"
#include "OSGTableModel.h"
#include "OSGTableModelEventSource.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TableModel
    A UI TableModel.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var TableModelEventSource * TableModelBase::_sfEventSource
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<TableModel *, nsOSG>::_type(
    "TableModelPtr", 
    "FieldContainerPtr", 
    TableModel::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(TableModel *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TableModel *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TableModel *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TableModelBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecTableModelEventSourcePtr::Description(
        SFUnrecTableModelEventSourcePtr::getClassType(),
        "EventSource",
        "",
        EventSourceFieldId, EventSourceFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&TableModel::editHandleEventSource),
        static_cast<FieldGetMethodSig >(&TableModel::getHandleEventSource));

    oType.addInitialDesc(pDesc);
}


TableModelBase::TypeObject TableModelBase::_type(
    TableModelBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    NULL,
    TableModel::initMethod,
    TableModel::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TableModel::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"TableModel\"\n"
    "    parent=\"FieldContainer\"\n"
    "    library=\"ContribToolboxUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"abstract\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "A UI TableModel.\n"
    "    <Field\n"
    "        name=\"EventSource\"\n"
    "        type=\"TableModelEventSource\"\n"
    "        category=\"pointer\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        defaultValue=\"NULL\"\n"
    "        access=\"public\"\n"
    "    >\n"
    "    </Field>\n"
    "    <ProducedEvent\n"
    "        name=\"ContentsHeaderRowChanged\"\n"
    "        detailsType=\"TableModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"ContentsChanged\"\n"
    "        detailsType=\"TableModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"IntervalAdded\"\n"
    "        detailsType=\"TableModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"IntervalRemoved\"\n"
    "        detailsType=\"TableModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "</FieldContainer>\n",
    "A UI TableModel.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TableModelBase::getType(void)
{
    return _type;
}

const FieldContainerType &TableModelBase::getType(void) const
{
    return _type;
}

UInt32 TableModelBase::getContainerSize(void) const
{
    return sizeof(TableModel);
}

/*------------------------- decorator get ------------------------------*/


//! Get the TableModel::_sfEventSource field.
const SFUnrecTableModelEventSourcePtr *TableModelBase::getSFEventSource(void) const
{
    return &_sfEventSource;
}

SFUnrecTableModelEventSourcePtr *TableModelBase::editSFEventSource    (void)
{
    editSField(EventSourceFieldMask);

    return &_sfEventSource;
}






/*------------------------------ access -----------------------------------*/

SizeT TableModelBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        returnValue += _sfEventSource.getBinSize();
    }

    return returnValue;
}

void TableModelBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        _sfEventSource.copyToBin(pMem);
    }
}

void TableModelBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        editSField(EventSourceFieldMask);
        _sfEventSource.copyFromBin(pMem);
    }
}




/*------------------------- constructors ----------------------------------*/

TableModelBase::TableModelBase(void) :
    Inherited(),
    _sfEventSource            (NULL)
{
}

TableModelBase::TableModelBase(const TableModelBase &source) :
    Inherited(source),
    _sfEventSource            (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

TableModelBase::~TableModelBase(void)
{
}

void TableModelBase::onCreate(const TableModel *source)
{
    Inherited::onCreate(source);

    if(source)
    {
        TableModel *pThis = static_cast<TableModel *>(this);

        pThis->setEventSource(source->getEventSource());
    }
    
    {
        TableModelEventSourceUnrecPtr evSrc = TableModelEventSource::create();
        setEventSource( evSrc );
    }
}

GetFieldHandlePtr TableModelBase::getHandleEventSource     (void) const
{
    SFUnrecTableModelEventSourcePtr::GetHandlePtr returnValue(
        new  SFUnrecTableModelEventSourcePtr::GetHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             const_cast<TableModelBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr TableModelBase::editHandleEventSource    (void)
{
    SFUnrecTableModelEventSourcePtr::EditHandlePtr returnValue(
        new  SFUnrecTableModelEventSourcePtr::EditHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&TableModel::setEventSource,
                    static_cast<TableModel *>(this), _1));

    editSField(EventSourceFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void TableModelBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TableModel *pThis = static_cast<TableModel *>(this);

    pThis->execSync(static_cast<TableModel *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif



void TableModelBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<TableModel *>(this)->setEventSource(NULL);


}


boost::signals2::connection  TableModelBase::connectContentsHeaderRowChanged(
                                                    const TableModelEventSource::ContentsHeaderRowChangedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectContentsHeaderRowChanged( listener, at );
}

boost::signals2::connection  TableModelBase::connectContentsHeaderRowChanged(
                                                    const TableModelEventSource::ContentsHeaderRowChangedEventType::group_type &group,
                                                    const TableModelEventSource::ContentsHeaderRowChangedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectContentsHeaderRowChanged( group, listener, at );
}

void  TableModelBase::disconnectContentsHeaderRowChanged(
                                                    const TableModelEventSource::ContentsHeaderRowChangedEventType::group_type &group
)
{
    getEventSource()->disconnectContentsHeaderRowChanged( group );
}

void  TableModelBase::disconnectAllSlotsContentsHeaderRowChanged(void)
{
    getEventSource()->disconnectAllSlotsContentsHeaderRowChanged();
}

bool  TableModelBase::isEmptyContentsHeaderRowChanged(void) const
{
    return getEventSource()->isEmptyContentsHeaderRowChanged();
}

UInt32  TableModelBase::numSlotsContentsHeaderRowChanged(void) const
{
    return getEventSource()->numSlotsContentsHeaderRowChanged();
}

boost::signals2::connection  TableModelBase::connectContentsChanged(
                                                    const TableModelEventSource::ContentsChangedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectContentsChanged( listener, at );
}

boost::signals2::connection  TableModelBase::connectContentsChanged(
                                                    const TableModelEventSource::ContentsChangedEventType::group_type &group,
                                                    const TableModelEventSource::ContentsChangedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectContentsChanged( group, listener, at );
}

void  TableModelBase::disconnectContentsChanged(
                                                    const TableModelEventSource::ContentsChangedEventType::group_type &group
)
{
    getEventSource()->disconnectContentsChanged( group );
}

void  TableModelBase::disconnectAllSlotsContentsChanged(void)
{
    getEventSource()->disconnectAllSlotsContentsChanged();
}

bool  TableModelBase::isEmptyContentsChanged(void) const
{
    return getEventSource()->isEmptyContentsChanged();
}

UInt32  TableModelBase::numSlotsContentsChanged(void) const
{
    return getEventSource()->numSlotsContentsChanged();
}

boost::signals2::connection  TableModelBase::connectIntervalAdded(
                                                    const TableModelEventSource::IntervalAddedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectIntervalAdded( listener, at );
}

boost::signals2::connection  TableModelBase::connectIntervalAdded(
                                                    const TableModelEventSource::IntervalAddedEventType::group_type &group,
                                                    const TableModelEventSource::IntervalAddedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectIntervalAdded( group, listener, at );
}

void  TableModelBase::disconnectIntervalAdded(
                                                    const TableModelEventSource::IntervalAddedEventType::group_type &group
)
{
    getEventSource()->disconnectIntervalAdded( group );
}

void  TableModelBase::disconnectAllSlotsIntervalAdded(void)
{
    getEventSource()->disconnectAllSlotsIntervalAdded();
}

bool  TableModelBase::isEmptyIntervalAdded(void) const
{
    return getEventSource()->isEmptyIntervalAdded();
}

UInt32  TableModelBase::numSlotsIntervalAdded(void) const
{
    return getEventSource()->numSlotsIntervalAdded();
}

boost::signals2::connection  TableModelBase::connectIntervalRemoved(
                                                    const TableModelEventSource::IntervalRemovedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectIntervalRemoved( listener, at );
}

boost::signals2::connection  TableModelBase::connectIntervalRemoved(
                                                    const TableModelEventSource::IntervalRemovedEventType::group_type &group,
                                                    const TableModelEventSource::IntervalRemovedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectIntervalRemoved( group, listener, at );
}

void  TableModelBase::disconnectIntervalRemoved(
                                                    const TableModelEventSource::IntervalRemovedEventType::group_type &group
)
{
    getEventSource()->disconnectIntervalRemoved( group );
}

void  TableModelBase::disconnectAllSlotsIntervalRemoved(void)
{
    getEventSource()->disconnectAllSlotsIntervalRemoved();
}

bool  TableModelBase::isEmptyIntervalRemoved(void) const
{
    return getEventSource()->isEmptyIntervalRemoved();
}

UInt32  TableModelBase::numSlotsIntervalRemoved(void) const
{
    return getEventSource()->numSlotsIntervalRemoved();
}

OSG_END_NAMESPACE
