/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TreeModelLayout!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"



#include "OSGTreeModelLayoutEventSource.h" // EventSource Class

#include "OSGTreeModelLayoutBase.h"
#include "OSGTreeModelLayout.h"
#include "OSGTreeModelLayoutEventSource.h"
#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TreeModelLayout
    A UI Tree Model Layout.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var TreeModelLayoutEventSource * TreeModelLayoutBase::_sfEventSource
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<TreeModelLayout *, nsOSG>::_type(
    "TreeModelLayoutPtr", 
    "TreeRowMapperPtr", 
    TreeModelLayout::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(TreeModelLayout *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TreeModelLayout *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TreeModelLayout *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TreeModelLayoutBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecTreeModelLayoutEventSourcePtr::Description(
        SFUnrecTreeModelLayoutEventSourcePtr::getClassType(),
        "EventSource",
        "",
        EventSourceFieldId, EventSourceFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&TreeModelLayout::editHandleEventSource),
        static_cast<FieldGetMethodSig >(&TreeModelLayout::getHandleEventSource));

    oType.addInitialDesc(pDesc);
}


TreeModelLayoutBase::TypeObject TreeModelLayoutBase::_type(
    TreeModelLayoutBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    NULL,
    TreeModelLayout::initMethod,
    TreeModelLayout::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TreeModelLayout::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"TreeModelLayout\"\n"
    "    parent=\"TreeRowMapper\"\n"
    "    library=\"ContribToolboxUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"abstract\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "A UI Tree Model Layout.\n"
    "    <Field\n"
    "        name=\"EventSource\"\n"
    "        type=\"TreeModelLayoutEventSource\"\n"
    "        category=\"pointer\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        defaultValue=\"NULL\"\n"
    "        access=\"public\"\n"
    "        >\n"
    "    </Field>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeCollapsed\"\n"
    "        detailsType=\"TreeModelLayoutEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeExpanded\"\n"
    "        detailsType=\"TreeModelLayoutEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeWillCollapse\"\n"
    "        detailsType=\"TreeModelLayoutEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeWillExpand\"\n"
    "        detailsType=\"TreeModelLayoutEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeNodesChanged\"\n"
    "        detailsType=\"TreeModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeNodesInserted\"\n"
    "        detailsType=\"TreeModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeNodesRemoved\"\n"
    "        detailsType=\"TreeModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeNodesWillBeRemoved\"\n"
    "        detailsType=\"TreeModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeStructureChanged\"\n"
    "        detailsType=\"TreeModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "</FieldContainer>\n",
    "A UI Tree Model Layout.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TreeModelLayoutBase::getType(void)
{
    return _type;
}

const FieldContainerType &TreeModelLayoutBase::getType(void) const
{
    return _type;
}

UInt32 TreeModelLayoutBase::getContainerSize(void) const
{
    return sizeof(TreeModelLayout);
}

/*------------------------- decorator get ------------------------------*/


//! Get the TreeModelLayout::_sfEventSource field.
const SFUnrecTreeModelLayoutEventSourcePtr *TreeModelLayoutBase::getSFEventSource(void) const
{
    return &_sfEventSource;
}

SFUnrecTreeModelLayoutEventSourcePtr *TreeModelLayoutBase::editSFEventSource    (void)
{
    editSField(EventSourceFieldMask);

    return &_sfEventSource;
}

//! Get the value of the TreeModelLayout::_sfEventSource field.
TreeModelLayoutEventSource * TreeModelLayoutBase::getEventSource(void) const
{
    return _sfEventSource.getValue();
}

//! Set the value of the TreeModelLayout::_sfEventSource field.
void TreeModelLayoutBase::setEventSource(TreeModelLayoutEventSource * const value)
{
    editSField(EventSourceFieldMask);

    _sfEventSource.setValue(value);
}






/*------------------------------ access -----------------------------------*/

SizeT TreeModelLayoutBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        returnValue += _sfEventSource.getBinSize();
    }

    return returnValue;
}

void TreeModelLayoutBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        _sfEventSource.copyToBin(pMem);
    }
}

void TreeModelLayoutBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        editSField(EventSourceFieldMask);
        _sfEventSource.copyFromBin(pMem);
    }
}




/*------------------------- constructors ----------------------------------*/

TreeModelLayoutBase::TreeModelLayoutBase(void) :
    Inherited(),
    _sfEventSource            (NULL)
{
}

TreeModelLayoutBase::TreeModelLayoutBase(const TreeModelLayoutBase &source) :
    Inherited(source),
    _sfEventSource            (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

TreeModelLayoutBase::~TreeModelLayoutBase(void)
{
}

void TreeModelLayoutBase::onCreate(const TreeModelLayout *source)
{
    Inherited::onCreate(source);

    if(source)
    {
        TreeModelLayout *pThis = static_cast<TreeModelLayout *>(this);

        pThis->setEventSource(source->getEventSource());
    }
    else
    {
        TreeModelLayoutEventSourceUnrecPtr evSrc = TreeModelLayoutEventSource::create();
        setEventSource( evSrc );
    }
}

GetFieldHandlePtr TreeModelLayoutBase::getHandleEventSource     (void) const
{
    SFUnrecTreeModelLayoutEventSourcePtr::GetHandlePtr returnValue(
        new  SFUnrecTreeModelLayoutEventSourcePtr::GetHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             const_cast<TreeModelLayoutBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr TreeModelLayoutBase::editHandleEventSource    (void)
{
    SFUnrecTreeModelLayoutEventSourcePtr::EditHandlePtr returnValue(
        new  SFUnrecTreeModelLayoutEventSourcePtr::EditHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&TreeModelLayout::setEventSource,
                    static_cast<TreeModelLayout *>(this), _1));

    editSField(EventSourceFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void TreeModelLayoutBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TreeModelLayout *pThis = static_cast<TreeModelLayout *>(this);

    pThis->execSync(static_cast<TreeModelLayout *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif



void TreeModelLayoutBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<TreeModelLayout *>(this)->setEventSource(NULL);


}


OSG_END_NAMESPACE
