/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTREEMODELLAYOUTFIELDS_H_
#define _OSGTREEMODELLAYOUTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TreeModelLayout;

OSG_GEN_CONTAINERPTR(TreeModelLayout);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<TreeModelLayout *, nsOSG> :
    public FieldTraitsFCPtrBase<TreeModelLayout *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TreeModelLayout *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TreeModelLayout *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTreeModelLayoutPtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelLayout *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTreeModelLayoutPtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelLayout *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTreeModelLayoutPtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelLayout *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTreeModelLayoutPtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelLayout *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTreeModelLayoutPtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelLayout *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTreeModelLayoutPtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelLayout *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTreeModelLayoutPtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelLayout *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTreeModelLayoutPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TreeModelLayout *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTreeModelLayoutPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TreeModelLayout *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTreeModelLayoutPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TreeModelLayout *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTreeModelLayoutPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TreeModelLayout *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTreeModelLayoutPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TreeModelLayout *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTreeModelLayoutPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TreeModelLayout *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTreeModelLayoutPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TreeModelLayout *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTreeModelLayoutPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TreeModelLayout *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTreeModelLayoutPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecTreeModelLayoutPtr : 
    public PointerSField<TreeModelLayout *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecTreeModelLayoutPtr : 
    public PointerSField<TreeModelLayout *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakTreeModelLayoutPtr :
    public PointerSField<TreeModelLayout *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedTreeModelLayoutPtr :
    public PointerSField<TreeModelLayout *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecTreeModelLayoutPtr :
    public PointerMField<TreeModelLayout *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecTreeModelLayoutPtr :
    public PointerMField<TreeModelLayout *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakTreeModelLayoutPtr :
    public PointerMField<TreeModelLayout *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedTreeModelLayoutPtr :
    public PointerMField<TreeModelLayout *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTREEMODELLAYOUTFIELDS_H_ */
