/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TreeModelLayout
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTREEMODELLAYOUTBASE_H_
#define _OSGTREEMODELLAYOUTBASE_H_
#ifdef __sgi
#pragma once
#endif


#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

//#include "OSGBaseTypes.h"

#include "OSGTreeRowMapper.h" // Parent

#include "OSGTreeModelLayoutEventSourceFields.h" // EventSource type

#include "OSGTreeModelLayoutFields.h"

#include "OSGTreeModelLayoutEventSource.h"

OSG_BEGIN_NAMESPACE


class TreeModelLayout;

//! \brief TreeModelLayout Base Class.

class OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING TreeModelLayoutBase : public TreeRowMapper
{
  public:

    typedef TreeRowMapper Inherited;
    typedef TreeRowMapper ParentContainer;

    typedef Inherited::TypeObject TypeObject;
    typedef TypeObject::InitPhase InitPhase;

    OSG_GEN_INTERNALPTR(TreeModelLayout);

    /*==========================  PUBLIC  =================================*/

  public:

    enum
    {
        EventSourceFieldId = Inherited::NextFieldId,
        NextFieldId = EventSourceFieldId + 1
    };

    static const OSG::BitVector EventSourceFieldMask =
        (TypeTraits<BitVector>::One << EventSourceFieldId);
    static const OSG::BitVector NextFieldMask =
        (TypeTraits<BitVector>::One << NextFieldId);
        
    typedef SFUnrecTreeModelLayoutEventSourcePtr SFEventSourceType;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static FieldContainerType &getClassType   (void);
    static UInt32              getClassTypeId (void);
    static UInt16              getClassGroupId(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType         (void);
    virtual const FieldContainerType &getType         (void) const;

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */

            const SFUnrecTreeModelLayoutEventSourcePtr *getSFEventSource    (void) const;
                  SFUnrecTreeModelLayoutEventSourcePtr *editSFEventSource    (void);


                  TreeModelLayoutEventSource * getEventSource    (void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

            void setEventSource    (TreeModelLayoutEventSource * const value);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr Field Set                                 */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr MField Set                                */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual SizeT  getBinSize (ConstFieldMaskArg  whichField);
    virtual void   copyToBin  (BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);
    virtual void   copyFromBin(BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);


    /*! \}                                                                 */
    /*! \}                                                                 */
    /*! \name                Event Forwards to EventSource                 */
    /*! \{                                                                 */
    
    //TreeCollapsed
    boost::signals2::connection connectTreeCollapsed  (const TreeModelLayoutEventSource::TreeCollapsedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    boost::signals2::connection connectTreeCollapsed  (const TreeModelLayoutEventSource::TreeCollapsedEventType::group_type &group,
                                                       const TreeModelLayoutEventSource::TreeCollapsedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    void   disconnectTreeCollapsed          (const TreeModelLayoutEventSource::TreeCollapsedEventType::group_type &group);
    void   disconnectAllSlotsTreeCollapsed  (void);
    bool   isEmptyTreeCollapsed             (void) const;
    UInt32 numSlotsTreeCollapsed            (void) const;
    
    //TreeExpanded
    boost::signals2::connection connectTreeExpanded   (const TreeModelLayoutEventSource::TreeExpandedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    boost::signals2::connection connectTreeExpanded   (const TreeModelLayoutEventSource::TreeExpandedEventType::group_type &group,
                                                       const TreeModelLayoutEventSource::TreeExpandedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    void   disconnectTreeExpanded           (const TreeModelLayoutEventSource::TreeExpandedEventType::group_type &group);
    void   disconnectAllSlotsTreeExpanded   (void);
    bool   isEmptyTreeExpanded              (void) const;
    UInt32 numSlotsTreeExpanded             (void) const;
    
    //TreeWillCollapse
    boost::signals2::connection connectTreeWillCollapse(const TreeModelLayoutEventSource::TreeWillCollapseEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    boost::signals2::connection connectTreeWillCollapse(const TreeModelLayoutEventSource::TreeWillCollapseEventType::group_type &group,
                                                       const TreeModelLayoutEventSource::TreeWillCollapseEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    void   disconnectTreeWillCollapse       (const TreeModelLayoutEventSource::TreeWillCollapseEventType::group_type &group);
    void   disconnectAllSlotsTreeWillCollapse(void);
    bool   isEmptyTreeWillCollapse          (void) const;
    UInt32 numSlotsTreeWillCollapse         (void) const;
    
    //TreeWillExpand
    boost::signals2::connection connectTreeWillExpand (const TreeModelLayoutEventSource::TreeWillExpandEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    boost::signals2::connection connectTreeWillExpand (const TreeModelLayoutEventSource::TreeWillExpandEventType::group_type &group,
                                                       const TreeModelLayoutEventSource::TreeWillExpandEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    void   disconnectTreeWillExpand         (const TreeModelLayoutEventSource::TreeWillExpandEventType::group_type &group);
    void   disconnectAllSlotsTreeWillExpand (void);
    bool   isEmptyTreeWillExpand            (void) const;
    UInt32 numSlotsTreeWillExpand           (void) const;
    
    //TreeNodesChanged
    boost::signals2::connection connectTreeNodesChanged(const TreeModelLayoutEventSource::TreeNodesChangedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    boost::signals2::connection connectTreeNodesChanged(const TreeModelLayoutEventSource::TreeNodesChangedEventType::group_type &group,
                                                       const TreeModelLayoutEventSource::TreeNodesChangedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    void   disconnectTreeNodesChanged       (const TreeModelLayoutEventSource::TreeNodesChangedEventType::group_type &group);
    void   disconnectAllSlotsTreeNodesChanged(void);
    bool   isEmptyTreeNodesChanged          (void) const;
    UInt32 numSlotsTreeNodesChanged         (void) const;
    
    //TreeNodesInserted
    boost::signals2::connection connectTreeNodesInserted(const TreeModelLayoutEventSource::TreeNodesInsertedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    boost::signals2::connection connectTreeNodesInserted(const TreeModelLayoutEventSource::TreeNodesInsertedEventType::group_type &group,
                                                       const TreeModelLayoutEventSource::TreeNodesInsertedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    void   disconnectTreeNodesInserted      (const TreeModelLayoutEventSource::TreeNodesInsertedEventType::group_type &group);
    void   disconnectAllSlotsTreeNodesInserted(void);
    bool   isEmptyTreeNodesInserted         (void) const;
    UInt32 numSlotsTreeNodesInserted        (void) const;
    
    //TreeNodesRemoved
    boost::signals2::connection connectTreeNodesRemoved(const TreeModelLayoutEventSource::TreeNodesRemovedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    boost::signals2::connection connectTreeNodesRemoved(const TreeModelLayoutEventSource::TreeNodesRemovedEventType::group_type &group,
                                                       const TreeModelLayoutEventSource::TreeNodesRemovedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    void   disconnectTreeNodesRemoved       (const TreeModelLayoutEventSource::TreeNodesRemovedEventType::group_type &group);
    void   disconnectAllSlotsTreeNodesRemoved(void);
    bool   isEmptyTreeNodesRemoved          (void) const;
    UInt32 numSlotsTreeNodesRemoved         (void) const;
    
    //TreeNodesWillBeRemoved
    boost::signals2::connection connectTreeNodesWillBeRemoved(const TreeModelLayoutEventSource::TreeNodesWillBeRemovedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    boost::signals2::connection connectTreeNodesWillBeRemoved(const TreeModelLayoutEventSource::TreeNodesWillBeRemovedEventType::group_type &group,
                                                       const TreeModelLayoutEventSource::TreeNodesWillBeRemovedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    void   disconnectTreeNodesWillBeRemoved (const TreeModelLayoutEventSource::TreeNodesWillBeRemovedEventType::group_type &group);
    void   disconnectAllSlotsTreeNodesWillBeRemoved(void);
    bool   isEmptyTreeNodesWillBeRemoved    (void) const;
    UInt32 numSlotsTreeNodesWillBeRemoved   (void) const;
    
    //TreeStructureChanged
    boost::signals2::connection connectTreeStructureChanged(const TreeModelLayoutEventSource::TreeStructureChangedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    boost::signals2::connection connectTreeStructureChanged(const TreeModelLayoutEventSource::TreeStructureChangedEventType::group_type &group,
                                                       const TreeModelLayoutEventSource::TreeStructureChangedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    void   disconnectTreeStructureChanged   (const TreeModelLayoutEventSource::TreeStructureChangedEventType::group_type &group);
    void   disconnectAllSlotsTreeStructureChanged(void);
    bool   isEmptyTreeStructureChanged      (void) const;
    UInt32 numSlotsTreeStructureChanged     (void) const;
    
    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/

  protected:

    static TypeObject _type;

    static       void   classDescInserter(TypeObject &oType);
    static const Char8 *getClassname     (void             );

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    SFUnrecTreeModelLayoutEventSourcePtr _sfEventSource;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    TreeModelLayoutBase(void);
    TreeModelLayoutBase(const TreeModelLayoutBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~TreeModelLayoutBase(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     onCreate                                */
    /*! \{                                                                 */

    void onCreate(const TreeModelLayout *source = NULL);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Generic Field Access                      */
    /*! \{                                                                 */

    GetFieldHandlePtr  getHandleEventSource     (void) const;
    EditFieldHandlePtr editHandleEventSource    (void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual void execSyncV(      FieldContainer    &oFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);

            void execSync (      TreeModelLayoutBase *pFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     Aspect Create                            */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */
    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    virtual void resolveLinks(void);

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/

  private:
    /*---------------------------------------------------------------------*/

    // prohibit default functions (move to 'public' if you need one)
    void operator =(const TreeModelLayoutBase &source);
};

typedef TreeModelLayoutBase *TreeModelLayoutBaseP;

OSG_END_NAMESPACE

#endif /* _OSGTREEMODELLAYOUTBASE_H_ */
