/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTREEMODELLAYOUTEVENTSOURCEFIELDS_H_
#define _OSGTREEMODELLAYOUTEVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TreeModelLayoutEventSource;

OSG_GEN_CONTAINERPTR(TreeModelLayoutEventSource);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<TreeModelLayoutEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<TreeModelLayoutEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TreeModelLayoutEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TreeModelLayoutEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTreeModelLayoutEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelLayoutEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTreeModelLayoutEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelLayoutEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTreeModelLayoutEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelLayoutEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTreeModelLayoutEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelLayoutEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTreeModelLayoutEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelLayoutEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTreeModelLayoutEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelLayoutEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTreeModelLayoutEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelLayoutEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTreeModelLayoutEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TreeModelLayoutEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTreeModelLayoutEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TreeModelLayoutEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTreeModelLayoutEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TreeModelLayoutEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTreeModelLayoutEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TreeModelLayoutEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTreeModelLayoutEventSourcePtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TreeModelLayoutEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTreeModelLayoutEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TreeModelLayoutEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTreeModelLayoutEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TreeModelLayoutEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTreeModelLayoutEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TreeModelLayoutEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTreeModelLayoutEventSourcePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecTreeModelLayoutEventSourcePtr : 
    public PointerSField<TreeModelLayoutEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecTreeModelLayoutEventSourcePtr : 
    public PointerSField<TreeModelLayoutEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakTreeModelLayoutEventSourcePtr :
    public PointerSField<TreeModelLayoutEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedTreeModelLayoutEventSourcePtr :
    public PointerSField<TreeModelLayoutEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecTreeModelLayoutEventSourcePtr :
    public PointerMField<TreeModelLayoutEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecTreeModelLayoutEventSourcePtr :
    public PointerMField<TreeModelLayoutEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakTreeModelLayoutEventSourcePtr :
    public PointerMField<TreeModelLayoutEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedTreeModelLayoutEventSourcePtr :
    public PointerMField<TreeModelLayoutEventSource *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTREEMODELLAYOUTEventSourceFIELDS_H_ */
