/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TreeModelLayout!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"



#include "OSGTreeModelLayoutEventSource.h" // EventSource Class

#include "OSGTreeModelLayoutBase.h"
#include "OSGTreeModelLayout.h"
#include "OSGTreeModelLayoutEventSource.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TreeModelLayout
    A UI Tree Model Layout.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var TreeModelLayoutEventSource * TreeModelLayoutBase::_sfEventSource
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<TreeModelLayout *, nsOSG>::_type(
    "TreeModelLayoutPtr", 
    "TreeRowMapperPtr", 
    TreeModelLayout::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(TreeModelLayout *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TreeModelLayout *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TreeModelLayout *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TreeModelLayoutBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecTreeModelLayoutEventSourcePtr::Description(
        SFUnrecTreeModelLayoutEventSourcePtr::getClassType(),
        "EventSource",
        "",
        EventSourceFieldId, EventSourceFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&TreeModelLayout::editHandleEventSource),
        static_cast<FieldGetMethodSig >(&TreeModelLayout::getHandleEventSource));

    oType.addInitialDesc(pDesc);
}


TreeModelLayoutBase::TypeObject TreeModelLayoutBase::_type(
    TreeModelLayoutBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    NULL,
    TreeModelLayout::initMethod,
    TreeModelLayout::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TreeModelLayout::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"TreeModelLayout\"\n"
    "    parent=\"TreeRowMapper\"\n"
    "    library=\"ContribToolboxUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"abstract\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "A UI Tree Model Layout.\n"
    "    <Field\n"
    "        name=\"EventSource\"\n"
    "        type=\"TreeModelLayoutEventSource\"\n"
    "        category=\"pointer\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        defaultValue=\"NULL\"\n"
    "        access=\"public\"\n"
    "        >\n"
    "    </Field>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeCollapsed\"\n"
    "        detailsType=\"TreeModelLayoutEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeExpanded\"\n"
    "        detailsType=\"TreeModelLayoutEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeWillCollapse\"\n"
    "        detailsType=\"TreeModelLayoutEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeWillExpand\"\n"
    "        detailsType=\"TreeModelLayoutEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeNodesChanged\"\n"
    "        detailsType=\"TreeModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeNodesInserted\"\n"
    "        detailsType=\"TreeModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeNodesRemoved\"\n"
    "        detailsType=\"TreeModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeNodesWillBeRemoved\"\n"
    "        detailsType=\"TreeModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeStructureChanged\"\n"
    "        detailsType=\"TreeModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "</FieldContainer>\n",
    "A UI Tree Model Layout.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TreeModelLayoutBase::getType(void)
{
    return _type;
}

const FieldContainerType &TreeModelLayoutBase::getType(void) const
{
    return _type;
}

UInt32 TreeModelLayoutBase::getContainerSize(void) const
{
    return sizeof(TreeModelLayout);
}

/*------------------------- decorator get ------------------------------*/


//! Get the TreeModelLayout::_sfEventSource field.
const SFUnrecTreeModelLayoutEventSourcePtr *TreeModelLayoutBase::getSFEventSource(void) const
{
    return &_sfEventSource;
}

SFUnrecTreeModelLayoutEventSourcePtr *TreeModelLayoutBase::editSFEventSource    (void)
{
    editSField(EventSourceFieldMask);

    return &_sfEventSource;
}






/*------------------------------ access -----------------------------------*/

SizeT TreeModelLayoutBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        returnValue += _sfEventSource.getBinSize();
    }

    return returnValue;
}

void TreeModelLayoutBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        _sfEventSource.copyToBin(pMem);
    }
}

void TreeModelLayoutBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        editSField(EventSourceFieldMask);
        _sfEventSource.copyFromBin(pMem);
    }
}




/*------------------------- constructors ----------------------------------*/

TreeModelLayoutBase::TreeModelLayoutBase(void) :
    Inherited(),
    _sfEventSource            (NULL)
{
}

TreeModelLayoutBase::TreeModelLayoutBase(const TreeModelLayoutBase &source) :
    Inherited(source),
    _sfEventSource            (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

TreeModelLayoutBase::~TreeModelLayoutBase(void)
{
}

void TreeModelLayoutBase::onCreate(const TreeModelLayout *source)
{
    Inherited::onCreate(source);

    if(source)
    {
        TreeModelLayout *pThis = static_cast<TreeModelLayout *>(this);

        pThis->setEventSource(source->getEventSource());
    }
    
    {
        TreeModelLayoutEventSourceUnrecPtr evSrc = TreeModelLayoutEventSource::create();
        setEventSource( evSrc );
    }
}

GetFieldHandlePtr TreeModelLayoutBase::getHandleEventSource     (void) const
{
    SFUnrecTreeModelLayoutEventSourcePtr::GetHandlePtr returnValue(
        new  SFUnrecTreeModelLayoutEventSourcePtr::GetHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             const_cast<TreeModelLayoutBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr TreeModelLayoutBase::editHandleEventSource    (void)
{
    SFUnrecTreeModelLayoutEventSourcePtr::EditHandlePtr returnValue(
        new  SFUnrecTreeModelLayoutEventSourcePtr::EditHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&TreeModelLayout::setEventSource,
                    static_cast<TreeModelLayout *>(this), _1));

    editSField(EventSourceFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void TreeModelLayoutBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TreeModelLayout *pThis = static_cast<TreeModelLayout *>(this);

    pThis->execSync(static_cast<TreeModelLayout *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif



void TreeModelLayoutBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<TreeModelLayout *>(this)->setEventSource(NULL);


}


boost::signals2::connection  TreeModelLayoutBase::connectTreeCollapsed(
                                                    const TreeModelLayoutEventSource::TreeCollapsedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeCollapsed( listener, at );
}

boost::signals2::connection  TreeModelLayoutBase::connectTreeCollapsed(
                                                    const TreeModelLayoutEventSource::TreeCollapsedEventType::group_type &group,
                                                    const TreeModelLayoutEventSource::TreeCollapsedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeCollapsed( group, listener, at );
}

void  TreeModelLayoutBase::disconnectTreeCollapsed(
                                                    const TreeModelLayoutEventSource::TreeCollapsedEventType::group_type &group
)
{
    getEventSource()->disconnectTreeCollapsed( group );
}

void  TreeModelLayoutBase::disconnectAllSlotsTreeCollapsed(void)
{
    getEventSource()->disconnectAllSlotsTreeCollapsed();
}

bool  TreeModelLayoutBase::isEmptyTreeCollapsed(void) const
{
    return getEventSource()->isEmptyTreeCollapsed();
}

UInt32  TreeModelLayoutBase::numSlotsTreeCollapsed(void) const
{
    return getEventSource()->numSlotsTreeCollapsed();
}

boost::signals2::connection  TreeModelLayoutBase::connectTreeExpanded(
                                                    const TreeModelLayoutEventSource::TreeExpandedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeExpanded( listener, at );
}

boost::signals2::connection  TreeModelLayoutBase::connectTreeExpanded(
                                                    const TreeModelLayoutEventSource::TreeExpandedEventType::group_type &group,
                                                    const TreeModelLayoutEventSource::TreeExpandedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeExpanded( group, listener, at );
}

void  TreeModelLayoutBase::disconnectTreeExpanded(
                                                    const TreeModelLayoutEventSource::TreeExpandedEventType::group_type &group
)
{
    getEventSource()->disconnectTreeExpanded( group );
}

void  TreeModelLayoutBase::disconnectAllSlotsTreeExpanded(void)
{
    getEventSource()->disconnectAllSlotsTreeExpanded();
}

bool  TreeModelLayoutBase::isEmptyTreeExpanded(void) const
{
    return getEventSource()->isEmptyTreeExpanded();
}

UInt32  TreeModelLayoutBase::numSlotsTreeExpanded(void) const
{
    return getEventSource()->numSlotsTreeExpanded();
}

boost::signals2::connection  TreeModelLayoutBase::connectTreeWillCollapse(
                                                    const TreeModelLayoutEventSource::TreeWillCollapseEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeWillCollapse( listener, at );
}

boost::signals2::connection  TreeModelLayoutBase::connectTreeWillCollapse(
                                                    const TreeModelLayoutEventSource::TreeWillCollapseEventType::group_type &group,
                                                    const TreeModelLayoutEventSource::TreeWillCollapseEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeWillCollapse( group, listener, at );
}

void  TreeModelLayoutBase::disconnectTreeWillCollapse(
                                                    const TreeModelLayoutEventSource::TreeWillCollapseEventType::group_type &group
)
{
    getEventSource()->disconnectTreeWillCollapse( group );
}

void  TreeModelLayoutBase::disconnectAllSlotsTreeWillCollapse(void)
{
    getEventSource()->disconnectAllSlotsTreeWillCollapse();
}

bool  TreeModelLayoutBase::isEmptyTreeWillCollapse(void) const
{
    return getEventSource()->isEmptyTreeWillCollapse();
}

UInt32  TreeModelLayoutBase::numSlotsTreeWillCollapse(void) const
{
    return getEventSource()->numSlotsTreeWillCollapse();
}

boost::signals2::connection  TreeModelLayoutBase::connectTreeWillExpand(
                                                    const TreeModelLayoutEventSource::TreeWillExpandEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeWillExpand( listener, at );
}

boost::signals2::connection  TreeModelLayoutBase::connectTreeWillExpand(
                                                    const TreeModelLayoutEventSource::TreeWillExpandEventType::group_type &group,
                                                    const TreeModelLayoutEventSource::TreeWillExpandEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeWillExpand( group, listener, at );
}

void  TreeModelLayoutBase::disconnectTreeWillExpand(
                                                    const TreeModelLayoutEventSource::TreeWillExpandEventType::group_type &group
)
{
    getEventSource()->disconnectTreeWillExpand( group );
}

void  TreeModelLayoutBase::disconnectAllSlotsTreeWillExpand(void)
{
    getEventSource()->disconnectAllSlotsTreeWillExpand();
}

bool  TreeModelLayoutBase::isEmptyTreeWillExpand(void) const
{
    return getEventSource()->isEmptyTreeWillExpand();
}

UInt32  TreeModelLayoutBase::numSlotsTreeWillExpand(void) const
{
    return getEventSource()->numSlotsTreeWillExpand();
}

boost::signals2::connection  TreeModelLayoutBase::connectTreeNodesChanged(
                                                    const TreeModelLayoutEventSource::TreeNodesChangedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeNodesChanged( listener, at );
}

boost::signals2::connection  TreeModelLayoutBase::connectTreeNodesChanged(
                                                    const TreeModelLayoutEventSource::TreeNodesChangedEventType::group_type &group,
                                                    const TreeModelLayoutEventSource::TreeNodesChangedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeNodesChanged( group, listener, at );
}

void  TreeModelLayoutBase::disconnectTreeNodesChanged(
                                                    const TreeModelLayoutEventSource::TreeNodesChangedEventType::group_type &group
)
{
    getEventSource()->disconnectTreeNodesChanged( group );
}

void  TreeModelLayoutBase::disconnectAllSlotsTreeNodesChanged(void)
{
    getEventSource()->disconnectAllSlotsTreeNodesChanged();
}

bool  TreeModelLayoutBase::isEmptyTreeNodesChanged(void) const
{
    return getEventSource()->isEmptyTreeNodesChanged();
}

UInt32  TreeModelLayoutBase::numSlotsTreeNodesChanged(void) const
{
    return getEventSource()->numSlotsTreeNodesChanged();
}

boost::signals2::connection  TreeModelLayoutBase::connectTreeNodesInserted(
                                                    const TreeModelLayoutEventSource::TreeNodesInsertedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeNodesInserted( listener, at );
}

boost::signals2::connection  TreeModelLayoutBase::connectTreeNodesInserted(
                                                    const TreeModelLayoutEventSource::TreeNodesInsertedEventType::group_type &group,
                                                    const TreeModelLayoutEventSource::TreeNodesInsertedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeNodesInserted( group, listener, at );
}

void  TreeModelLayoutBase::disconnectTreeNodesInserted(
                                                    const TreeModelLayoutEventSource::TreeNodesInsertedEventType::group_type &group
)
{
    getEventSource()->disconnectTreeNodesInserted( group );
}

void  TreeModelLayoutBase::disconnectAllSlotsTreeNodesInserted(void)
{
    getEventSource()->disconnectAllSlotsTreeNodesInserted();
}

bool  TreeModelLayoutBase::isEmptyTreeNodesInserted(void) const
{
    return getEventSource()->isEmptyTreeNodesInserted();
}

UInt32  TreeModelLayoutBase::numSlotsTreeNodesInserted(void) const
{
    return getEventSource()->numSlotsTreeNodesInserted();
}

boost::signals2::connection  TreeModelLayoutBase::connectTreeNodesRemoved(
                                                    const TreeModelLayoutEventSource::TreeNodesRemovedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeNodesRemoved( listener, at );
}

boost::signals2::connection  TreeModelLayoutBase::connectTreeNodesRemoved(
                                                    const TreeModelLayoutEventSource::TreeNodesRemovedEventType::group_type &group,
                                                    const TreeModelLayoutEventSource::TreeNodesRemovedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeNodesRemoved( group, listener, at );
}

void  TreeModelLayoutBase::disconnectTreeNodesRemoved(
                                                    const TreeModelLayoutEventSource::TreeNodesRemovedEventType::group_type &group
)
{
    getEventSource()->disconnectTreeNodesRemoved( group );
}

void  TreeModelLayoutBase::disconnectAllSlotsTreeNodesRemoved(void)
{
    getEventSource()->disconnectAllSlotsTreeNodesRemoved();
}

bool  TreeModelLayoutBase::isEmptyTreeNodesRemoved(void) const
{
    return getEventSource()->isEmptyTreeNodesRemoved();
}

UInt32  TreeModelLayoutBase::numSlotsTreeNodesRemoved(void) const
{
    return getEventSource()->numSlotsTreeNodesRemoved();
}

boost::signals2::connection  TreeModelLayoutBase::connectTreeNodesWillBeRemoved(
                                                    const TreeModelLayoutEventSource::TreeNodesWillBeRemovedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeNodesWillBeRemoved( listener, at );
}

boost::signals2::connection  TreeModelLayoutBase::connectTreeNodesWillBeRemoved(
                                                    const TreeModelLayoutEventSource::TreeNodesWillBeRemovedEventType::group_type &group,
                                                    const TreeModelLayoutEventSource::TreeNodesWillBeRemovedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeNodesWillBeRemoved( group, listener, at );
}

void  TreeModelLayoutBase::disconnectTreeNodesWillBeRemoved(
                                                    const TreeModelLayoutEventSource::TreeNodesWillBeRemovedEventType::group_type &group
)
{
    getEventSource()->disconnectTreeNodesWillBeRemoved( group );
}

void  TreeModelLayoutBase::disconnectAllSlotsTreeNodesWillBeRemoved(void)
{
    getEventSource()->disconnectAllSlotsTreeNodesWillBeRemoved();
}

bool  TreeModelLayoutBase::isEmptyTreeNodesWillBeRemoved(void) const
{
    return getEventSource()->isEmptyTreeNodesWillBeRemoved();
}

UInt32  TreeModelLayoutBase::numSlotsTreeNodesWillBeRemoved(void) const
{
    return getEventSource()->numSlotsTreeNodesWillBeRemoved();
}

boost::signals2::connection  TreeModelLayoutBase::connectTreeStructureChanged(
                                                    const TreeModelLayoutEventSource::TreeStructureChangedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeStructureChanged( listener, at );
}

boost::signals2::connection  TreeModelLayoutBase::connectTreeStructureChanged(
                                                    const TreeModelLayoutEventSource::TreeStructureChangedEventType::group_type &group,
                                                    const TreeModelLayoutEventSource::TreeStructureChangedEventType::slot_type &listener, 
                                                    boost::signals2::connect_position at)
{
    return getEventSource()->connectTreeStructureChanged( group, listener, at );
}

void  TreeModelLayoutBase::disconnectTreeStructureChanged(
                                                    const TreeModelLayoutEventSource::TreeStructureChangedEventType::group_type &group
)
{
    getEventSource()->disconnectTreeStructureChanged( group );
}

void  TreeModelLayoutBase::disconnectAllSlotsTreeStructureChanged(void)
{
    getEventSource()->disconnectAllSlotsTreeStructureChanged();
}

bool  TreeModelLayoutBase::isEmptyTreeStructureChanged(void) const
{
    return getEventSource()->isEmptyTreeStructureChanged();
}

UInt32  TreeModelLayoutBase::numSlotsTreeStructureChanged(void) const
{
    return getEventSource()->numSlotsTreeStructureChanged();
}

OSG_END_NAMESPACE
