/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TreeModelLayoutEventSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"


#include "OSGTreeModelLayoutEventSourceBase.h"
#include "OSGTreeModelLayoutEventSource.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TreeModelLayoutEventSource
    A UI Tree Model Layout.
 */



/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<TreeModelLayoutEventSource *, nsOSG>::_type(
    "TreeModelLayoutEventSourcePtr",
    "EventContainerPtr",
    TreeModelLayoutEventSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(TreeModelLayoutEventSource *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TreeModelLayoutEventSource *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TreeModelLayoutEventSource *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TreeModelLayoutEventSourceBase::classDescInserter(TypeObject &oType)
{
}


TreeModelLayoutEventSourceBase::TypeObject TreeModelLayoutEventSourceBase::_type(
    TreeModelLayoutEventSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&TreeModelLayoutEventSourceBase::createEmptyLocal),
    TreeModelLayoutEventSource::initMethod,
    TreeModelLayoutEventSource::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TreeModelLayoutEventSource::classDescInserter),
    false,
    0,
    "",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TreeModelLayoutEventSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &TreeModelLayoutEventSourceBase::getType(void) const
{
    return _type;
}

UInt32 TreeModelLayoutEventSourceBase::getContainerSize(void) const
{
    return sizeof(TreeModelLayoutEventSource);
}



/*------------------------------ access -----------------------------------*/

SizeT TreeModelLayoutEventSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    return returnValue;
}

void TreeModelLayoutEventSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);
}

void TreeModelLayoutEventSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);
}

//! create a new instance of the class
TreeModelLayoutEventSourceTransitPtr TreeModelLayoutEventSourceBase::createLocal(BitVector bFlags)
{
    TreeModelLayoutEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<TreeModelLayoutEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
TreeModelLayoutEventSourceTransitPtr TreeModelLayoutEventSourceBase::createDependent(BitVector bFlags)
{
    TreeModelLayoutEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<TreeModelLayoutEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
TreeModelLayoutEventSourceTransitPtr TreeModelLayoutEventSourceBase::create(void)
{
    TreeModelLayoutEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<TreeModelLayoutEventSource>(tmpPtr);
    }

    return fc;
}

TreeModelLayoutEventSource *TreeModelLayoutEventSourceBase::createEmptyLocal(BitVector bFlags)
{
    TreeModelLayoutEventSource *returnValue;

    newPtr<TreeModelLayoutEventSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
TreeModelLayoutEventSource *TreeModelLayoutEventSourceBase::createEmpty(void)
{
    TreeModelLayoutEventSource *returnValue;

    newPtr<TreeModelLayoutEventSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr TreeModelLayoutEventSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    TreeModelLayoutEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TreeModelLayoutEventSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr TreeModelLayoutEventSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    TreeModelLayoutEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TreeModelLayoutEventSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr TreeModelLayoutEventSourceBase::shallowCopy(void) const
{
    TreeModelLayoutEventSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const TreeModelLayoutEventSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

TreeModelLayoutEventSourceBase::TreeModelLayoutEventSourceBase(void) :
    Inherited()
{
}

TreeModelLayoutEventSourceBase::TreeModelLayoutEventSourceBase(const TreeModelLayoutEventSourceBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

TreeModelLayoutEventSourceBase::~TreeModelLayoutEventSourceBase(void)
{
}


#ifdef OSG_MT_CPTR_ASPECT
void TreeModelLayoutEventSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TreeModelLayoutEventSource *pThis = static_cast<TreeModelLayoutEventSource *>(this);

    pThis->execSync(static_cast<TreeModelLayoutEventSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *TreeModelLayoutEventSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    TreeModelLayoutEventSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const TreeModelLayoutEventSource *>(pRefAspect),
                  dynamic_cast<const TreeModelLayoutEventSource *>(this));

    return returnValue;
}
#endif

void TreeModelLayoutEventSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();

}

OSG_END_NAMESPACE
