/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ColorSelectionModel!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"



#include "OSGColorSelectionModelEventSource.h" // EventSource Class

#include "OSGColorSelectionModelBase.h"
#include "OSGColorSelectionModel.h"
#include "OSGColorSelectionModelEventSource.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::ColorSelectionModel
    A UI ColorSelectionModel.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var ColorSelectionModelEventSource * ColorSelectionModelBase::_sfEventSource
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<ColorSelectionModel *, nsOSG>::_type(
    "ColorSelectionModelPtr", 
    "AttachmentContainerPtr", 
    ColorSelectionModel::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(ColorSelectionModel *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           ColorSelectionModel *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           ColorSelectionModel *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void ColorSelectionModelBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecColorSelectionModelEventSourcePtr::Description(
        SFUnrecColorSelectionModelEventSourcePtr::getClassType(),
        "EventSource",
        "",
        EventSourceFieldId, EventSourceFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&ColorSelectionModel::editHandleEventSource),
        static_cast<FieldGetMethodSig >(&ColorSelectionModel::getHandleEventSource));

    oType.addInitialDesc(pDesc);
}


ColorSelectionModelBase::TypeObject ColorSelectionModelBase::_type(
    ColorSelectionModelBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    NULL,
    ColorSelectionModel::initMethod,
    ColorSelectionModel::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&ColorSelectionModel::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"ColorSelectionModel\"\n"
    "    parent=\"AttachmentContainer\"\n"
    "    library=\"ContribToolboxUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"abstract\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "A UI ColorSelectionModel.\n"
    "\t<Field\n"
    "        name=\"EventSource\"\n"
    "        type=\"ColorSelectionModelEventSource\"\n"
    "        category=\"pointer\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        access=\"public\"\n"
    "        defaultValue=\"NULL\"\t\n"
    "\t>\n"
    "\t</Field>\n"
    "    <ProducedEvent\n"
    "        name=\"StateChanged\"\n"
    "        detailsType=\"ChangeEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "</FieldContainer>\n",
    "A UI ColorSelectionModel.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &ColorSelectionModelBase::getType(void)
{
    return _type;
}

const FieldContainerType &ColorSelectionModelBase::getType(void) const
{
    return _type;
}

UInt32 ColorSelectionModelBase::getContainerSize(void) const
{
    return sizeof(ColorSelectionModel);
}

/*------------------------- decorator get ------------------------------*/


//! Get the ColorSelectionModel::_sfEventSource field.
const SFUnrecColorSelectionModelEventSourcePtr *ColorSelectionModelBase::getSFEventSource(void) const
{
    return &_sfEventSource;
}

SFUnrecColorSelectionModelEventSourcePtr *ColorSelectionModelBase::editSFEventSource    (void)
{
    editSField(EventSourceFieldMask);

    return &_sfEventSource;
}






/*------------------------------ access -----------------------------------*/

SizeT ColorSelectionModelBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        returnValue += _sfEventSource.getBinSize();
    }

    return returnValue;
}

void ColorSelectionModelBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        _sfEventSource.copyToBin(pMem);
    }
}

void ColorSelectionModelBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        editSField(EventSourceFieldMask);
        _sfEventSource.copyFromBin(pMem);
    }
}




/*------------------------- constructors ----------------------------------*/

ColorSelectionModelBase::ColorSelectionModelBase(void) :
    Inherited(),
    _sfEventSource            (NULL)
{
}

ColorSelectionModelBase::ColorSelectionModelBase(const ColorSelectionModelBase &source) :
    Inherited(source),
    _sfEventSource            (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

ColorSelectionModelBase::~ColorSelectionModelBase(void)
{
}

void ColorSelectionModelBase::onCreate(const ColorSelectionModel *source)
{
    Inherited::onCreate(source);

    if(source)
    {
        ColorSelectionModel *pThis = static_cast<ColorSelectionModel *>(this);

        pThis->setEventSource(source->getEventSource());
    }
    
    {
        ColorSelectionModelEventSourceUnrecPtr evSrc = ColorSelectionModelEventSource::create();
        setEventSource( evSrc );
    }
}

GetFieldHandlePtr ColorSelectionModelBase::getHandleEventSource     (void) const
{
    SFUnrecColorSelectionModelEventSourcePtr::GetHandlePtr returnValue(
        new  SFUnrecColorSelectionModelEventSourcePtr::GetHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             const_cast<ColorSelectionModelBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr ColorSelectionModelBase::editHandleEventSource    (void)
{
    SFUnrecColorSelectionModelEventSourcePtr::EditHandlePtr returnValue(
        new  SFUnrecColorSelectionModelEventSourcePtr::EditHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&ColorSelectionModel::setEventSource,
                    static_cast<ColorSelectionModel *>(this), _1));

    editSField(EventSourceFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void ColorSelectionModelBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    ColorSelectionModel *pThis = static_cast<ColorSelectionModel *>(this);

    pThis->execSync(static_cast<ColorSelectionModel *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif



void ColorSelectionModelBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<ColorSelectionModel *>(this)->setEventSource(NULL);


}


OSG_END_NAMESPACE
