/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCOLORSELECTIONMODELFIELDS_H_
#define _OSGCOLORSELECTIONMODELFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class ColorSelectionModel;

OSG_GEN_CONTAINERPTR(ColorSelectionModel);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<ColorSelectionModel *, nsOSG> :
    public FieldTraitsFCPtrBase<ColorSelectionModel *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<ColorSelectionModel *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<ColorSelectionModel *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecColorSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ColorSelectionModel *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecColorSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ColorSelectionModel *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakColorSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ColorSelectionModel *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdColorSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ColorSelectionModel *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecColorSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ColorSelectionModel *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecColorSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ColorSelectionModel *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakColorSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ColorSelectionModel *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdColorSelectionModelPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ColorSelectionModel *,
                      RecordedRefCountPolicy, nsOSG  > SFRecColorSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ColorSelectionModel *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecColorSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ColorSelectionModel *,
                      WeakRefCountPolicy, nsOSG      > SFWeakColorSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ColorSelectionModel *,
                      NoRefCountPolicy, nsOSG        > SFUncountedColorSelectionModelPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ColorSelectionModel *,
                      RecordedRefCountPolicy, nsOSG  > MFRecColorSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ColorSelectionModel *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecColorSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ColorSelectionModel *,
                      WeakRefCountPolicy, nsOSG      > MFWeakColorSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ColorSelectionModel *,
                      NoRefCountPolicy, nsOSG        > MFUncountedColorSelectionModelPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecColorSelectionModelPtr : 
    public PointerSField<ColorSelectionModel *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecColorSelectionModelPtr : 
    public PointerSField<ColorSelectionModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakColorSelectionModelPtr :
    public PointerSField<ColorSelectionModel *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedColorSelectionModelPtr :
    public PointerSField<ColorSelectionModel *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecColorSelectionModelPtr :
    public PointerMField<ColorSelectionModel *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecColorSelectionModelPtr :
    public PointerMField<ColorSelectionModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakColorSelectionModelPtr :
    public PointerMField<ColorSelectionModel *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedColorSelectionModelPtr :
    public PointerMField<ColorSelectionModel *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGCOLORSELECTIONMODELFIELDS_H_ */
