/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ColorSelectionModelEventSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"


#include "OSGColorSelectionModelEventSourceBase.h"
#include "OSGColorSelectionModelEventSource.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::ColorSelectionModelEventSource
    A UI ColorSelectionModel.
 */



/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<ColorSelectionModelEventSource *, nsOSG>::_type(
    "ColorSelectionModelEventSourcePtr",
    "EventContainerPtr",
    ColorSelectionModelEventSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(ColorSelectionModelEventSource *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           ColorSelectionModelEventSource *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           ColorSelectionModelEventSource *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void ColorSelectionModelEventSourceBase::classDescInserter(TypeObject &oType)
{
}


ColorSelectionModelEventSourceBase::TypeObject ColorSelectionModelEventSourceBase::_type(
    ColorSelectionModelEventSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&ColorSelectionModelEventSourceBase::createEmptyLocal),
    ColorSelectionModelEventSource::initMethod,
    ColorSelectionModelEventSource::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&ColorSelectionModelEventSource::classDescInserter),
    false,
    0,
    "",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &ColorSelectionModelEventSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &ColorSelectionModelEventSourceBase::getType(void) const
{
    return _type;
}

UInt32 ColorSelectionModelEventSourceBase::getContainerSize(void) const
{
    return sizeof(ColorSelectionModelEventSource);
}



/*------------------------------ access -----------------------------------*/

SizeT ColorSelectionModelEventSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    return returnValue;
}

void ColorSelectionModelEventSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);
}

void ColorSelectionModelEventSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);
}

//! create a new instance of the class
ColorSelectionModelEventSourceTransitPtr ColorSelectionModelEventSourceBase::createLocal(BitVector bFlags)
{
    ColorSelectionModelEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<ColorSelectionModelEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
ColorSelectionModelEventSourceTransitPtr ColorSelectionModelEventSourceBase::createDependent(BitVector bFlags)
{
    ColorSelectionModelEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<ColorSelectionModelEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
ColorSelectionModelEventSourceTransitPtr ColorSelectionModelEventSourceBase::create(void)
{
    ColorSelectionModelEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<ColorSelectionModelEventSource>(tmpPtr);
    }

    return fc;
}

ColorSelectionModelEventSource *ColorSelectionModelEventSourceBase::createEmptyLocal(BitVector bFlags)
{
    ColorSelectionModelEventSource *returnValue;

    newPtr<ColorSelectionModelEventSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
ColorSelectionModelEventSource *ColorSelectionModelEventSourceBase::createEmpty(void)
{
    ColorSelectionModelEventSource *returnValue;

    newPtr<ColorSelectionModelEventSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr ColorSelectionModelEventSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    ColorSelectionModelEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ColorSelectionModelEventSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr ColorSelectionModelEventSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    ColorSelectionModelEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ColorSelectionModelEventSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr ColorSelectionModelEventSourceBase::shallowCopy(void) const
{
    ColorSelectionModelEventSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const ColorSelectionModelEventSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

ColorSelectionModelEventSourceBase::ColorSelectionModelEventSourceBase(void) :
    Inherited()
{
}

ColorSelectionModelEventSourceBase::ColorSelectionModelEventSourceBase(const ColorSelectionModelEventSourceBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

ColorSelectionModelEventSourceBase::~ColorSelectionModelEventSourceBase(void)
{
}


#ifdef OSG_MT_CPTR_ASPECT
void ColorSelectionModelEventSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    ColorSelectionModelEventSource *pThis = static_cast<ColorSelectionModelEventSource *>(this);

    pThis->execSync(static_cast<ColorSelectionModelEventSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *ColorSelectionModelEventSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    ColorSelectionModelEventSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const ColorSelectionModelEventSource *>(pRefAspect),
                  dynamic_cast<const ColorSelectionModelEventSource *>(this));

    return returnValue;
}
#endif

void ColorSelectionModelEventSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();

}

OSG_END_NAMESPACE
