/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBOUNDEDRANGEMODELEVENTSOURCEFIELDS_H_
#define _OSGBOUNDEDRANGEMODELEVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class BoundedRangeModelEventSource;

OSG_GEN_CONTAINERPTR(BoundedRangeModelEventSource);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<BoundedRangeModelEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<BoundedRangeModelEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<BoundedRangeModelEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<BoundedRangeModelEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBoundedRangeModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<BoundedRangeModelEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBoundedRangeModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<BoundedRangeModelEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBoundedRangeModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<BoundedRangeModelEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBoundedRangeModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<BoundedRangeModelEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBoundedRangeModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<BoundedRangeModelEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBoundedRangeModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<BoundedRangeModelEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBoundedRangeModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<BoundedRangeModelEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBoundedRangeModelEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<BoundedRangeModelEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecBoundedRangeModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<BoundedRangeModelEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecBoundedRangeModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<BoundedRangeModelEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakBoundedRangeModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<BoundedRangeModelEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedBoundedRangeModelEventSourcePtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<BoundedRangeModelEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecBoundedRangeModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<BoundedRangeModelEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecBoundedRangeModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<BoundedRangeModelEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakBoundedRangeModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<BoundedRangeModelEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedBoundedRangeModelEventSourcePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecBoundedRangeModelEventSourcePtr : 
    public PointerSField<BoundedRangeModelEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecBoundedRangeModelEventSourcePtr : 
    public PointerSField<BoundedRangeModelEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakBoundedRangeModelEventSourcePtr :
    public PointerSField<BoundedRangeModelEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedBoundedRangeModelEventSourcePtr :
    public PointerSField<BoundedRangeModelEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecBoundedRangeModelEventSourcePtr :
    public PointerMField<BoundedRangeModelEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecBoundedRangeModelEventSourcePtr :
    public PointerMField<BoundedRangeModelEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakBoundedRangeModelEventSourcePtr :
    public PointerMField<BoundedRangeModelEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedBoundedRangeModelEventSourcePtr :
    public PointerMField<BoundedRangeModelEventSource *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBOUNDEDRANGEMODELEventSourceFIELDS_H_ */
