/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGBOUNDEDRANGEMODELFIELDS_H_
#define _OSGBOUNDEDRANGEMODELFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class BoundedRangeModel;

OSG_GEN_CONTAINERPTR(BoundedRangeModel);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<BoundedRangeModel *, nsOSG> :
    public FieldTraitsFCPtrBase<BoundedRangeModel *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<BoundedRangeModel *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<BoundedRangeModel *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecBoundedRangeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<BoundedRangeModel *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecBoundedRangeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<BoundedRangeModel *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakBoundedRangeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<BoundedRangeModel *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdBoundedRangeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<BoundedRangeModel *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecBoundedRangeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<BoundedRangeModel *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecBoundedRangeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<BoundedRangeModel *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakBoundedRangeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<BoundedRangeModel *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdBoundedRangeModelPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<BoundedRangeModel *,
                      RecordedRefCountPolicy, nsOSG  > SFRecBoundedRangeModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<BoundedRangeModel *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecBoundedRangeModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<BoundedRangeModel *,
                      WeakRefCountPolicy, nsOSG      > SFWeakBoundedRangeModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<BoundedRangeModel *,
                      NoRefCountPolicy, nsOSG        > SFUncountedBoundedRangeModelPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<BoundedRangeModel *,
                      RecordedRefCountPolicy, nsOSG  > MFRecBoundedRangeModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<BoundedRangeModel *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecBoundedRangeModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<BoundedRangeModel *,
                      WeakRefCountPolicy, nsOSG      > MFWeakBoundedRangeModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<BoundedRangeModel *,
                      NoRefCountPolicy, nsOSG        > MFUncountedBoundedRangeModelPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecBoundedRangeModelPtr : 
    public PointerSField<BoundedRangeModel *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecBoundedRangeModelPtr : 
    public PointerSField<BoundedRangeModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakBoundedRangeModelPtr :
    public PointerSField<BoundedRangeModel *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedBoundedRangeModelPtr :
    public PointerSField<BoundedRangeModel *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecBoundedRangeModelPtr :
    public PointerMField<BoundedRangeModel *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecBoundedRangeModelPtr :
    public PointerMField<BoundedRangeModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakBoundedRangeModelPtr :
    public PointerMField<BoundedRangeModel *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedBoundedRangeModelPtr :
    public PointerMField<BoundedRangeModel *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGBOUNDEDRANGEMODELFIELDS_H_ */
