/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class BoundedRangeModelEventSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"


#include "OSGBoundedRangeModelEventSourceBase.h"
#include "OSGBoundedRangeModelEventSource.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::BoundedRangeModelEventSource
    A UI BoundedRangeModel.
 */



/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<BoundedRangeModelEventSource *, nsOSG>::_type(
    "BoundedRangeModelEventSourcePtr",
    "EventContainerPtr",
    BoundedRangeModelEventSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(BoundedRangeModelEventSource *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           BoundedRangeModelEventSource *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           BoundedRangeModelEventSource *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void BoundedRangeModelEventSourceBase::classDescInserter(TypeObject &oType)
{
}


BoundedRangeModelEventSourceBase::TypeObject BoundedRangeModelEventSourceBase::_type(
    BoundedRangeModelEventSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&BoundedRangeModelEventSourceBase::createEmptyLocal),
    BoundedRangeModelEventSource::initMethod,
    BoundedRangeModelEventSource::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&BoundedRangeModelEventSource::classDescInserter),
    false,
    0,
    "",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &BoundedRangeModelEventSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &BoundedRangeModelEventSourceBase::getType(void) const
{
    return _type;
}

UInt32 BoundedRangeModelEventSourceBase::getContainerSize(void) const
{
    return sizeof(BoundedRangeModelEventSource);
}



/*------------------------------ access -----------------------------------*/

SizeT BoundedRangeModelEventSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    return returnValue;
}

void BoundedRangeModelEventSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);
}

void BoundedRangeModelEventSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);
}

//! create a new instance of the class
BoundedRangeModelEventSourceTransitPtr BoundedRangeModelEventSourceBase::createLocal(BitVector bFlags)
{
    BoundedRangeModelEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<BoundedRangeModelEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
BoundedRangeModelEventSourceTransitPtr BoundedRangeModelEventSourceBase::createDependent(BitVector bFlags)
{
    BoundedRangeModelEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<BoundedRangeModelEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
BoundedRangeModelEventSourceTransitPtr BoundedRangeModelEventSourceBase::create(void)
{
    BoundedRangeModelEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<BoundedRangeModelEventSource>(tmpPtr);
    }

    return fc;
}

BoundedRangeModelEventSource *BoundedRangeModelEventSourceBase::createEmptyLocal(BitVector bFlags)
{
    BoundedRangeModelEventSource *returnValue;

    newPtr<BoundedRangeModelEventSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
BoundedRangeModelEventSource *BoundedRangeModelEventSourceBase::createEmpty(void)
{
    BoundedRangeModelEventSource *returnValue;

    newPtr<BoundedRangeModelEventSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr BoundedRangeModelEventSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    BoundedRangeModelEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BoundedRangeModelEventSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr BoundedRangeModelEventSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    BoundedRangeModelEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const BoundedRangeModelEventSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr BoundedRangeModelEventSourceBase::shallowCopy(void) const
{
    BoundedRangeModelEventSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const BoundedRangeModelEventSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

BoundedRangeModelEventSourceBase::BoundedRangeModelEventSourceBase(void) :
    Inherited()
{
}

BoundedRangeModelEventSourceBase::BoundedRangeModelEventSourceBase(const BoundedRangeModelEventSourceBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

BoundedRangeModelEventSourceBase::~BoundedRangeModelEventSourceBase(void)
{
}


#ifdef OSG_MT_CPTR_ASPECT
void BoundedRangeModelEventSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    BoundedRangeModelEventSource *pThis = static_cast<BoundedRangeModelEventSource *>(this);

    pThis->execSync(static_cast<BoundedRangeModelEventSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *BoundedRangeModelEventSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    BoundedRangeModelEventSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const BoundedRangeModelEventSource *>(pRefAspect),
                  dynamic_cast<const BoundedRangeModelEventSource *>(this));

    return returnValue;
}
#endif

void BoundedRangeModelEventSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();

}

OSG_END_NAMESPACE
