/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class BoundedRangeModel!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"



#include "OSGBoundedRangeModelEventSource.h" // EventSource Class

#include "OSGBoundedRangeModelBase.h"
#include "OSGBoundedRangeModel.h"
#include "OSGBoundedRangeModelEventSource.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::BoundedRangeModel
    A UI BoundedRangeModel.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var BoundedRangeModelEventSource * BoundedRangeModelBase::_sfEventSource
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<BoundedRangeModel *, nsOSG>::_type(
    "BoundedRangeModelPtr", 
    "FieldContainerPtr", 
    BoundedRangeModel::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(BoundedRangeModel *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           BoundedRangeModel *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           BoundedRangeModel *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void BoundedRangeModelBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecBoundedRangeModelEventSourcePtr::Description(
        SFUnrecBoundedRangeModelEventSourcePtr::getClassType(),
        "EventSource",
        "",
        EventSourceFieldId, EventSourceFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&BoundedRangeModel::editHandleEventSource),
        static_cast<FieldGetMethodSig >(&BoundedRangeModel::getHandleEventSource));

    oType.addInitialDesc(pDesc);
}


BoundedRangeModelBase::TypeObject BoundedRangeModelBase::_type(
    BoundedRangeModelBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    NULL,
    BoundedRangeModel::initMethod,
    BoundedRangeModel::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&BoundedRangeModel::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"BoundedRangeModel\"\n"
    "    parent=\"FieldContainer\"\n"
    "    library=\"ContribToolboxUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"abstract\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "A UI BoundedRangeModel.\n"
    "    <Field\n"
    "        name=\"EventSource\"\n"
    "        type=\"BoundedRangeModelEventSource\"\n"
    "        category=\"pointer\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        defaultValue=\"NULL\"\n"
    "        access=\"public\"\n"
    "    >\n"
    "    </Field>\n"
    "    <ProducedEvent\n"
    "        name=\"StateChanged\"\n"
    "        detailsType=\"ChangeEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "</FieldContainer>\n",
    "A UI BoundedRangeModel.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &BoundedRangeModelBase::getType(void)
{
    return _type;
}

const FieldContainerType &BoundedRangeModelBase::getType(void) const
{
    return _type;
}

UInt32 BoundedRangeModelBase::getContainerSize(void) const
{
    return sizeof(BoundedRangeModel);
}

/*------------------------- decorator get ------------------------------*/


//! Get the BoundedRangeModel::_sfEventSource field.
const SFUnrecBoundedRangeModelEventSourcePtr *BoundedRangeModelBase::getSFEventSource(void) const
{
    return &_sfEventSource;
}

SFUnrecBoundedRangeModelEventSourcePtr *BoundedRangeModelBase::editSFEventSource    (void)
{
    editSField(EventSourceFieldMask);

    return &_sfEventSource;
}






/*------------------------------ access -----------------------------------*/

SizeT BoundedRangeModelBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        returnValue += _sfEventSource.getBinSize();
    }

    return returnValue;
}

void BoundedRangeModelBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        _sfEventSource.copyToBin(pMem);
    }
}

void BoundedRangeModelBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        editSField(EventSourceFieldMask);
        _sfEventSource.copyFromBin(pMem);
    }
}




/*------------------------- constructors ----------------------------------*/

BoundedRangeModelBase::BoundedRangeModelBase(void) :
    Inherited(),
    _sfEventSource            (NULL)
{
}

BoundedRangeModelBase::BoundedRangeModelBase(const BoundedRangeModelBase &source) :
    Inherited(source),
    _sfEventSource            (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

BoundedRangeModelBase::~BoundedRangeModelBase(void)
{
}

void BoundedRangeModelBase::onCreate(const BoundedRangeModel *source)
{
    Inherited::onCreate(source);

    if(source)
    {
        BoundedRangeModel *pThis = static_cast<BoundedRangeModel *>(this);

        pThis->setEventSource(source->getEventSource());
    }
    
    {
        BoundedRangeModelEventSourceUnrecPtr evSrc = BoundedRangeModelEventSource::create();
        setEventSource( evSrc );
    }
}

GetFieldHandlePtr BoundedRangeModelBase::getHandleEventSource     (void) const
{
    SFUnrecBoundedRangeModelEventSourcePtr::GetHandlePtr returnValue(
        new  SFUnrecBoundedRangeModelEventSourcePtr::GetHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             const_cast<BoundedRangeModelBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr BoundedRangeModelBase::editHandleEventSource    (void)
{
    SFUnrecBoundedRangeModelEventSourcePtr::EditHandlePtr returnValue(
        new  SFUnrecBoundedRangeModelEventSourcePtr::EditHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&BoundedRangeModel::setEventSource,
                    static_cast<BoundedRangeModel *>(this), _1));

    editSField(EventSourceFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void BoundedRangeModelBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    BoundedRangeModel *pThis = static_cast<BoundedRangeModel *>(this);

    pThis->execSync(static_cast<BoundedRangeModel *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif



void BoundedRangeModelBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<BoundedRangeModel *>(this)->setEventSource(NULL);


}


OSG_END_NAMESPACE
