/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSCROLLBAREVENTSOURCEFIELDS_H_
#define _OSGSCROLLBAREVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class ScrollBarEventSource;

OSG_GEN_CONTAINERPTR(ScrollBarEventSource);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<ScrollBarEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<ScrollBarEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<ScrollBarEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<ScrollBarEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecScrollBarEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ScrollBarEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecScrollBarEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ScrollBarEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakScrollBarEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ScrollBarEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdScrollBarEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ScrollBarEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecScrollBarEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ScrollBarEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecScrollBarEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ScrollBarEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakScrollBarEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<ScrollBarEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdScrollBarEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ScrollBarEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecScrollBarEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ScrollBarEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecScrollBarEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ScrollBarEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakScrollBarEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ScrollBarEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedScrollBarEventSourcePtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ScrollBarEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecScrollBarEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ScrollBarEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecScrollBarEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ScrollBarEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakScrollBarEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ScrollBarEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedScrollBarEventSourcePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecScrollBarEventSourcePtr : 
    public PointerSField<ScrollBarEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecScrollBarEventSourcePtr : 
    public PointerSField<ScrollBarEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakScrollBarEventSourcePtr :
    public PointerSField<ScrollBarEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedScrollBarEventSourcePtr :
    public PointerSField<ScrollBarEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecScrollBarEventSourcePtr :
    public PointerMField<ScrollBarEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecScrollBarEventSourcePtr :
    public PointerMField<ScrollBarEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakScrollBarEventSourcePtr :
    public PointerMField<ScrollBarEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedScrollBarEventSourcePtr :
    public PointerMField<ScrollBarEventSource *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSCROLLBAREVENTSOURCEFIELDS_H_ */
