/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ScrollBarEventSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"


#include "OSGScrollBarEventSourceBase.h"
#include "OSGScrollBarEventSource.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::ScrollBarEventSource
    A UI ScrollBar.
 */



/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<ScrollBarEventSource *, nsOSG>::_type(
    "ScrollBarEventSourcePtr",
    "ComponentEventSourcePtr",
    ScrollBarEventSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(ScrollBarEventSource *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           ScrollBarEventSource *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           ScrollBarEventSource *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void ScrollBarEventSourceBase::classDescInserter(TypeObject &oType)
{
}


ScrollBarEventSourceBase::TypeObject ScrollBarEventSourceBase::_type(
    ScrollBarEventSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&ScrollBarEventSourceBase::createEmptyLocal),
    ScrollBarEventSource::initMethod,
    ScrollBarEventSource::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&ScrollBarEventSource::classDescInserter),
    false,
    0,
    "",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &ScrollBarEventSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &ScrollBarEventSourceBase::getType(void) const
{
    return _type;
}

UInt32 ScrollBarEventSourceBase::getContainerSize(void) const
{
    return sizeof(ScrollBarEventSource);
}



/*------------------------------ access -----------------------------------*/

SizeT ScrollBarEventSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    return returnValue;
}

void ScrollBarEventSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);
}

void ScrollBarEventSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);
}

//! create a new instance of the class
ScrollBarEventSourceTransitPtr ScrollBarEventSourceBase::createLocal(BitVector bFlags)
{
    ScrollBarEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<ScrollBarEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
ScrollBarEventSourceTransitPtr ScrollBarEventSourceBase::createDependent(BitVector bFlags)
{
    ScrollBarEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<ScrollBarEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
ScrollBarEventSourceTransitPtr ScrollBarEventSourceBase::create(void)
{
    ScrollBarEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<ScrollBarEventSource>(tmpPtr);
    }

    return fc;
}

ScrollBarEventSource *ScrollBarEventSourceBase::createEmptyLocal(BitVector bFlags)
{
    ScrollBarEventSource *returnValue;

    newPtr<ScrollBarEventSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
ScrollBarEventSource *ScrollBarEventSourceBase::createEmpty(void)
{
    ScrollBarEventSource *returnValue;

    newPtr<ScrollBarEventSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr ScrollBarEventSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    ScrollBarEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ScrollBarEventSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr ScrollBarEventSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    ScrollBarEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ScrollBarEventSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr ScrollBarEventSourceBase::shallowCopy(void) const
{
    ScrollBarEventSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const ScrollBarEventSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

ScrollBarEventSourceBase::ScrollBarEventSourceBase(void) :
    Inherited()
{
}

ScrollBarEventSourceBase::ScrollBarEventSourceBase(const ScrollBarEventSourceBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

ScrollBarEventSourceBase::~ScrollBarEventSourceBase(void)
{
}


#ifdef OSG_MT_CPTR_ASPECT
void ScrollBarEventSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    ScrollBarEventSource *pThis = static_cast<ScrollBarEventSource *>(this);

    pThis->execSync(static_cast<ScrollBarEventSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *ScrollBarEventSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    ScrollBarEventSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const ScrollBarEventSource *>(pRefAspect),
                  dynamic_cast<const ScrollBarEventSource *>(this));

    return returnValue;
}
#endif

void ScrollBarEventSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();

}

OSG_END_NAMESPACE
