/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSCROLLBARFIELDS_H_
#define _OSGSCROLLBARFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class ScrollBar;

OSG_GEN_CONTAINERPTR(ScrollBar);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<ScrollBar *, nsOSG> :
    public FieldTraitsFCPtrBase<ScrollBar *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<ScrollBar *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<ScrollBar *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecScrollBarPtr"; 
}

template<> inline
const Char8 *FieldTraits<ScrollBar *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecScrollBarPtr"; 
}

template<> inline
const Char8 *FieldTraits<ScrollBar *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakScrollBarPtr"; 
}

template<> inline
const Char8 *FieldTraits<ScrollBar *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdScrollBarPtr"; 
}

template<> inline
const Char8 *FieldTraits<ScrollBar *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecScrollBarPtr"; 
}

template<> inline
const Char8 *FieldTraits<ScrollBar *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecScrollBarPtr"; 
}

template<> inline
const Char8 *FieldTraits<ScrollBar *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakScrollBarPtr"; 
}

template<> inline
const Char8 *FieldTraits<ScrollBar *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdScrollBarPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ScrollBar *,
                      RecordedRefCountPolicy, nsOSG  > SFRecScrollBarPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ScrollBar *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecScrollBarPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ScrollBar *,
                      WeakRefCountPolicy, nsOSG      > SFWeakScrollBarPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ScrollBar *,
                      NoRefCountPolicy, nsOSG        > SFUncountedScrollBarPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ScrollBar *,
                      RecordedRefCountPolicy, nsOSG  > MFRecScrollBarPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ScrollBar *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecScrollBarPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ScrollBar *,
                      WeakRefCountPolicy, nsOSG      > MFWeakScrollBarPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ScrollBar *,
                      NoRefCountPolicy, nsOSG        > MFUncountedScrollBarPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecScrollBarPtr : 
    public PointerSField<ScrollBar *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecScrollBarPtr : 
    public PointerSField<ScrollBar *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakScrollBarPtr :
    public PointerSField<ScrollBar *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedScrollBarPtr :
    public PointerSField<ScrollBar *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecScrollBarPtr :
    public PointerMField<ScrollBar *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecScrollBarPtr :
    public PointerMField<ScrollBar *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakScrollBarPtr :
    public PointerMField<ScrollBar *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedScrollBarPtr :
    public PointerMField<ScrollBar *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSCROLLBARFIELDS_H_ */
