/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTABLECOLUMNEVENTSOURCEFIELDS_H_
#define _OSGTABLECOLUMNEVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TableColumnEventSource;

OSG_GEN_CONTAINERPTR(TableColumnEventSource);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<TableColumnEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<TableColumnEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TableColumnEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TableColumnEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTableColumnEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumnEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTableColumnEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumnEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTableColumnEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumnEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTableColumnEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumnEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTableColumnEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumnEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTableColumnEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumnEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTableColumnEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumnEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTableColumnEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TableColumnEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTableColumnEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TableColumnEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTableColumnEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TableColumnEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTableColumnEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TableColumnEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTableColumnEventSourcePtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TableColumnEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTableColumnEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TableColumnEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTableColumnEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TableColumnEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTableColumnEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TableColumnEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTableColumnEventSourcePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecTableColumnEventSourcePtr : 
    public PointerSField<TableColumnEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecTableColumnEventSourcePtr : 
    public PointerSField<TableColumnEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakTableColumnEventSourcePtr :
    public PointerSField<TableColumnEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedTableColumnEventSourcePtr :
    public PointerSField<TableColumnEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecTableColumnEventSourcePtr :
    public PointerMField<TableColumnEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecTableColumnEventSourcePtr :
    public PointerMField<TableColumnEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakTableColumnEventSourcePtr :
    public PointerMField<TableColumnEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedTableColumnEventSourcePtr :
    public PointerMField<TableColumnEventSource *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTABLECOLUMNEVENTSOURCEFIELDS_H_ */
