/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTABLECOLUMNFIELDS_H_
#define _OSGTABLECOLUMNFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TableColumn;

OSG_GEN_CONTAINERPTR(TableColumn);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<TableColumn *, nsOSG> :
    public FieldTraitsFCPtrBase<TableColumn *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TableColumn *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TableColumn *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTableColumnPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumn *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTableColumnPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumn *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTableColumnPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumn *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTableColumnPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumn *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTableColumnPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumn *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTableColumnPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumn *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTableColumnPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableColumn *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTableColumnPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TableColumn *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTableColumnPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TableColumn *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTableColumnPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TableColumn *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTableColumnPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TableColumn *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTableColumnPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TableColumn *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTableColumnPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TableColumn *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTableColumnPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TableColumn *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTableColumnPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TableColumn *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTableColumnPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecTableColumnPtr : 
    public PointerSField<TableColumn *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecTableColumnPtr : 
    public PointerSField<TableColumn *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakTableColumnPtr :
    public PointerSField<TableColumn *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedTableColumnPtr :
    public PointerSField<TableColumn *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecTableColumnPtr :
    public PointerMField<TableColumn *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecTableColumnPtr :
    public PointerMField<TableColumn *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakTableColumnPtr :
    public PointerMField<TableColumn *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedTableColumnPtr :
    public PointerMField<TableColumn *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTABLECOLUMNFIELDS_H_ */
