/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TableColumnEventSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"


#include "OSGTableColumnEventSourceBase.h"
#include "OSGTableColumnEventSource.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TableColumnEventSource
    A UI Table Column.
 */



/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<TableColumnEventSource *, nsOSG>::_type(
    "TableColumnEventSourcePtr",
    "EventContainerPtr",
    TableColumnEventSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(TableColumnEventSource *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TableColumnEventSource *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TableColumnEventSource *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TableColumnEventSourceBase::classDescInserter(TypeObject &oType)
{
}


TableColumnEventSourceBase::TypeObject TableColumnEventSourceBase::_type(
    TableColumnEventSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&TableColumnEventSourceBase::createEmptyLocal),
    TableColumnEventSource::initMethod,
    TableColumnEventSource::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TableColumnEventSource::classDescInserter),
    false,
    0,
    "",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TableColumnEventSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &TableColumnEventSourceBase::getType(void) const
{
    return _type;
}

UInt32 TableColumnEventSourceBase::getContainerSize(void) const
{
    return sizeof(TableColumnEventSource);
}



/*------------------------------ access -----------------------------------*/

SizeT TableColumnEventSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    return returnValue;
}

void TableColumnEventSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);
}

void TableColumnEventSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);
}

//! create a new instance of the class
TableColumnEventSourceTransitPtr TableColumnEventSourceBase::createLocal(BitVector bFlags)
{
    TableColumnEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<TableColumnEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
TableColumnEventSourceTransitPtr TableColumnEventSourceBase::createDependent(BitVector bFlags)
{
    TableColumnEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<TableColumnEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
TableColumnEventSourceTransitPtr TableColumnEventSourceBase::create(void)
{
    TableColumnEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<TableColumnEventSource>(tmpPtr);
    }

    return fc;
}

TableColumnEventSource *TableColumnEventSourceBase::createEmptyLocal(BitVector bFlags)
{
    TableColumnEventSource *returnValue;

    newPtr<TableColumnEventSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
TableColumnEventSource *TableColumnEventSourceBase::createEmpty(void)
{
    TableColumnEventSource *returnValue;

    newPtr<TableColumnEventSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr TableColumnEventSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    TableColumnEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TableColumnEventSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr TableColumnEventSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    TableColumnEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TableColumnEventSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr TableColumnEventSourceBase::shallowCopy(void) const
{
    TableColumnEventSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const TableColumnEventSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

TableColumnEventSourceBase::TableColumnEventSourceBase(void) :
    Inherited()
{
}

TableColumnEventSourceBase::TableColumnEventSourceBase(const TableColumnEventSourceBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

TableColumnEventSourceBase::~TableColumnEventSourceBase(void)
{
}


#ifdef OSG_MT_CPTR_ASPECT
void TableColumnEventSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TableColumnEventSource *pThis = static_cast<TableColumnEventSource *>(this);

    pThis->execSync(static_cast<TableColumnEventSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *TableColumnEventSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    TableColumnEventSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const TableColumnEventSource *>(pRefAspect),
                  dynamic_cast<const TableColumnEventSource *>(this));

    return returnValue;
}
#endif

void TableColumnEventSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();

}

OSG_END_NAMESPACE
