/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGEVENTCONTAINERFIELDS_H_
#define _OSGEVENTCONTAINERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class EventContainer;

OSG_GEN_CONTAINERPTR(EventContainer);
/*! \ingroup GrpContribToolboxFieldTraits
    \ingroup GrpLibOSGContribToolbox
 */
template <>
struct FieldTraits<EventContainer *, nsOSG> :
    public FieldTraitsFCPtrBase<EventContainer *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<EventContainer *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOX_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<EventContainer *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecEventContainerPtr"; 
}

template<> inline
const Char8 *FieldTraits<EventContainer *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecEventContainerPtr"; 
}

template<> inline
const Char8 *FieldTraits<EventContainer *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakEventContainerPtr"; 
}

template<> inline
const Char8 *FieldTraits<EventContainer *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdEventContainerPtr"; 
}

template<> inline
const Char8 *FieldTraits<EventContainer *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecEventContainerPtr"; 
}

template<> inline
const Char8 *FieldTraits<EventContainer *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecEventContainerPtr"; 
}

template<> inline
const Char8 *FieldTraits<EventContainer *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakEventContainerPtr"; 
}

template<> inline
const Char8 *FieldTraits<EventContainer *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdEventContainerPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxFieldSFields */
typedef PointerSField<EventContainer *,
                      RecordedRefCountPolicy, nsOSG  > SFRecEventContainerPtr;
/*! \ingroup GrpContribToolboxFieldSFields */
typedef PointerSField<EventContainer *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecEventContainerPtr;
/*! \ingroup GrpContribToolboxFieldSFields */
typedef PointerSField<EventContainer *,
                      WeakRefCountPolicy, nsOSG      > SFWeakEventContainerPtr;
/*! \ingroup GrpContribToolboxFieldSFields */
typedef PointerSField<EventContainer *,
                      NoRefCountPolicy, nsOSG        > SFUncountedEventContainerPtr;


/*! \ingroup GrpContribToolboxFieldMFields */
typedef PointerMField<EventContainer *,
                      RecordedRefCountPolicy, nsOSG  > MFRecEventContainerPtr;
/*! \ingroup GrpContribToolboxFieldMFields */
typedef PointerMField<EventContainer *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecEventContainerPtr;
/*! \ingroup GrpContribToolboxFieldMFields */
typedef PointerMField<EventContainer *,
                      WeakRefCountPolicy, nsOSG      > MFWeakEventContainerPtr;
/*! \ingroup GrpContribToolboxFieldMFields */
typedef PointerMField<EventContainer *,
                      NoRefCountPolicy, nsOSG        > MFUncountedEventContainerPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxFieldSFields \ingroup GrpLibOSGContribToolbox */
struct SFRecEventContainerPtr : 
    public PointerSField<EventContainer *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxFieldSFields \ingroup GrpLibOSGContribToolbox */
struct SFUnrecEventContainerPtr : 
    public PointerSField<EventContainer *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxFieldSFields \ingroup GrpLibOSGContribToolbox */
struct SFWeakEventContainerPtr :
    public PointerSField<EventContainer *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxFieldSFields \ingroup GrpLibOSGContribToolbox */
struct SFUncountedEventContainerPtr :
    public PointerSField<EventContainer *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxFieldMFields \ingroup GrpLibOSGContribToolbox */
struct MFRecEventContainerPtr :
    public PointerMField<EventContainer *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxFieldMFields \ingroup GrpLibOSGContribToolbox */
struct MFUnrecEventContainerPtr :
    public PointerMField<EventContainer *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxFieldMFields \ingroup GrpLibOSGContribToolbox */
struct MFWeakEventContainerPtr :
    public PointerMField<EventContainer *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxFieldMFields \ingroup GrpLibOSGContribToolbox */
struct MFUncountedEventContainerPtr :
    public PointerMField<EventContainer *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGEVENTCONTAINERFIELDS_H_ */
