/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGWINDOWEVENTPRODUCEREVENTSOURCEFIELDS_H_
#define _OSGWINDOWEVENTPRODUCEREVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxWindowDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class WindowEventProducerEventSource;

OSG_GEN_CONTAINERPTR(WindowEventProducerEventSource);
/*! \ingroup GrpContribToolboxWindowFieldTraits
    \ingroup GrpLibOSGContribToolboxWindow
 */
template <>
struct FieldTraits<WindowEventProducerEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<WindowEventProducerEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<WindowEventProducerEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXWINDOW_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<WindowEventProducerEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecWindowEventProducerEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<WindowEventProducerEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecWindowEventProducerEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<WindowEventProducerEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakWindowEventProducerEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<WindowEventProducerEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdWindowEventProducerEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<WindowEventProducerEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecWindowEventProducerEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<WindowEventProducerEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecWindowEventProducerEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<WindowEventProducerEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakWindowEventProducerEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<WindowEventProducerEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdWindowEventProducerEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxWindowFieldSFields */
typedef PointerSField<WindowEventProducerEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecWindowEventProducerEventSourcePtr;
/*! \ingroup GrpContribToolboxWindowFieldSFields */
typedef PointerSField<WindowEventProducerEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecWindowEventProducerEventSourcePtr;
/*! \ingroup GrpContribToolboxWindowFieldSFields */
typedef PointerSField<WindowEventProducerEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakWindowEventProducerEventSourcePtr;
/*! \ingroup GrpContribToolboxWindowFieldSFields */
typedef PointerSField<WindowEventProducerEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedWindowEventProducerEventSourcePtr;


/*! \ingroup GrpContribToolboxWindowFieldMFields */
typedef PointerMField<WindowEventProducerEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecWindowEventProducerEventSourcePtr;
/*! \ingroup GrpContribToolboxWindowFieldMFields */
typedef PointerMField<WindowEventProducerEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecWindowEventProducerEventSourcePtr;
/*! \ingroup GrpContribToolboxWindowFieldMFields */
typedef PointerMField<WindowEventProducerEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakWindowEventProducerEventSourcePtr;
/*! \ingroup GrpContribToolboxWindowFieldMFields */
typedef PointerMField<WindowEventProducerEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedWindowEventProducerEventSourcePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxWindowFieldSFields \ingroup GrpLibOSGContribToolboxWindow */
struct SFRecWindowEventProducerEventSourcePtr : 
    public PointerSField<WindowEventProducerEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxWindowFieldSFields \ingroup GrpLibOSGContribToolboxWindow */
struct SFUnrecWindowEventProducerEventSourcePtr : 
    public PointerSField<WindowEventProducerEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxWindowFieldSFields \ingroup GrpLibOSGContribToolboxWindow */
struct SFWeakWindowEventProducerEventSourcePtr :
    public PointerSField<WindowEventProducerEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxWindowFieldSFields \ingroup GrpLibOSGContribToolboxWindow */
struct SFUncountedWindowEventProducerEventSourcePtr :
    public PointerSField<WindowEventProducerEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxWindowFieldMFields \ingroup GrpLibOSGContribToolboxWindow */
struct MFRecWindowEventProducerEventSourcePtr :
    public PointerMField<WindowEventProducerEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxWindowFieldMFields \ingroup GrpLibOSGContribToolboxWindow */
struct MFUnrecWindowEventProducerEventSourcePtr :
    public PointerMField<WindowEventProducerEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxWindowFieldMFields \ingroup GrpLibOSGContribToolboxWindow */
struct MFWeakWindowEventProducerEventSourcePtr :
    public PointerMField<WindowEventProducerEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxWindowFieldMFields \ingroup GrpLibOSGContribToolboxWindow */
struct MFUncountedWindowEventProducerEventSourcePtr :
    public PointerMField<WindowEventProducerEventSource *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGWINDOWEVENTPRODUCEREVENTSOURCEFIELDS_H_ */
