/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGLISTSELECTIONMODELFIELDS_H_
#define _OSGLISTSELECTIONMODELFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class ListSelectionModel;

OSG_GEN_CONTAINERPTR(ListSelectionModel);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<ListSelectionModel *, nsOSG> :
    public FieldTraitsFCPtrBase<ListSelectionModel *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<ListSelectionModel *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<ListSelectionModel *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecListSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListSelectionModel *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecListSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListSelectionModel *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakListSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListSelectionModel *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdListSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListSelectionModel *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecListSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListSelectionModel *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecListSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListSelectionModel *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakListSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ListSelectionModel *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdListSelectionModelPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ListSelectionModel *,
                      RecordedRefCountPolicy, nsOSG  > SFRecListSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ListSelectionModel *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecListSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ListSelectionModel *,
                      WeakRefCountPolicy, nsOSG      > SFWeakListSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ListSelectionModel *,
                      NoRefCountPolicy, nsOSG        > SFUncountedListSelectionModelPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ListSelectionModel *,
                      RecordedRefCountPolicy, nsOSG  > MFRecListSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ListSelectionModel *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecListSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ListSelectionModel *,
                      WeakRefCountPolicy, nsOSG      > MFWeakListSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ListSelectionModel *,
                      NoRefCountPolicy, nsOSG        > MFUncountedListSelectionModelPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecListSelectionModelPtr : 
    public PointerSField<ListSelectionModel *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecListSelectionModelPtr : 
    public PointerSField<ListSelectionModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakListSelectionModelPtr :
    public PointerSField<ListSelectionModel *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedListSelectionModelPtr :
    public PointerSField<ListSelectionModel *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecListSelectionModelPtr :
    public PointerMField<ListSelectionModel *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecListSelectionModelPtr :
    public PointerMField<ListSelectionModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakListSelectionModelPtr :
    public PointerMField<ListSelectionModel *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedListSelectionModelPtr :
    public PointerMField<ListSelectionModel *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGLISTSELECTIONMODELFIELDS_H_ */
