/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ListSelectionModelEventSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"




#include "OSGListSelectionModelEventSourceBase.h"
#include "OSGListSelectionModelEventSource.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::ListSelectionModelEventSource
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<ListSelectionModelEventSource *, nsOSG>::_type(
    "ListSelectionModelEventSourcePtr", 
    "EventContainerPtr", 
    ListSelectionModelEventSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(ListSelectionModelEventSource *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           ListSelectionModelEventSource *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           ListSelectionModelEventSource *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void ListSelectionModelEventSourceBase::classDescInserter(TypeObject &oType)
{
}


ListSelectionModelEventSourceBase::TypeObject ListSelectionModelEventSourceBase::_type(
    ListSelectionModelEventSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&ListSelectionModelEventSourceBase::createEmptyLocal),
    ListSelectionModelEventSource::initMethod,
    ListSelectionModelEventSource::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&ListSelectionModelEventSource::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"ListSelectionModelEventSource\"\n"
    "    parent=\"EventContainer\"\n"
    "    library=\"ContribToolboxUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    ">\n"
    "<!--\n"
    "    <ProducedEvent\n"
    "        name=\"SelectionChanged\"\n"
    "        detailsType=\"ListSelectionEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "-->\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &ListSelectionModelEventSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &ListSelectionModelEventSourceBase::getType(void) const
{
    return _type;
}

UInt32 ListSelectionModelEventSourceBase::getContainerSize(void) const
{
    return sizeof(ListSelectionModelEventSource);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

SizeT ListSelectionModelEventSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void ListSelectionModelEventSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void ListSelectionModelEventSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
ListSelectionModelEventSourceTransitPtr ListSelectionModelEventSourceBase::createLocal(BitVector bFlags)
{
    ListSelectionModelEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<ListSelectionModelEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
ListSelectionModelEventSourceTransitPtr ListSelectionModelEventSourceBase::createDependent(BitVector bFlags)
{
    ListSelectionModelEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<ListSelectionModelEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
ListSelectionModelEventSourceTransitPtr ListSelectionModelEventSourceBase::create(void)
{
    ListSelectionModelEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<ListSelectionModelEventSource>(tmpPtr);
    }

    return fc;
}

ListSelectionModelEventSource *ListSelectionModelEventSourceBase::createEmptyLocal(BitVector bFlags)
{
    ListSelectionModelEventSource *returnValue;

    newPtr<ListSelectionModelEventSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
ListSelectionModelEventSource *ListSelectionModelEventSourceBase::createEmpty(void)
{
    ListSelectionModelEventSource *returnValue;

    newPtr<ListSelectionModelEventSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr ListSelectionModelEventSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    ListSelectionModelEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ListSelectionModelEventSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr ListSelectionModelEventSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    ListSelectionModelEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ListSelectionModelEventSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr ListSelectionModelEventSourceBase::shallowCopy(void) const
{
    ListSelectionModelEventSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const ListSelectionModelEventSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

ListSelectionModelEventSourceBase::ListSelectionModelEventSourceBase(void) :
    Inherited()
{
}

ListSelectionModelEventSourceBase::ListSelectionModelEventSourceBase(const ListSelectionModelEventSourceBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

ListSelectionModelEventSourceBase::~ListSelectionModelEventSourceBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void ListSelectionModelEventSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    ListSelectionModelEventSource *pThis = static_cast<ListSelectionModelEventSource *>(this);

    pThis->execSync(static_cast<ListSelectionModelEventSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *ListSelectionModelEventSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    ListSelectionModelEventSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const ListSelectionModelEventSource *>(pRefAspect),
                  dynamic_cast<const ListSelectionModelEventSource *>(this));

    return returnValue;
}
#endif

void ListSelectionModelEventSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
