/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSINGLESELECTIONMODELEVENTSOURCEFIELDS_H_
#define _OSGSINGLESELECTIONMODELEVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class SingleSelectionModelEventSource;

OSG_GEN_CONTAINERPTR(SingleSelectionModelEventSource);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<SingleSelectionModelEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<SingleSelectionModelEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<SingleSelectionModelEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<SingleSelectionModelEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSingleSelectionModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<SingleSelectionModelEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSingleSelectionModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<SingleSelectionModelEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSingleSelectionModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<SingleSelectionModelEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSingleSelectionModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<SingleSelectionModelEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSingleSelectionModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<SingleSelectionModelEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSingleSelectionModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<SingleSelectionModelEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSingleSelectionModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<SingleSelectionModelEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSingleSelectionModelEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<SingleSelectionModelEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecSingleSelectionModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<SingleSelectionModelEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecSingleSelectionModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<SingleSelectionModelEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakSingleSelectionModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<SingleSelectionModelEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedSingleSelectionModelEventSourcePtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<SingleSelectionModelEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecSingleSelectionModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<SingleSelectionModelEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecSingleSelectionModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<SingleSelectionModelEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakSingleSelectionModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<SingleSelectionModelEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedSingleSelectionModelEventSourcePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecSingleSelectionModelEventSourcePtr : 
    public PointerSField<SingleSelectionModelEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecSingleSelectionModelEventSourcePtr : 
    public PointerSField<SingleSelectionModelEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakSingleSelectionModelEventSourcePtr :
    public PointerSField<SingleSelectionModelEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedSingleSelectionModelEventSourcePtr :
    public PointerSField<SingleSelectionModelEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecSingleSelectionModelEventSourcePtr :
    public PointerMField<SingleSelectionModelEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecSingleSelectionModelEventSourcePtr :
    public PointerMField<SingleSelectionModelEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakSingleSelectionModelEventSourcePtr :
    public PointerMField<SingleSelectionModelEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedSingleSelectionModelEventSourcePtr :
    public PointerMField<SingleSelectionModelEventSource *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSINGLESELECTIONMODELEVENTSOURCEFIELDS_H_ */
