/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSINGLESELECTIONMODELFIELDS_H_
#define _OSGSINGLESELECTIONMODELFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class SingleSelectionModel;

OSG_GEN_CONTAINERPTR(SingleSelectionModel);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<SingleSelectionModel *, nsOSG> :
    public FieldTraitsFCPtrBase<SingleSelectionModel *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<SingleSelectionModel *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<SingleSelectionModel *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSingleSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<SingleSelectionModel *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSingleSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<SingleSelectionModel *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSingleSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<SingleSelectionModel *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSingleSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<SingleSelectionModel *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSingleSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<SingleSelectionModel *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSingleSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<SingleSelectionModel *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSingleSelectionModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<SingleSelectionModel *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSingleSelectionModelPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<SingleSelectionModel *,
                      RecordedRefCountPolicy, nsOSG  > SFRecSingleSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<SingleSelectionModel *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecSingleSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<SingleSelectionModel *,
                      WeakRefCountPolicy, nsOSG      > SFWeakSingleSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<SingleSelectionModel *,
                      NoRefCountPolicy, nsOSG        > SFUncountedSingleSelectionModelPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<SingleSelectionModel *,
                      RecordedRefCountPolicy, nsOSG  > MFRecSingleSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<SingleSelectionModel *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecSingleSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<SingleSelectionModel *,
                      WeakRefCountPolicy, nsOSG      > MFWeakSingleSelectionModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<SingleSelectionModel *,
                      NoRefCountPolicy, nsOSG        > MFUncountedSingleSelectionModelPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecSingleSelectionModelPtr : 
    public PointerSField<SingleSelectionModel *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecSingleSelectionModelPtr : 
    public PointerSField<SingleSelectionModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakSingleSelectionModelPtr :
    public PointerSField<SingleSelectionModel *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedSingleSelectionModelPtr :
    public PointerSField<SingleSelectionModel *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecSingleSelectionModelPtr :
    public PointerMField<SingleSelectionModel *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecSingleSelectionModelPtr :
    public PointerMField<SingleSelectionModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakSingleSelectionModelPtr :
    public PointerMField<SingleSelectionModel *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedSingleSelectionModelPtr :
    public PointerMField<SingleSelectionModel *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSINGLESELECTIONMODELFIELDS_H_ */
