/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class SingleSelectionModel!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"



#include "OSGSingleSelectionModelEventSource.h" // EventSource Class

#include "OSGSingleSelectionModelBase.h"
#include "OSGSingleSelectionModel.h"
#include "OSGSingleSelectionModelEventSource.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::SingleSelectionModel
    A UI SingleSelectionModel.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var SingleSelectionModelEventSource * SingleSelectionModelBase::_sfEventSource
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<SingleSelectionModel *, nsOSG>::_type(
    "SingleSelectionModelPtr", 
    "FieldContainerPtr", 
    SingleSelectionModel::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(SingleSelectionModel *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           SingleSelectionModel *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           SingleSelectionModel *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void SingleSelectionModelBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecSingleSelectionModelEventSourcePtr::Description(
        SFUnrecSingleSelectionModelEventSourcePtr::getClassType(),
        "EventSource",
        "",
        EventSourceFieldId, EventSourceFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&SingleSelectionModel::editHandleEventSource),
        static_cast<FieldGetMethodSig >(&SingleSelectionModel::getHandleEventSource));

    oType.addInitialDesc(pDesc);
}


SingleSelectionModelBase::TypeObject SingleSelectionModelBase::_type(
    SingleSelectionModelBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    NULL,
    SingleSelectionModel::initMethod,
    SingleSelectionModel::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&SingleSelectionModel::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"SingleSelectionModel\"\n"
    "    parent=\"FieldContainer\"\n"
    "    library=\"ContribToolboxUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"abstract\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "A UI SingleSelectionModel.\n"
    "    <Field\n"
    "        name=\"EventSource\"\n"
    "        type=\"SingleSelectionModelEventSource\"\n"
    "        category=\"pointer\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        defaultValue=\"NULL\"\n"
    "        access=\"public\"\n"
    "    >\n"
    "    </Field>\n"
    "    <ProducedEvent\n"
    "        name=\"SelectionChanged\"\n"
    "        detailsType=\"SelectionEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "</FieldContainer>\n",
    "A UI SingleSelectionModel.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &SingleSelectionModelBase::getType(void)
{
    return _type;
}

const FieldContainerType &SingleSelectionModelBase::getType(void) const
{
    return _type;
}

UInt32 SingleSelectionModelBase::getContainerSize(void) const
{
    return sizeof(SingleSelectionModel);
}

/*------------------------- decorator get ------------------------------*/


//! Get the SingleSelectionModel::_sfEventSource field.
const SFUnrecSingleSelectionModelEventSourcePtr *SingleSelectionModelBase::getSFEventSource(void) const
{
    return &_sfEventSource;
}

SFUnrecSingleSelectionModelEventSourcePtr *SingleSelectionModelBase::editSFEventSource    (void)
{
    editSField(EventSourceFieldMask);

    return &_sfEventSource;
}






/*------------------------------ access -----------------------------------*/

SizeT SingleSelectionModelBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        returnValue += _sfEventSource.getBinSize();
    }

    return returnValue;
}

void SingleSelectionModelBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        _sfEventSource.copyToBin(pMem);
    }
}

void SingleSelectionModelBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        editSField(EventSourceFieldMask);
        _sfEventSource.copyFromBin(pMem);
    }
}




/*------------------------- constructors ----------------------------------*/

SingleSelectionModelBase::SingleSelectionModelBase(void) :
    Inherited(),
    _sfEventSource            (NULL)
{
}

SingleSelectionModelBase::SingleSelectionModelBase(const SingleSelectionModelBase &source) :
    Inherited(source),
    _sfEventSource            (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

SingleSelectionModelBase::~SingleSelectionModelBase(void)
{
}

void SingleSelectionModelBase::onCreate(const SingleSelectionModel *source)
{
    Inherited::onCreate(source);

    if(source)
    {
        SingleSelectionModel *pThis = static_cast<SingleSelectionModel *>(this);

        pThis->setEventSource(source->getEventSource());
    }
    
    {
        SingleSelectionModelEventSourceUnrecPtr evSrc = SingleSelectionModelEventSource::create();
        setEventSource( evSrc );
    }
}

GetFieldHandlePtr SingleSelectionModelBase::getHandleEventSource     (void) const
{
    SFUnrecSingleSelectionModelEventSourcePtr::GetHandlePtr returnValue(
        new  SFUnrecSingleSelectionModelEventSourcePtr::GetHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             const_cast<SingleSelectionModelBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr SingleSelectionModelBase::editHandleEventSource    (void)
{
    SFUnrecSingleSelectionModelEventSourcePtr::EditHandlePtr returnValue(
        new  SFUnrecSingleSelectionModelEventSourcePtr::EditHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&SingleSelectionModel::setEventSource,
                    static_cast<SingleSelectionModel *>(this), _1));

    editSField(EventSourceFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void SingleSelectionModelBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    SingleSelectionModel *pThis = static_cast<SingleSelectionModel *>(this);

    pThis->execSync(static_cast<SingleSelectionModel *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif



void SingleSelectionModelBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<SingleSelectionModel *>(this)->setEventSource(NULL);


}


OSG_END_NAMESPACE
