/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGPOPUPMENUFIELDS_H_
#define _OSGPOPUPMENUFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class PopupMenu;

OSG_GEN_CONTAINERPTR(PopupMenu);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<PopupMenu *, nsOSG> :
    public FieldTraitsFCPtrBase<PopupMenu *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<PopupMenu *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<PopupMenu *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecPopupMenuPtr"; 
}

template<> inline
const Char8 *FieldTraits<PopupMenu *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecPopupMenuPtr"; 
}

template<> inline
const Char8 *FieldTraits<PopupMenu *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakPopupMenuPtr"; 
}

template<> inline
const Char8 *FieldTraits<PopupMenu *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdPopupMenuPtr"; 
}

template<> inline
const Char8 *FieldTraits<PopupMenu *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecPopupMenuPtr"; 
}

template<> inline
const Char8 *FieldTraits<PopupMenu *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecPopupMenuPtr"; 
}

template<> inline
const Char8 *FieldTraits<PopupMenu *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakPopupMenuPtr"; 
}

template<> inline
const Char8 *FieldTraits<PopupMenu *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdPopupMenuPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<PopupMenu *,
                      RecordedRefCountPolicy, nsOSG  > SFRecPopupMenuPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<PopupMenu *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecPopupMenuPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<PopupMenu *,
                      WeakRefCountPolicy, nsOSG      > SFWeakPopupMenuPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<PopupMenu *,
                      NoRefCountPolicy, nsOSG        > SFUncountedPopupMenuPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<PopupMenu *,
                      RecordedRefCountPolicy, nsOSG  > MFRecPopupMenuPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<PopupMenu *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecPopupMenuPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<PopupMenu *,
                      WeakRefCountPolicy, nsOSG      > MFWeakPopupMenuPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<PopupMenu *,
                      NoRefCountPolicy, nsOSG        > MFUncountedPopupMenuPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecPopupMenuPtr : 
    public PointerSField<PopupMenu *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecPopupMenuPtr : 
    public PointerSField<PopupMenu *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakPopupMenuPtr :
    public PointerSField<PopupMenu *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedPopupMenuPtr :
    public PointerSField<PopupMenu *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecPopupMenuPtr :
    public PointerMField<PopupMenu *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecPopupMenuPtr :
    public PointerMField<PopupMenu *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakPopupMenuPtr :
    public PointerMField<PopupMenu *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedPopupMenuPtr :
    public PointerMField<PopupMenu *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGPOPUPMENUFIELDS_H_ */
