/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TBAnimation
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTBANIMATIONBASE_H_
#define _OSGTBANIMATIONBASE_H_
#ifdef __sgi
#pragma once
#endif


#include "OSGConfig.h"
#include "OSGContribToolboxAnimationDef.h"

//#include "OSGBaseTypes.h"

#include "OSGAttachmentContainer.h" // Parent

#include "OSGSysFields.h"               // Cycling type
#include "OSGTBAnimationEventSourceFields.h" // EventSource type

#include "OSGTBAnimationFields.h"

OSG_BEGIN_NAMESPACE


class TBAnimation;

//! \brief TBAnimation Base Class.

class OSG_CONTRIBTOOLBOXANIMATION_DLLMAPPING TBAnimationBase : public AttachmentContainer
{
  public:

    typedef AttachmentContainer Inherited;
    typedef AttachmentContainer ParentContainer;

    typedef Inherited::TypeObject TypeObject;
    typedef TypeObject::InitPhase InitPhase;

    OSG_GEN_INTERNALPTR(TBAnimation);

    /*==========================  PUBLIC  =================================*/

  public:

    enum
    {
        CyclingFieldId = Inherited::NextFieldId,
        ScaleFieldId = CyclingFieldId + 1,
        OffsetFieldId = ScaleFieldId + 1,
        SpanFieldId = OffsetFieldId + 1,
        CyclesFieldId = SpanFieldId + 1,
        EventSourceFieldId = CyclesFieldId + 1,
        NextFieldId = EventSourceFieldId + 1
    };

    static const OSG::BitVector CyclingFieldMask =
        (TypeTraits<BitVector>::One << CyclingFieldId);
    static const OSG::BitVector ScaleFieldMask =
        (TypeTraits<BitVector>::One << ScaleFieldId);
    static const OSG::BitVector OffsetFieldMask =
        (TypeTraits<BitVector>::One << OffsetFieldId);
    static const OSG::BitVector SpanFieldMask =
        (TypeTraits<BitVector>::One << SpanFieldId);
    static const OSG::BitVector CyclesFieldMask =
        (TypeTraits<BitVector>::One << CyclesFieldId);
    static const OSG::BitVector EventSourceFieldMask =
        (TypeTraits<BitVector>::One << EventSourceFieldId);
    static const OSG::BitVector NextFieldMask =
        (TypeTraits<BitVector>::One << NextFieldId);
        
    typedef SFInt32           SFCyclingType;
    typedef SFReal32          SFScaleType;
    typedef SFReal32          SFOffsetType;
    typedef SFReal32          SFSpanType;
    typedef SFReal32          SFCyclesType;
    typedef SFUnrecChildTBAnimationEventSourcePtr SFEventSourceType;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static FieldContainerType &getClassType   (void);
    static UInt32              getClassTypeId (void);
    static UInt16              getClassGroupId(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType         (void);
    virtual const FieldContainerType &getType         (void) const;

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */


                  SFInt32             *editSFCycling        (void);
            const SFInt32             *getSFCycling         (void) const;

                  SFReal32            *editSFScale          (void);
            const SFReal32            *getSFScale           (void) const;

                  SFReal32            *editSFOffset         (void);
            const SFReal32            *getSFOffset          (void) const;

                  SFReal32            *editSFSpan           (void);
            const SFReal32            *getSFSpan            (void) const;

                  SFReal32            *editSFCycles         (void);
            const SFReal32            *getSFCycles          (void) const;
            const SFUnrecChildTBAnimationEventSourcePtr *getSFEventSource    (void) const;
                  SFUnrecChildTBAnimationEventSourcePtr *editSFEventSource    (void);


                  Int32               &editCycling        (void);
                  Int32                getCycling         (void) const;

                  Real32              &editScale          (void);
                  Real32               getScale           (void) const;

                  Real32              &editOffset         (void);
                  Real32               getOffset          (void) const;

                  Real32              &editSpan           (void);
                  Real32               getSpan            (void) const;

                  Real32              &editCycles         (void);
                  Real32               getCycles          (void) const;

                  TBAnimationEventSource * getEventSource    (void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

            void setCycling        (const Int32 value);
            void setScale          (const Real32 value);
            void setOffset         (const Real32 value);
            void setSpan           (const Real32 value);
            void setCycles         (const Real32 value);
            void setEventSource    (TBAnimationEventSource * const value);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr Field Set                                 */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr MField Set                                */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual SizeT  getBinSize (ConstFieldMaskArg  whichField);
    virtual void   copyToBin  (BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);
    virtual void   copyFromBin(BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);


    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/

  protected:

    static TypeObject _type;

    static       void   classDescInserter(TypeObject &oType);
    static const Char8 *getClassname     (void             );

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    SFInt32           _sfCycling;
    SFReal32          _sfScale;
    SFReal32          _sfOffset;
    SFReal32          _sfSpan;
    SFReal32          _sfCycles;
    SFUnrecChildTBAnimationEventSourcePtr _sfEventSource;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    TBAnimationBase(void);
    TBAnimationBase(const TBAnimationBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~TBAnimationBase(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     onCreate                                */
    /*! \{                                                                 */

    void onCreate(const TBAnimation *source = NULL);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name Child linking                                                */
    /*! \{                                                                 */

    virtual bool unlinkChild(FieldContainer * const pChild,
                             UInt16           const childFieldId);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Generic Field Access                      */
    /*! \{                                                                 */

    GetFieldHandlePtr  getHandleCycling         (void) const;
    EditFieldHandlePtr editHandleCycling        (void);
    GetFieldHandlePtr  getHandleScale           (void) const;
    EditFieldHandlePtr editHandleScale          (void);
    GetFieldHandlePtr  getHandleOffset          (void) const;
    EditFieldHandlePtr editHandleOffset         (void);
    GetFieldHandlePtr  getHandleSpan            (void) const;
    EditFieldHandlePtr editHandleSpan           (void);
    GetFieldHandlePtr  getHandleCycles          (void) const;
    EditFieldHandlePtr editHandleCycles         (void);
    GetFieldHandlePtr  getHandleEventSource     (void) const;
    EditFieldHandlePtr editHandleEventSource    (void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual void execSyncV(      FieldContainer    &oFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);

            void execSync (      TBAnimationBase *pFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     Aspect Create                            */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */
    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    virtual void resolveLinks(void);

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/

  private:
    /*---------------------------------------------------------------------*/

    // prohibit default functions (move to 'public' if you need one)
    void operator =(const TBAnimationBase &source);
};

typedef TBAnimationBase *TBAnimationBaseP;

OSG_END_NAMESPACE

#endif /* _OSGTBANIMATIONBASE_H_ */
