/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTBANIMATIONEVENTSOURCEFIELDS_H_
#define _OSGTBANIMATIONEVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxAnimationDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TBAnimationEventSource;

OSG_GEN_CONTAINERPTR(TBAnimationEventSource);
/*! \ingroup GrpContribToolboxAnimationFieldTraits
    \ingroup GrpLibOSGContribToolboxAnimation
 */
template <>
struct FieldTraits<TBAnimationEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<TBAnimationEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TBAnimationEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXANIMATION_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TBAnimationEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTBAnimationEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimationEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTBAnimationEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimationEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTBAnimationEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimationEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTBAnimationEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimationEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTBAnimationEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimationEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTBAnimationEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimationEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTBAnimationEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimationEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTBAnimationEventSourcePtr"; 
}


/*! \ingroup GrpContribToolboxAnimationFieldTraits
 */
template <>
struct FieldTraits<TBAnimationEventSource *, nsOSG + 1> :
    public FieldTraitsFCPtrBase<TBAnimationEventSource *, nsOSG + 1>
{
  private:

  public:
    typedef FieldTraits<TBAnimationEventSource *, nsOSG + 1>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXANIMATION_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);
};

template<> inline
const Char8 *FieldTraits<TBAnimationEventSource *, nsOSG + 1>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecChildTBAnimationEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimationEventSource *, nsOSG + 1>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecChildTBAnimationEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimationEventSource *, nsOSG + 1>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakChildTBAnimationEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimationEventSource *, nsOSG + 1>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdChildTBAnimationEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimationEventSource *, nsOSG + 1>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecChildTBAnimationEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimationEventSource *, nsOSG + 1>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecChildTBAnimationEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimationEventSource *, nsOSG + 1>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakChildTBAnimationEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimationEventSource *, nsOSG + 1>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdChildTBAnimationEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxAnimationFieldSFields */
typedef PointerSField<TBAnimationEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTBAnimationEventSourcePtr;
/*! \ingroup GrpContribToolboxAnimationFieldSFields */
typedef PointerSField<TBAnimationEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTBAnimationEventSourcePtr;
/*! \ingroup GrpContribToolboxAnimationFieldSFields */
typedef PointerSField<TBAnimationEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTBAnimationEventSourcePtr;
/*! \ingroup GrpContribToolboxAnimationFieldSFields */
typedef PointerSField<TBAnimationEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTBAnimationEventSourcePtr;


/*! \ingroup GrpContribToolboxAnimationFieldMFields */
typedef PointerMField<TBAnimationEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTBAnimationEventSourcePtr;
/*! \ingroup GrpContribToolboxAnimationFieldMFields */
typedef PointerMField<TBAnimationEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTBAnimationEventSourcePtr;
/*! \ingroup GrpContribToolboxAnimationFieldMFields */
typedef PointerMField<TBAnimationEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTBAnimationEventSourcePtr;
/*! \ingroup GrpContribToolboxAnimationFieldMFields */
typedef PointerMField<TBAnimationEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTBAnimationEventSourcePtr;



/*! \ingroup GrpContribToolboxAnimationFieldSFields */
typedef ChildPointerSField<
          TBAnimationEventSource *, 
          UnrecordedRefCountPolicy,
          nsOSG + 1             > SFUnrecChildTBAnimationEventSourcePtr;



#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxAnimationFieldSFields \ingroup GrpLibOSGContribToolboxAnimation */
struct SFRecTBAnimationEventSourcePtr : 
    public PointerSField<TBAnimationEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxAnimationFieldSFields \ingroup GrpLibOSGContribToolboxAnimation */
struct SFUnrecTBAnimationEventSourcePtr : 
    public PointerSField<TBAnimationEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxAnimationFieldSFields \ingroup GrpLibOSGContribToolboxAnimation */
struct SFWeakTBAnimationEventSourcePtr :
    public PointerSField<TBAnimationEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxAnimationFieldSFields \ingroup GrpLibOSGContribToolboxAnimation */
struct SFUncountedTBAnimationEventSourcePtr :
    public PointerSField<TBAnimationEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxAnimationFieldMFields \ingroup GrpLibOSGContribToolboxAnimation */
struct MFRecTBAnimationEventSourcePtr :
    public PointerMField<TBAnimationEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxAnimationFieldMFields \ingroup GrpLibOSGContribToolboxAnimation */
struct MFUnrecTBAnimationEventSourcePtr :
    public PointerMField<TBAnimationEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxAnimationFieldMFields \ingroup GrpLibOSGContribToolboxAnimation */
struct MFWeakTBAnimationEventSourcePtr :
    public PointerMField<TBAnimationEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxAnimationFieldMFields \ingroup GrpLibOSGContribToolboxAnimation */
struct MFUncountedTBAnimationEventSourcePtr :
    public PointerMField<TBAnimationEventSource *,
                         NoRefCountPolicy        > {};



/*! \ingroup GrpContribToolboxAnimationFieldSFields \ingroup GrpLibOSGContribToolboxAnimation */
struct SFUnrecChildTBAnimationEventSourcePtr :
    public ChildPointerSField<
        TBAnimationEventSource *, 
        UnrecordedRefCountPolicy,
        nsOSG + 1             > {};


#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTBANIMATIONEVENTSOURCEFIELDS_H_ */
