/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TBAnimationEventSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"




#include "OSGTBAnimationEventSourceBase.h"
#include "OSGTBAnimationEventSource.h"

#include <boost/bind.hpp>

#include "OSGEventDetails.h"
#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TBAnimationEventSource
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<TBAnimationEventSource *, nsOSG>::_type(
    "TBAnimationEventSourcePtr", 
    "EventContainerPtr", 
    TBAnimationEventSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(TBAnimationEventSource *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TBAnimationEventSource *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TBAnimationEventSource *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TBAnimationEventSourceBase::classDescInserter(TypeObject &oType)
{
}


TBAnimationEventSourceBase::TypeObject TBAnimationEventSourceBase::_type(
    TBAnimationEventSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&TBAnimationEventSourceBase::createEmptyLocal),
    TBAnimationEventSource::initMethod,
    TBAnimationEventSource::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TBAnimationEventSource::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"TBAnimationEventSource\"\n"
    "    parent=\"EventContainer\"\n"
    "    library=\"ContribToolboxAnimation\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    ">\n"
    "<!--    \n"
    "    <ProducedEvent\n"
    "        name=\"AnimationStarted\"\n"
    "        detailsType=\"AnimationEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"AnimationStopped\"\n"
    "        detailsType=\"AnimationEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"AnimationPaused\"\n"
    "        detailsType=\"AnimationEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"AnimationUnpaused\"\n"
    "        detailsType=\"AnimationEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"AnimationEnded\"\n"
    "        detailsType=\"AnimationEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"AnimationCycled\"\n"
    "        detailsType=\"AnimationEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "-->\n"
    "</FieldContainer>\n",
    ""
    );

//! Animation Produced Events

EventDescription *TBAnimationBase::_eventDesc[] =
{
    new EventDescription("AnimationStarted", 
                          "",
                          AnimationStartedEventId, 
                          FieldTraits<AnimationEventDetails *>::getType(),
                          true,
                          static_cast<EventGetMethod>(&TBAnimationBase::getHandleAnimationStartedSignal)),

    new EventDescription("AnimationStopped", 
                          "",
                          AnimationStoppedEventId, 
                          FieldTraits<AnimationEventDetails *>::getType(),
                          true,
                          static_cast<EventGetMethod>(&TBAnimationBase::getHandleAnimationStoppedSignal)),

    new EventDescription("AnimationPaused", 
                          "",
                          AnimationPausedEventId, 
                          FieldTraits<AnimationEventDetails *>::getType(),
                          true,
                          static_cast<EventGetMethod>(&TBAnimationBase::getHandleAnimationPausedSignal)),

    new EventDescription("AnimationUnpaused", 
                          "",
                          AnimationUnpausedEventId, 
                          FieldTraits<AnimationEventDetails *>::getType(),
                          true,
                          static_cast<EventGetMethod>(&TBAnimationBase::getHandleAnimationUnpausedSignal)),

    new EventDescription("AnimationEnded", 
                          "",
                          AnimationEndedEventId, 
                          FieldTraits<AnimationEventDetails *>::getType(),
                          true,
                          static_cast<EventGetMethod>(&TBAnimationBase::getHandleAnimationEndedSignal)),

    new EventDescription("AnimationCycled", 
                          "",
                          AnimationCycledEventId, 
                          FieldTraits<AnimationEventDetails *>::getType(),
                          true,
                          static_cast<EventGetMethod>(&TBAnimationBase::getHandleAnimationCycledSignal))

};

EventProducerType TBAnimationEventSourceBase::_producerType(
    "AnimationProducerType",
    "EventProducerType",
    "",
    InitEventProducerFunctor(),
    _eventDesc,
    sizeof(_eventDesc));
/*------------------------------ get -----------------------------------*/

FieldContainerType &TBAnimationEventSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &TBAnimationEventSourceBase::getType(void) const
{
    return _type;
}

const EventProducerType &TBAnimationEventSourceBase::getProducerType(void) const
{
    return _producerType;
}

UInt32 TBAnimationEventSourceBase::getContainerSize(void) const
{
    return sizeof(TBAnimationEventSource);
}


/*------------------------- event producers ----------------------------------*/
void TBAnimationBase::produceEvent(UInt32 eventId, EventDetails* const e)
{
    switch(eventId)
    {
    case AnimationStartedEventId:
        OSG_ASSERT(dynamic_cast<AnimationStartedEventDetailsType* const>(e));

        _AnimationStartedEvent.set_combiner(ConsumableEventCombiner(e));
        _AnimationStartedEvent(dynamic_cast<AnimationStartedEventDetailsType* const>(e), AnimationStartedEventId);
        break;
    case AnimationStoppedEventId:
        OSG_ASSERT(dynamic_cast<AnimationStoppedEventDetailsType* const>(e));

        _AnimationStoppedEvent.set_combiner(ConsumableEventCombiner(e));
        _AnimationStoppedEvent(dynamic_cast<AnimationStoppedEventDetailsType* const>(e), AnimationStoppedEventId);
        break;
    case AnimationPausedEventId:
        OSG_ASSERT(dynamic_cast<AnimationPausedEventDetailsType* const>(e));

        _AnimationPausedEvent.set_combiner(ConsumableEventCombiner(e));
        _AnimationPausedEvent(dynamic_cast<AnimationPausedEventDetailsType* const>(e), AnimationPausedEventId);
        break;
    case AnimationUnpausedEventId:
        OSG_ASSERT(dynamic_cast<AnimationUnpausedEventDetailsType* const>(e));

        _AnimationUnpausedEvent.set_combiner(ConsumableEventCombiner(e));
        _AnimationUnpausedEvent(dynamic_cast<AnimationUnpausedEventDetailsType* const>(e), AnimationUnpausedEventId);
        break;
    case AnimationEndedEventId:
        OSG_ASSERT(dynamic_cast<AnimationEndedEventDetailsType* const>(e));

        _AnimationEndedEvent.set_combiner(ConsumableEventCombiner(e));
        _AnimationEndedEvent(dynamic_cast<AnimationEndedEventDetailsType* const>(e), AnimationEndedEventId);
        break;
    case AnimationCycledEventId:
        OSG_ASSERT(dynamic_cast<AnimationCycledEventDetailsType* const>(e));

        _AnimationCycledEvent.set_combiner(ConsumableEventCombiner(e));
        _AnimationCycledEvent(dynamic_cast<AnimationCycledEventDetailsType* const>(e), AnimationCycledEventId);
        break;
    default:
        SWARNING << "No event defined with ID " << eventId << std::endl;
        break;
    }
}

boost::signals2::connection TBAnimationBase::connectEvent(UInt32 eventId, 
                                                             const BaseEventType::slot_type &listener, 
                                                             boost::signals2::connect_position at)
{
    switch(eventId)
    {
    case AnimationStartedEventId:
        return _AnimationStartedEvent.connect(listener, at);
        break;
    case AnimationStoppedEventId:
        return _AnimationStoppedEvent.connect(listener, at);
        break;
    case AnimationPausedEventId:
        return _AnimationPausedEvent.connect(listener, at);
        break;
    case AnimationUnpausedEventId:
        return _AnimationUnpausedEvent.connect(listener, at);
        break;
    case AnimationEndedEventId:
        return _AnimationEndedEvent.connect(listener, at);
        break;
    case AnimationCycledEventId:
        return _AnimationCycledEvent.connect(listener, at);
        break;
    default:
        SWARNING << "No event defined with ID " << eventId << std::endl;
        return boost::signals2::connection();
        break;
    }

    return boost::signals2::connection();
}

boost::signals2::connection  TBAnimationBase::connectEvent(UInt32 eventId, 
                                                              const BaseEventType::group_type &group,
                                                              const BaseEventType::slot_type &listener,
                                                              boost::signals2::connect_position at)
{
    switch(eventId)
    {
    case AnimationStartedEventId:
        return _AnimationStartedEvent.connect(group, listener, at);
        break;
    case AnimationStoppedEventId:
        return _AnimationStoppedEvent.connect(group, listener, at);
        break;
    case AnimationPausedEventId:
        return _AnimationPausedEvent.connect(group, listener, at);
        break;
    case AnimationUnpausedEventId:
        return _AnimationUnpausedEvent.connect(group, listener, at);
        break;
    case AnimationEndedEventId:
        return _AnimationEndedEvent.connect(group, listener, at);
        break;
    case AnimationCycledEventId:
        return _AnimationCycledEvent.connect(group, listener, at);
        break;
    default:
        SWARNING << "No event defined with ID " << eventId << std::endl;
        return boost::signals2::connection();
        break;
    }

    return boost::signals2::connection();
}
    
void  TBAnimationBase::disconnectEvent(UInt32 eventId, const BaseEventType::group_type &group)
{
    switch(eventId)
    {
    case AnimationStartedEventId:
        _AnimationStartedEvent.disconnect(group);
        break;
    case AnimationStoppedEventId:
        _AnimationStoppedEvent.disconnect(group);
        break;
    case AnimationPausedEventId:
        _AnimationPausedEvent.disconnect(group);
        break;
    case AnimationUnpausedEventId:
        _AnimationUnpausedEvent.disconnect(group);
        break;
    case AnimationEndedEventId:
        _AnimationEndedEvent.disconnect(group);
        break;
    case AnimationCycledEventId:
        _AnimationCycledEvent.disconnect(group);
        break;
    default:
        SWARNING << "No event defined with ID " << eventId << std::endl;
        break;
    }
}

void  TBAnimationBase::disconnectAllSlotsEvent(UInt32 eventId)
{
    switch(eventId)
    {
    case AnimationStartedEventId:
        _AnimationStartedEvent.disconnect_all_slots();
        break;
    case AnimationStoppedEventId:
        _AnimationStoppedEvent.disconnect_all_slots();
        break;
    case AnimationPausedEventId:
        _AnimationPausedEvent.disconnect_all_slots();
        break;
    case AnimationUnpausedEventId:
        _AnimationUnpausedEvent.disconnect_all_slots();
        break;
    case AnimationEndedEventId:
        _AnimationEndedEvent.disconnect_all_slots();
        break;
    case AnimationCycledEventId:
        _AnimationCycledEvent.disconnect_all_slots();
        break;
    default:
        SWARNING << "No event defined with ID " << eventId << std::endl;
        break;
    }
}

bool  TBAnimationBase::isEmptyEvent(UInt32 eventId) const
{
    switch(eventId)
    {
    case AnimationStartedEventId:
        return _AnimationStartedEvent.empty();
        break;
    case AnimationStoppedEventId:
        return _AnimationStoppedEvent.empty();
        break;
    case AnimationPausedEventId:
        return _AnimationPausedEvent.empty();
        break;
    case AnimationUnpausedEventId:
        return _AnimationUnpausedEvent.empty();
        break;
    case AnimationEndedEventId:
        return _AnimationEndedEvent.empty();
        break;
    case AnimationCycledEventId:
        return _AnimationCycledEvent.empty();
        break;
    default:
        SWARNING << "No event defined with ID " << eventId << std::endl;
        return true;
        break;
    }
}

UInt32  TBAnimationBase::numSlotsEvent(UInt32 eventId) const
{
    switch(eventId)
    {
    case AnimationStartedEventId:
        return _AnimationStartedEvent.num_slots();
        break;
    case AnimationStoppedEventId:
        return _AnimationStoppedEvent.num_slots();
        break;
    case AnimationPausedEventId:
        return _AnimationPausedEvent.num_slots();
        break;
    case AnimationUnpausedEventId:
        return _AnimationUnpausedEvent.num_slots();
        break;
    case AnimationEndedEventId:
        return _AnimationEndedEvent.num_slots();
        break;
    case AnimationCycledEventId:
        return _AnimationCycledEvent.num_slots();
        break;
    default:
        SWARNING << "No event defined with ID " << eventId << std::endl;
        return 0;
        break;
    }
}






/*------------------------------ access -----------------------------------*/

SizeT TBAnimationEventSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void TBAnimationEventSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void TBAnimationEventSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
TBAnimationEventSourceTransitPtr TBAnimationEventSourceBase::createLocal(BitVector bFlags)
{
    TBAnimationEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<TBAnimationEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
TBAnimationEventSourceTransitPtr TBAnimationEventSourceBase::createDependent(BitVector bFlags)
{
    TBAnimationEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<TBAnimationEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
TBAnimationEventSourceTransitPtr TBAnimationEventSourceBase::create(void)
{
    TBAnimationEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<TBAnimationEventSource>(tmpPtr);
    }

    return fc;
}

TBAnimationEventSource *TBAnimationEventSourceBase::createEmptyLocal(BitVector bFlags)
{
    TBAnimationEventSource *returnValue;

    newPtr<TBAnimationEventSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
TBAnimationEventSource *TBAnimationEventSourceBase::createEmpty(void)
{
    TBAnimationEventSource *returnValue;

    newPtr<TBAnimationEventSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr TBAnimationEventSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    TBAnimationEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TBAnimationEventSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr TBAnimationEventSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    TBAnimationEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TBAnimationEventSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr TBAnimationEventSourceBase::shallowCopy(void) const
{
    TBAnimationEventSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const TBAnimationEventSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

TBAnimationEventSourceBase::TBAnimationEventSourceBase(void) :
    Inherited()
{
}

TBAnimationEventSourceBase::TBAnimationEventSourceBase(const TBAnimationEventSourceBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

TBAnimationEventSourceBase::~TBAnimationEventSourceBase(void)
{
}


GetEventHandlePtr TBAnimationBase::getHandleAnimationStartedSignal(void) const
{
    GetEventHandlePtr returnValue(
        new  GetTypedEventHandle<AnimationStartedEventType>(
             const_cast<AnimationStartedEventType *>(&_AnimationStartedEvent),
             _producerType.getEventDescription(AnimationStartedEventId),
             const_cast<TBAnimationBase *>(this)));

    return returnValue;
}

GetEventHandlePtr TBAnimationBase::getHandleAnimationStoppedSignal(void) const
{
    GetEventHandlePtr returnValue(
        new  GetTypedEventHandle<AnimationStoppedEventType>(
             const_cast<AnimationStoppedEventType *>(&_AnimationStoppedEvent),
             _producerType.getEventDescription(AnimationStoppedEventId),
             const_cast<TBAnimationBase *>(this)));

    return returnValue;
}

GetEventHandlePtr TBAnimationBase::getHandleAnimationPausedSignal(void) const
{
    GetEventHandlePtr returnValue(
        new  GetTypedEventHandle<AnimationPausedEventType>(
             const_cast<AnimationPausedEventType *>(&_AnimationPausedEvent),
             _producerType.getEventDescription(AnimationPausedEventId),
             const_cast<TBAnimationBase *>(this)));

    return returnValue;
}

GetEventHandlePtr TBAnimationBase::getHandleAnimationUnpausedSignal(void) const
{
    GetEventHandlePtr returnValue(
        new  GetTypedEventHandle<AnimationUnpausedEventType>(
             const_cast<AnimationUnpausedEventType *>(&_AnimationUnpausedEvent),
             _producerType.getEventDescription(AnimationUnpausedEventId),
             const_cast<TBAnimationBase *>(this)));

    return returnValue;
}

GetEventHandlePtr TBAnimationBase::getHandleAnimationEndedSignal(void) const
{
    GetEventHandlePtr returnValue(
        new  GetTypedEventHandle<AnimationEndedEventType>(
             const_cast<AnimationEndedEventType *>(&_AnimationEndedEvent),
             _producerType.getEventDescription(AnimationEndedEventId),
             const_cast<TBAnimationBase *>(this)));

    return returnValue;
}

GetEventHandlePtr TBAnimationBase::getHandleAnimationCycledSignal(void) const
{
    GetEventHandlePtr returnValue(
        new  GetTypedEventHandle<AnimationCycledEventType>(
             const_cast<AnimationCycledEventType *>(&_AnimationCycledEvent),
             _producerType.getEventDescription(AnimationCycledEventId),
             const_cast<TBAnimationBase *>(this)));

    return returnValue;
}

#ifdef OSG_MT_CPTR_ASPECT
void TBAnimationEventSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TBAnimationEventSource *pThis = static_cast<TBAnimationEventSource *>(this);

    pThis->execSync(static_cast<TBAnimationEventSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *TBAnimationEventSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    TBAnimationEventSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const TBAnimationEventSource *>(pRefAspect),
                  dynamic_cast<const TBAnimationEventSource *>(this));

    return returnValue;
}
#endif

void TBAnimationEventSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
