/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTBANIMATIONFIELDS_H_
#define _OSGTBANIMATIONFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxAnimationDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TBAnimation;

OSG_GEN_CONTAINERPTR(TBAnimation);
/*! \ingroup GrpContribToolboxAnimationFieldTraits
    \ingroup GrpLibOSGContribToolboxAnimation
 */
template <>
struct FieldTraits<TBAnimation *, nsOSG> :
    public FieldTraitsFCPtrBase<TBAnimation *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TBAnimation *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXANIMATION_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TBAnimation *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTBAnimationPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimation *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTBAnimationPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimation *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTBAnimationPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimation *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTBAnimationPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimation *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTBAnimationPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimation *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTBAnimationPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimation *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTBAnimationPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBAnimation *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTBAnimationPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxAnimationFieldSFields */
typedef PointerSField<TBAnimation *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTBAnimationPtr;
/*! \ingroup GrpContribToolboxAnimationFieldSFields */
typedef PointerSField<TBAnimation *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTBAnimationPtr;
/*! \ingroup GrpContribToolboxAnimationFieldSFields */
typedef PointerSField<TBAnimation *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTBAnimationPtr;
/*! \ingroup GrpContribToolboxAnimationFieldSFields */
typedef PointerSField<TBAnimation *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTBAnimationPtr;


/*! \ingroup GrpContribToolboxAnimationFieldMFields */
typedef PointerMField<TBAnimation *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTBAnimationPtr;
/*! \ingroup GrpContribToolboxAnimationFieldMFields */
typedef PointerMField<TBAnimation *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTBAnimationPtr;
/*! \ingroup GrpContribToolboxAnimationFieldMFields */
typedef PointerMField<TBAnimation *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTBAnimationPtr;
/*! \ingroup GrpContribToolboxAnimationFieldMFields */
typedef PointerMField<TBAnimation *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTBAnimationPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxAnimationFieldSFields \ingroup GrpLibOSGContribToolboxAnimation */
struct SFRecTBAnimationPtr : 
    public PointerSField<TBAnimation *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxAnimationFieldSFields \ingroup GrpLibOSGContribToolboxAnimation */
struct SFUnrecTBAnimationPtr : 
    public PointerSField<TBAnimation *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxAnimationFieldSFields \ingroup GrpLibOSGContribToolboxAnimation */
struct SFWeakTBAnimationPtr :
    public PointerSField<TBAnimation *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxAnimationFieldSFields \ingroup GrpLibOSGContribToolboxAnimation */
struct SFUncountedTBAnimationPtr :
    public PointerSField<TBAnimation *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxAnimationFieldMFields \ingroup GrpLibOSGContribToolboxAnimation */
struct MFRecTBAnimationPtr :
    public PointerMField<TBAnimation *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxAnimationFieldMFields \ingroup GrpLibOSGContribToolboxAnimation */
struct MFUnrecTBAnimationPtr :
    public PointerMField<TBAnimation *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxAnimationFieldMFields \ingroup GrpLibOSGContribToolboxAnimation */
struct MFWeakTBAnimationPtr :
    public PointerMField<TBAnimation *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxAnimationFieldMFields \ingroup GrpLibOSGContribToolboxAnimation */
struct MFUncountedTBAnimationPtr :
    public PointerMField<TBAnimation *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTBANIMATIONFIELDS_H_ */
