/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TBAnimationEventSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"



#include "OSGTBAnimation.h"             // Parent Class

#include "OSGTBAnimationEventSourceBase.h"
#include "OSGTBAnimationEventSource.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TBAnimationEventSource
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var TBAnimation *   TBAnimationEventSourceBase::_sfParent
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<TBAnimationEventSource *, nsOSG>::_type(
    "TBAnimationEventSourcePtr", 
    "EventContainerPtr", 
    TBAnimationEventSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(TBAnimationEventSource *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TBAnimationEventSource *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TBAnimationEventSource *,
                           nsOSG);

DataType &FieldTraits< TBAnimationEventSource *, nsOSG + 1 >::getType(void)
{
    return FieldTraits<TBAnimationEventSource *, nsOSG>::getType();
}


OSG_EXPORT_PTR_SFIELD(ChildPointerSField,
                      TBAnimationEventSource *,
                      UnrecordedRefCountPolicy,
                      nsOSG + 1);


/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TBAnimationEventSourceBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFParentTBAnimationPtr::Description(
        SFParentTBAnimationPtr::getClassType(),
        "Parent",
        "",
        ParentFieldId, ParentFieldMask,
        true,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast     <FieldEditMethodSig>(&TBAnimationEventSource::invalidEditField),
        static_cast     <FieldGetMethodSig >(&TBAnimationEventSource::invalidGetField));

    oType.addInitialDesc(pDesc);
}


TBAnimationEventSourceBase::TypeObject TBAnimationEventSourceBase::_type(
    TBAnimationEventSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&TBAnimationEventSourceBase::createEmptyLocal),
    TBAnimationEventSource::initMethod,
    TBAnimationEventSource::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TBAnimationEventSource::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"TBAnimationEventSource\"\n"
    "    parent=\"EventContainer\"\n"
    "    library=\"ContribToolboxAnimation\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    childFields=\"single\"\n"
    ">\n"
    "    <Field\n"
    "        name=\"Parent\"\n"
    "        category=\"parentpointer\"\n"
    "        type=\"TBAnimation\"\n"
    "        cardinality=\"single\"\n"
    "        access=\"none\"\n"
    "        visibility=\"internal\"\n"
    "        >\n"
    "    </Field>\n"
    "<!--    \n"
    "    <ProducedEvent\n"
    "        name=\"AnimationStarted\"\n"
    "        detailsType=\"AnimationEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"AnimationStopped\"\n"
    "        detailsType=\"AnimationEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"AnimationPaused\"\n"
    "        detailsType=\"AnimationEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"AnimationUnpaused\"\n"
    "        detailsType=\"AnimationEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"AnimationEnded\"\n"
    "        detailsType=\"AnimationEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"AnimationCycled\"\n"
    "        detailsType=\"AnimationEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "-->\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TBAnimationEventSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &TBAnimationEventSourceBase::getType(void) const
{
    return _type;
}

UInt32 TBAnimationEventSourceBase::getContainerSize(void) const
{
    return sizeof(TBAnimationEventSource);
}

/*------------------------- decorator get ------------------------------*/







/*------------------------------ access -----------------------------------*/

SizeT TBAnimationEventSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (ParentFieldMask & whichField))
    {
        returnValue += _sfParent.getBinSize();
    }

    return returnValue;
}

void TBAnimationEventSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (ParentFieldMask & whichField))
    {
        _sfParent.copyToBin(pMem);
    }
}

void TBAnimationEventSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (ParentFieldMask & whichField))
    {
        editSField(ParentFieldMask);
        _sfParent.copyFromBin(pMem);
    }
}

//! create a new instance of the class
TBAnimationEventSourceTransitPtr TBAnimationEventSourceBase::createLocal(BitVector bFlags)
{
    TBAnimationEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<TBAnimationEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
TBAnimationEventSourceTransitPtr TBAnimationEventSourceBase::createDependent(BitVector bFlags)
{
    TBAnimationEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<TBAnimationEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
TBAnimationEventSourceTransitPtr TBAnimationEventSourceBase::create(void)
{
    TBAnimationEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<TBAnimationEventSource>(tmpPtr);
    }

    return fc;
}

TBAnimationEventSource *TBAnimationEventSourceBase::createEmptyLocal(BitVector bFlags)
{
    TBAnimationEventSource *returnValue;

    newPtr<TBAnimationEventSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
TBAnimationEventSource *TBAnimationEventSourceBase::createEmpty(void)
{
    TBAnimationEventSource *returnValue;

    newPtr<TBAnimationEventSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr TBAnimationEventSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    TBAnimationEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TBAnimationEventSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr TBAnimationEventSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    TBAnimationEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TBAnimationEventSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr TBAnimationEventSourceBase::shallowCopy(void) const
{
    TBAnimationEventSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const TBAnimationEventSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

TBAnimationEventSourceBase::TBAnimationEventSourceBase(void) :
    Inherited(),
    _sfParent                 (NULL)
{
}

TBAnimationEventSourceBase::TBAnimationEventSourceBase(const TBAnimationEventSourceBase &source) :
    Inherited(source),
    _sfParent                 (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

TBAnimationEventSourceBase::~TBAnimationEventSourceBase(void)
{
}
/*-------------------------------------------------------------------------*/
/* Parent linking                                                          */

bool TBAnimationEventSourceBase::linkParent(
    FieldContainer * const pParent,
    UInt16           const childFieldId,
    UInt16           const parentFieldId )
{
    if(parentFieldId == ParentFieldId)
    {
        TBAnimation * pTypedParent =
            dynamic_cast< TBAnimation * >(pParent);

        if(pTypedParent != NULL)
        {
            FieldContainer *pOldParent =
                _sfParent.getValue         ();

            UInt16 oldChildFieldId =
                _sfParent.getParentFieldPos();

            if(pOldParent != NULL)
            {
                pOldParent->unlinkChild(this, oldChildFieldId);
            }

            editSField(ParentFieldMask);

            _sfParent.setValue(static_cast<TBAnimation *>(pParent), childFieldId);

            return true;
        }

        return false;
    }

    return Inherited::linkParent(pParent, childFieldId, parentFieldId);
}

bool TBAnimationEventSourceBase::unlinkParent(
    FieldContainer * const pParent,
    UInt16           const parentFieldId)
{
    if(parentFieldId == ParentFieldId)
    {
        TBAnimation * pTypedParent =
            dynamic_cast< TBAnimation * >(pParent);

        if(pTypedParent != NULL)
        {
            if(_sfParent.getValue() == pTypedParent)
            {
                editSField(ParentFieldMask);

                _sfParent.setValue(NULL, 0xFFFF);

                return true;
            }

            SWARNING << "Child (["          << this
                     << "] id ["            << this->getId()
                     << "] type ["          << this->getType().getCName()
                     << "] parentFieldId [" << parentFieldId
                     << "]) - Parent (["    << pParent
                     << "] id ["            << pParent->getId()
                     << "] type ["          << pParent->getType().getCName()
                     << "]): link inconsistent!"
                     << std::endl;

            return false;
        }

        return false;
    }

    return Inherited::unlinkParent(pParent, parentFieldId);
}



GetFieldHandlePtr TBAnimationEventSourceBase::getHandleParent          (void) const
{
    SFParentTBAnimationPtr::GetHandlePtr returnValue;

    return returnValue;
}

EditFieldHandlePtr TBAnimationEventSourceBase::editHandleParent         (void)
{
    EditFieldHandlePtr returnValue;

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void TBAnimationEventSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TBAnimationEventSource *pThis = static_cast<TBAnimationEventSource *>(this);

    pThis->execSync(static_cast<TBAnimationEventSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *TBAnimationEventSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    TBAnimationEventSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const TBAnimationEventSource *>(pRefAspect),
                  dynamic_cast<const TBAnimationEventSource *>(this));

    return returnValue;
}
#endif

void TBAnimationEventSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
