/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TBQT4WindowHelper!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"




#include "OSGTBQT4WindowHelperBase.h"
#include "OSGTBQT4WindowHelper.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TBQT4WindowHelper
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<TBQT4WindowHelper *, nsOSG>::_type(
    "TBQT4WindowHelperPtr", 
    "QT4WindowPtr", 
    TBQT4WindowHelper::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(TBQT4WindowHelper *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TBQT4WindowHelper *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TBQT4WindowHelper *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TBQT4WindowHelperBase::classDescInserter(TypeObject &oType)
{
}


TBQT4WindowHelperBase::TypeObject TBQT4WindowHelperBase::_type(
    TBQT4WindowHelperBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&TBQT4WindowHelperBase::createEmptyLocal),
    TBQT4WindowHelper::initMethod,
    TBQT4WindowHelper::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TBQT4WindowHelper::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"TBQT4WindowHelper\"\n"
    "    parent=\"QT4Window\"\n"
    "    library=\"ContribToolboxQt\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    >\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TBQT4WindowHelperBase::getType(void)
{
    return _type;
}

const FieldContainerType &TBQT4WindowHelperBase::getType(void) const
{
    return _type;
}

UInt32 TBQT4WindowHelperBase::getContainerSize(void) const
{
    return sizeof(TBQT4WindowHelper);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

SizeT TBQT4WindowHelperBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void TBQT4WindowHelperBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void TBQT4WindowHelperBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
TBQT4WindowHelperTransitPtr TBQT4WindowHelperBase::createLocal(BitVector bFlags)
{
    TBQT4WindowHelperTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<TBQT4WindowHelper>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
TBQT4WindowHelperTransitPtr TBQT4WindowHelperBase::createDependent(BitVector bFlags)
{
    TBQT4WindowHelperTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<TBQT4WindowHelper>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
TBQT4WindowHelperTransitPtr TBQT4WindowHelperBase::create(void)
{
    TBQT4WindowHelperTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<TBQT4WindowHelper>(tmpPtr);
    }

    return fc;
}

TBQT4WindowHelper *TBQT4WindowHelperBase::createEmptyLocal(BitVector bFlags)
{
    TBQT4WindowHelper *returnValue;

    newPtr<TBQT4WindowHelper>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
TBQT4WindowHelper *TBQT4WindowHelperBase::createEmpty(void)
{
    TBQT4WindowHelper *returnValue;

    newPtr<TBQT4WindowHelper>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr TBQT4WindowHelperBase::shallowCopyLocal(
    BitVector bFlags) const
{
    TBQT4WindowHelper *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TBQT4WindowHelper *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr TBQT4WindowHelperBase::shallowCopyDependent(
    BitVector bFlags) const
{
    TBQT4WindowHelper *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TBQT4WindowHelper *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr TBQT4WindowHelperBase::shallowCopy(void) const
{
    TBQT4WindowHelper *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const TBQT4WindowHelper *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

TBQT4WindowHelperBase::TBQT4WindowHelperBase(void) :
    Inherited()
{
}

TBQT4WindowHelperBase::TBQT4WindowHelperBase(const TBQT4WindowHelperBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

TBQT4WindowHelperBase::~TBQT4WindowHelperBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void TBQT4WindowHelperBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TBQT4WindowHelper *pThis = static_cast<TBQT4WindowHelper *>(this);

    pThis->execSync(static_cast<TBQT4WindowHelper *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *TBQT4WindowHelperBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    TBQT4WindowHelper *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const TBQT4WindowHelper *>(pRefAspect),
                  dynamic_cast<const TBQT4WindowHelper *>(this));

    return returnValue;
}
#endif

void TBQT4WindowHelperBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
