/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTBQT4WINDOWHELPERFIELDS_H_
#define _OSGTBQT4WINDOWHELPERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxQtDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TBQT4WindowHelper;

OSG_GEN_CONTAINERPTR(TBQT4WindowHelper);
/*! \ingroup GrpContribToolboxQtFieldTraits
    \ingroup GrpLibOSGContribToolboxQt
 */
template <>
struct FieldTraits<TBQT4WindowHelper *, nsOSG> :
    public FieldTraitsFCPtrBase<TBQT4WindowHelper *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TBQT4WindowHelper *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXQT_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TBQT4WindowHelper *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTBQT4WindowHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBQT4WindowHelper *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTBQT4WindowHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBQT4WindowHelper *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTBQT4WindowHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBQT4WindowHelper *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTBQT4WindowHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBQT4WindowHelper *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTBQT4WindowHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBQT4WindowHelper *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTBQT4WindowHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBQT4WindowHelper *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTBQT4WindowHelperPtr"; 
}

template<> inline
const Char8 *FieldTraits<TBQT4WindowHelper *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTBQT4WindowHelperPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxQtFieldSFields */
typedef PointerSField<TBQT4WindowHelper *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTBQT4WindowHelperPtr;
/*! \ingroup GrpContribToolboxQtFieldSFields */
typedef PointerSField<TBQT4WindowHelper *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTBQT4WindowHelperPtr;
/*! \ingroup GrpContribToolboxQtFieldSFields */
typedef PointerSField<TBQT4WindowHelper *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTBQT4WindowHelperPtr;
/*! \ingroup GrpContribToolboxQtFieldSFields */
typedef PointerSField<TBQT4WindowHelper *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTBQT4WindowHelperPtr;


/*! \ingroup GrpContribToolboxQtFieldMFields */
typedef PointerMField<TBQT4WindowHelper *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTBQT4WindowHelperPtr;
/*! \ingroup GrpContribToolboxQtFieldMFields */
typedef PointerMField<TBQT4WindowHelper *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTBQT4WindowHelperPtr;
/*! \ingroup GrpContribToolboxQtFieldMFields */
typedef PointerMField<TBQT4WindowHelper *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTBQT4WindowHelperPtr;
/*! \ingroup GrpContribToolboxQtFieldMFields */
typedef PointerMField<TBQT4WindowHelper *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTBQT4WindowHelperPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxQtFieldSFields \ingroup GrpLibOSGContribToolboxQt */
struct SFRecTBQT4WindowHelperPtr : 
    public PointerSField<TBQT4WindowHelper *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxQtFieldSFields \ingroup GrpLibOSGContribToolboxQt */
struct SFUnrecTBQT4WindowHelperPtr : 
    public PointerSField<TBQT4WindowHelper *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxQtFieldSFields \ingroup GrpLibOSGContribToolboxQt */
struct SFWeakTBQT4WindowHelperPtr :
    public PointerSField<TBQT4WindowHelper *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxQtFieldSFields \ingroup GrpLibOSGContribToolboxQt */
struct SFUncountedTBQT4WindowHelperPtr :
    public PointerSField<TBQT4WindowHelper *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxQtFieldMFields \ingroup GrpLibOSGContribToolboxQt */
struct MFRecTBQT4WindowHelperPtr :
    public PointerMField<TBQT4WindowHelper *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxQtFieldMFields \ingroup GrpLibOSGContribToolboxQt */
struct MFUnrecTBQT4WindowHelperPtr :
    public PointerMField<TBQT4WindowHelper *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxQtFieldMFields \ingroup GrpLibOSGContribToolboxQt */
struct MFWeakTBQT4WindowHelperPtr :
    public PointerMField<TBQT4WindowHelper *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxQtFieldMFields \ingroup GrpLibOSGContribToolboxQt */
struct MFUncountedTBQT4WindowHelperPtr :
    public PointerMField<TBQT4WindowHelper *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTBQT4WINDOWHELPERFIELDS_H_ */
