/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class CellEditorEventSource!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"


#include "OSGCellEditorEventSourceBase.h"
#include "OSGCellEditorEventSource.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::CellEditorEventSource
    A UI Cell Editor.
 */



/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<CellEditorEventSource *, nsOSG>::_type(
    "CellEditorEventSourcePtr",
    "EventContainerPtr",
    CellEditorEventSource::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(CellEditorEventSource *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           CellEditorEventSource *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           CellEditorEventSource *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void CellEditorEventSourceBase::classDescInserter(TypeObject &oType)
{
}


CellEditorEventSourceBase::TypeObject CellEditorEventSourceBase::_type(
    CellEditorEventSourceBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&CellEditorEventSourceBase::createEmptyLocal),
    CellEditorEventSource::initMethod,
    CellEditorEventSource::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&CellEditorEventSource::classDescInserter),
    false,
    0,
    "",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &CellEditorEventSourceBase::getType(void)
{
    return _type;
}

const FieldContainerType &CellEditorEventSourceBase::getType(void) const
{
    return _type;
}

UInt32 CellEditorEventSourceBase::getContainerSize(void) const
{
    return sizeof(CellEditorEventSource);
}



/*------------------------------ access -----------------------------------*/

SizeT CellEditorEventSourceBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    return returnValue;
}

void CellEditorEventSourceBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);
}

void CellEditorEventSourceBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);
}

//! create a new instance of the class
CellEditorEventSourceTransitPtr CellEditorEventSourceBase::createLocal(BitVector bFlags)
{
    CellEditorEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<CellEditorEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
CellEditorEventSourceTransitPtr CellEditorEventSourceBase::createDependent(BitVector bFlags)
{
    CellEditorEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<CellEditorEventSource>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
CellEditorEventSourceTransitPtr CellEditorEventSourceBase::create(void)
{
    CellEditorEventSourceTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<CellEditorEventSource>(tmpPtr);
    }

    return fc;
}

CellEditorEventSource *CellEditorEventSourceBase::createEmptyLocal(BitVector bFlags)
{
    CellEditorEventSource *returnValue;

    newPtr<CellEditorEventSource>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
CellEditorEventSource *CellEditorEventSourceBase::createEmpty(void)
{
    CellEditorEventSource *returnValue;

    newPtr<CellEditorEventSource>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr CellEditorEventSourceBase::shallowCopyLocal(
    BitVector bFlags) const
{
    CellEditorEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const CellEditorEventSource *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr CellEditorEventSourceBase::shallowCopyDependent(
    BitVector bFlags) const
{
    CellEditorEventSource *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const CellEditorEventSource *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr CellEditorEventSourceBase::shallowCopy(void) const
{
    CellEditorEventSource *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const CellEditorEventSource *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

CellEditorEventSourceBase::CellEditorEventSourceBase(void) :
    Inherited()
{
}

CellEditorEventSourceBase::CellEditorEventSourceBase(const CellEditorEventSourceBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

CellEditorEventSourceBase::~CellEditorEventSourceBase(void)
{
}


#ifdef OSG_MT_CPTR_ASPECT
void CellEditorEventSourceBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    CellEditorEventSource *pThis = static_cast<CellEditorEventSource *>(this);

    pThis->execSync(static_cast<CellEditorEventSource *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *CellEditorEventSourceBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    CellEditorEventSource *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const CellEditorEventSource *>(pRefAspect),
                  dynamic_cast<const CellEditorEventSource *>(this));

    return returnValue;
}
#endif

void CellEditorEventSourceBase::resolveLinks(void)
{
    Inherited::resolveLinks();

}

OSG_END_NAMESPACE
