/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class CellEditor!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"



#include "OSGCellEditorEventSource.h"   // EventSource Class

#include "OSGCellEditorBase.h"
#include "OSGCellEditor.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::CellEditor
    A UI Cell Editor.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var CellEditorEventSource * CellEditorBase::_sfEventSource
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<CellEditor *, nsOSG>::_type(
    "CellEditorPtr", 
    "FieldContainerPtr", 
    CellEditor::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(CellEditor *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           CellEditor *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           CellEditor *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void CellEditorBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecCellEditorEventSourcePtr::Description(
        SFUnrecCellEditorEventSourcePtr::getClassType(),
        "EventSource",
        "",
        EventSourceFieldId, EventSourceFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&CellEditor::editHandleEventSource),
        static_cast<FieldGetMethodSig >(&CellEditor::getHandleEventSource));

    oType.addInitialDesc(pDesc);
}


CellEditorBase::TypeObject CellEditorBase::_type(
    CellEditorBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    NULL,
    CellEditor::initMethod,
    CellEditor::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&CellEditor::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"CellEditor\"\n"
    "    parent=\"FieldContainer\"\n"
    "    library=\"ContribToolboxUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"abstract\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "A UI Cell Editor.\n"
    "    <Field\n"
    "        name=\"EventSource\"\n"
    "        type=\"CellEditorEventSource\"\n"
    "        category=\"pointer\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        defaultValue=\"NULL\"\n"
    "        access=\"public\"\n"
    "        >\n"
    "    </Field>\n"
    "<!--\n"
    "    <ProducedEvent\n"
    "        name=\"EditingCanceled\"\n"
    "        detailsType=\"ChangeEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"EditingStopped\"\n"
    "        detailsType=\"ChangeEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "-->\n"
    "</FieldContainer>\n",
    "A UI Cell Editor.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &CellEditorBase::getType(void)
{
    return _type;
}

const FieldContainerType &CellEditorBase::getType(void) const
{
    return _type;
}

UInt32 CellEditorBase::getContainerSize(void) const
{
    return sizeof(CellEditor);
}

/*------------------------- decorator get ------------------------------*/


//! Get the CellEditor::_sfEventSource field.
const SFUnrecCellEditorEventSourcePtr *CellEditorBase::getSFEventSource(void) const
{
    return &_sfEventSource;
}

SFUnrecCellEditorEventSourcePtr *CellEditorBase::editSFEventSource    (void)
{
    editSField(EventSourceFieldMask);

    return &_sfEventSource;
}





/*------------------------------ access -----------------------------------*/

SizeT CellEditorBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        returnValue += _sfEventSource.getBinSize();
    }

    return returnValue;
}

void CellEditorBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        _sfEventSource.copyToBin(pMem);
    }
}

void CellEditorBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        editSField(EventSourceFieldMask);
        _sfEventSource.copyFromBin(pMem);
    }
}




/*------------------------- constructors ----------------------------------*/

CellEditorBase::CellEditorBase(void) :
    Inherited(),
    _sfEventSource            (NULL)
{
}

CellEditorBase::CellEditorBase(const CellEditorBase &source) :
    Inherited(source),
    _sfEventSource            (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

CellEditorBase::~CellEditorBase(void)
{
}

void CellEditorBase::onCreate(const CellEditor *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        CellEditor *pThis = static_cast<CellEditor *>(this);

        pThis->setEventSource(source->getEventSource());
    }
}

GetFieldHandlePtr CellEditorBase::getHandleEventSource     (void) const
{
    SFUnrecCellEditorEventSourcePtr::GetHandlePtr returnValue(
        new  SFUnrecCellEditorEventSourcePtr::GetHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             const_cast<CellEditorBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr CellEditorBase::editHandleEventSource    (void)
{
    SFUnrecCellEditorEventSourcePtr::EditHandlePtr returnValue(
        new  SFUnrecCellEditorEventSourcePtr::EditHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&CellEditor::setEventSource,
                    static_cast<CellEditor *>(this), _1));

    editSField(EventSourceFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void CellEditorBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    CellEditor *pThis = static_cast<CellEditor *>(this);

    pThis->execSync(static_cast<CellEditor *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif



void CellEditorBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<CellEditor *>(this)->setEventSource(NULL);


}


OSG_END_NAMESPACE
