/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCOMBOBOXMODELFIELDS_H_
#define _OSGCOMBOBOXMODELFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class ComboBoxModel;

OSG_GEN_CONTAINERPTR(ComboBoxModel);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<ComboBoxModel *, nsOSG> :
    public FieldTraitsFCPtrBase<ComboBoxModel *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<ComboBoxModel *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<ComboBoxModel *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecComboBoxModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComboBoxModel *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecComboBoxModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComboBoxModel *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakComboBoxModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComboBoxModel *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdComboBoxModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComboBoxModel *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecComboBoxModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComboBoxModel *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecComboBoxModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComboBoxModel *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakComboBoxModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ComboBoxModel *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdComboBoxModelPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComboBoxModel *,
                      RecordedRefCountPolicy, nsOSG  > SFRecComboBoxModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComboBoxModel *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecComboBoxModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComboBoxModel *,
                      WeakRefCountPolicy, nsOSG      > SFWeakComboBoxModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<ComboBoxModel *,
                      NoRefCountPolicy, nsOSG        > SFUncountedComboBoxModelPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComboBoxModel *,
                      RecordedRefCountPolicy, nsOSG  > MFRecComboBoxModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComboBoxModel *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecComboBoxModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComboBoxModel *,
                      WeakRefCountPolicy, nsOSG      > MFWeakComboBoxModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<ComboBoxModel *,
                      NoRefCountPolicy, nsOSG        > MFUncountedComboBoxModelPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecComboBoxModelPtr : 
    public PointerSField<ComboBoxModel *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecComboBoxModelPtr : 
    public PointerSField<ComboBoxModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakComboBoxModelPtr :
    public PointerSField<ComboBoxModel *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedComboBoxModelPtr :
    public PointerSField<ComboBoxModel *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecComboBoxModelPtr :
    public PointerMField<ComboBoxModel *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecComboBoxModelPtr :
    public PointerMField<ComboBoxModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakComboBoxModelPtr :
    public PointerMField<ComboBoxModel *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedComboBoxModelPtr :
    public PointerMField<ComboBoxModel *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGCOMBOBOXMODELFIELDS_H_ */
