/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTREEMODELFIELDS_H_
#define _OSGTREEMODELFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TreeModel;

OSG_GEN_CONTAINERPTR(TreeModel);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<TreeModel *, nsOSG> :
    public FieldTraitsFCPtrBase<TreeModel *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TreeModel *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TreeModel *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTreeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModel *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTreeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModel *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTreeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModel *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTreeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModel *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTreeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModel *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTreeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModel *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTreeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModel *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTreeModelPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TreeModel *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTreeModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TreeModel *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTreeModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TreeModel *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTreeModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TreeModel *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTreeModelPtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TreeModel *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTreeModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TreeModel *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTreeModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TreeModel *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTreeModelPtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TreeModel *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTreeModelPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecTreeModelPtr : 
    public PointerSField<TreeModel *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecTreeModelPtr : 
    public PointerSField<TreeModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakTreeModelPtr :
    public PointerSField<TreeModel *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedTreeModelPtr :
    public PointerSField<TreeModel *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecTreeModelPtr :
    public PointerMField<TreeModel *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecTreeModelPtr :
    public PointerMField<TreeModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakTreeModelPtr :
    public PointerMField<TreeModel *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedTreeModelPtr :
    public PointerMField<TreeModel *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTREEMODELFIELDS_H_ */
