/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TreeModel!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#include "OSGConfig.h"



#include "OSGTreeModelEventSource.h"    // EventSource Class

#include "OSGTreeModelBase.h"
#include "OSGTreeModel.h"
#include "OSGTreeModelEventSource.h"
#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TreeModel
    A UI TreeModel.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var TreeModelEventSource * TreeModelBase::_sfEventSource
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<TreeModel *, nsOSG>::_type(
    "TreeModelPtr", 
    "AttachmentContainerPtr", 
    TreeModel::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(TreeModel *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TreeModel *,
                           nsOSG);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TreeModel *,
                           nsOSG);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TreeModelBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecTreeModelEventSourcePtr::Description(
        SFUnrecTreeModelEventSourcePtr::getClassType(),
        "EventSource",
        "",
        EventSourceFieldId, EventSourceFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&TreeModel::editHandleEventSource),
        static_cast<FieldGetMethodSig >(&TreeModel::getHandleEventSource));

    oType.addInitialDesc(pDesc);
}


TreeModelBase::TypeObject TreeModelBase::_type(
    TreeModelBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    NULL,
    TreeModel::initMethod,
    TreeModel::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TreeModel::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "    name=\"TreeModel\"\n"
    "    parent=\"AttachmentContainer\"\n"
    "    library=\"ContribToolboxUserInterface\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "    structure=\"abstract\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "A UI TreeModel.\n"
    "    <Field\n"
    "        name=\"EventSource\"\n"
    "        type=\"TreeModelEventSource\"\n"
    "        category=\"pointer\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"external\"\n"
    "        defaultValue=\"NULL\"\n"
    "        access=\"public\"\n"
    "        >\n"
    "    </Field>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeNodesChanged\"\n"
    "        detailsType=\"TreeModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeNodesInserted\"\n"
    "        detailsType=\"TreeModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeNodesRemoved\"\n"
    "        detailsType=\"TreeModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeNodesWillBeRemoved\"\n"
    "        detailsType=\"TreeModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "    <ProducedEvent\n"
    "        name=\"TreeStructureChanged\"\n"
    "        detailsType=\"TreeModelEventDetails\"\n"
    "        consumable=\"true\"\n"
    "    >\n"
    "    </ProducedEvent>\n"
    "</FieldContainer>\n",
    "A UI TreeModel.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TreeModelBase::getType(void)
{
    return _type;
}

const FieldContainerType &TreeModelBase::getType(void) const
{
    return _type;
}

UInt32 TreeModelBase::getContainerSize(void) const
{
    return sizeof(TreeModel);
}

/*------------------------- decorator get ------------------------------*/


//! Get the TreeModel::_sfEventSource field.
const SFUnrecTreeModelEventSourcePtr *TreeModelBase::getSFEventSource(void) const
{
    return &_sfEventSource;
}

SFUnrecTreeModelEventSourcePtr *TreeModelBase::editSFEventSource    (void)
{
    editSField(EventSourceFieldMask);

    return &_sfEventSource;
}

//! Get the value of the TreeModel::_sfEventSource field.
TreeModelEventSource * TreeModelBase::getEventSource(void) const
{
    return _sfEventSource.getValue();
}

//! Set the value of the TreeModel::_sfEventSource field.
void TreeModelBase::setEventSource(TreeModelEventSource * const value)
{
    editSField(EventSourceFieldMask);

    _sfEventSource.setValue(value);
}






/*------------------------------ access -----------------------------------*/

SizeT TreeModelBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        returnValue += _sfEventSource.getBinSize();
    }

    return returnValue;
}

void TreeModelBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        _sfEventSource.copyToBin(pMem);
    }
}

void TreeModelBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (EventSourceFieldMask & whichField))
    {
        editSField(EventSourceFieldMask);
        _sfEventSource.copyFromBin(pMem);
    }
}




/*------------------------- constructors ----------------------------------*/

TreeModelBase::TreeModelBase(void) :
    Inherited(),
    _sfEventSource            (NULL)
{
}

TreeModelBase::TreeModelBase(const TreeModelBase &source) :
    Inherited(source),
    _sfEventSource            (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

TreeModelBase::~TreeModelBase(void)
{
}

void TreeModelBase::onCreate(const TreeModel *source)
{
    Inherited::onCreate(source);

    if(source)
    {
        TreeModel *pThis = static_cast<TreeModel *>(this);

        pThis->setEventSource(source->getEventSource());
    }
    else
    {
        TreeModelEventSourceUnrecPtr evSrc = TreeModelEventSource::create();
        setEventSource( evSrc );
    }
}

GetFieldHandlePtr TreeModelBase::getHandleEventSource     (void) const
{
    SFUnrecTreeModelEventSourcePtr::GetHandlePtr returnValue(
        new  SFUnrecTreeModelEventSourcePtr::GetHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             const_cast<TreeModelBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr TreeModelBase::editHandleEventSource    (void)
{
    SFUnrecTreeModelEventSourcePtr::EditHandlePtr returnValue(
        new  SFUnrecTreeModelEventSourcePtr::EditHandle(
             &_sfEventSource,
             this->getType().getFieldDesc(EventSourceFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&TreeModel::setEventSource,
                    static_cast<TreeModel *>(this), _1));

    editSField(EventSourceFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void TreeModelBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TreeModel *pThis = static_cast<TreeModel *>(this);

    pThis->execSync(static_cast<TreeModel *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif



void TreeModelBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<TreeModel *>(this)->setEventSource(NULL);


}


OSG_END_NAMESPACE
