/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: David Kabala (djkabala@gmail.com)                                *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTREEMODELEVENTSOURCEFIELDS_H_
#define _OSGTREEMODELEVENTSOURCEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribToolboxUserInterfaceDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TreeModelEventSource;

OSG_GEN_CONTAINERPTR(TreeModelEventSource);
/*! \ingroup GrpContribToolboxUserInterfaceFieldTraits
    \ingroup GrpLibOSGContribToolboxUserInterface
 */
template <>
struct FieldTraits<TreeModelEventSource *, nsOSG> :
    public FieldTraitsFCPtrBase<TreeModelEventSource *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TreeModelEventSource *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTOOLBOXUSERINTERFACE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TreeModelEventSource *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTreeModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelEventSource *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTreeModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelEventSource *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTreeModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelEventSource *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTreeModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelEventSource *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTreeModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelEventSource *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTreeModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelEventSource *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTreeModelEventSourcePtr"; 
}

template<> inline
const Char8 *FieldTraits<TreeModelEventSource *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTreeModelEventSourcePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TreeModelEventSource *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTreeModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TreeModelEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTreeModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TreeModelEventSource *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTreeModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields */
typedef PointerSField<TreeModelEventSource *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTreeModelEventSourcePtr;


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TreeModelEventSource *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTreeModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TreeModelEventSource *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTreeModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TreeModelEventSource *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTreeModelEventSourcePtr;
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields */
typedef PointerMField<TreeModelEventSource *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTreeModelEventSourcePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFRecTreeModelEventSourcePtr : 
    public PointerSField<TreeModelEventSource *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUnrecTreeModelEventSourcePtr : 
    public PointerSField<TreeModelEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFWeakTreeModelEventSourcePtr :
    public PointerSField<TreeModelEventSource *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldSFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct SFUncountedTreeModelEventSourcePtr :
    public PointerSField<TreeModelEventSource *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFRecTreeModelEventSourcePtr :
    public PointerMField<TreeModelEventSource *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUnrecTreeModelEventSourcePtr :
    public PointerMField<TreeModelEventSource *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFWeakTreeModelEventSourcePtr :
    public PointerMField<TreeModelEventSource *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribToolboxUserInterfaceFieldMFields \ingroup GrpLibOSGContribToolboxUserInterface */
struct MFUncountedTreeModelEventSourcePtr :
    public PointerMField<TreeModelEventSource *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTREEMODELEventSourceFIELDS_H_ */
